---
title: "AIDAI"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{AIDAI}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
library(MultiOmics4ImmunAID)
```

# Data
```{r data}
clinic <- read_batches() %>%
    Reduce(rbind, .) %>%
    formate_immunaid()
clinic_code <- read_batches(, "codes")

var_na <- c("Not applicable", "Unknown", "Not performed")
for (i in var_na) {
    clinic[clinic == i] <- NA
}
```

# Distribution
```{r}
aidai_scores0 <- list.map(
    c("", "SecondVisit_"),
    f(i) ~ {
        clin_codes <- clinic_code[[3]] %>%
            filter(str_detect(group_code, paste0("IMA_", i, "General_clinManifScore")))
        pull(clin_codes, column_code) %>%
            select(clinic, .) %>%
            set_colnames(
                str_remove_all(clin_codes$item_name, "\\s*\\([^\\)]+\\)") %>%
                    str_remove_all("( / )?Other (SAID )?") %>%
                    str_remove_all("(Skin rash)|(Sore throat)") %>%
                    to_title()
            )
    }
)

colors <- c(
    "#FEE391", "#FE9929", "#CC4C02", "#B2182B", "#D6604D", "#F4A582", "#F1B6DA", "#DE77AE",
    "#C51B7D", "#8E0152", "#40004B", "#762A83", "#9970AB", "#C2A5CF", "#ABD9E9", "#74ADD1",
    "#4575B4", "#313695", "#01665E", "#35978F", "#80CDC1", "#B8E186", "#7FBC41", "#4D9221",
    "#276419"
)

aidai_scores <- list()
for (i in seq_along(aidai_scores0)) {
    aidai_scores[[i]] <- aidai_scores0[[i]]
    aidai_scores[[i]][aidai_scores0[[i]] == 0] <- NA
}

i <- 1
n <- ncol(aidai_scores[[2]])
color_var <- colorRampPalette(colors)(n)
list.map(
    aidai_scores[[i]],
    f(i, j, k) ~ {
        if (!all(is.na(i))) {
            plot_violin(
                i,
                colour = color_var[j],
                cex = 1,
                title = k,
                width_title = 15,
                pch_alpha = 0.25,
                pch_colour = "black",
                pch_size = 3,
                cex_main = 30,
                cex_sub = 21,
                lwd = 1.5
            ) +
                theme(
                    panel.grid.minor = element_blank(),
                    axis.text.y = element_text(size = 1.5 * 13, color = "gray40")
                ) + ylim(c(0, 30))
        }
    }
) %>%
    compact() %>%
    plot_grid(
        plotlist = .,
        # align = "hv",
        nrow = 2,
        ncol = ceiling(length(.) / 2)
    )

# list.map(
#     aidai_scores[[i]],
#     f(x, y, z) ~ is.na(x) %>% which() %>% length() %>% rep(z, .)
# ) %>%
#     unlist() %>%
#     plot_bar_mcat(cex = 6, width_text = 50, df0 = aidai_scores[[i]])

list.map(
    seq(2),
    f(i) ~ {
        list.mapv(aidai_scores[[i]], f(x) ~ which(x > 0) %>% length()) %>%
            plot_bar(
                threshold = 1,
                sample_size = nrow(aidai_scores[[i]]),
                colour = c("#99000d", "gray")
            )
    }
) %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        ncol = 2
    )

t_aidai <- aidai_scores0[[1]] %>%
    as.data.frame() %>%
    set_rownames(as.numeric(clinic$C_2643_3796))
# use_data(t_aidai, overwrite = TRUE)

# color_var0 <- color_var[c(9, 12)]
list.map(
    names(aidai_scores[[1]]),
    f(i, j) ~ {
        tmp <- list.map(aidai_scores, .[[i]])
        if (!list.any(tmp, f(x) ~ all(is.na(x)))) {
            data.frame(tmp) %>%
                set_colnames(paste(c("First", "Second"), "visit")) %>%
                plot_violin(
                    color_title = color_var[j],
                    colour = c(color_var[j], alpha(color_var[j], alpha = 0.5)),
                    pch_colour = "gray40",
                    pch_alpha = 0.25,
                    pch_size = 3,
                    title = i,
                    cex = 1.2,
                    method = "wilcox"
                ) +
                theme(
                    panel.grid.minor = element_blank(),
                    axis.text.y = element_text(size = 1.5 * 13, color = "gray40")
                ) + ylim(c(0, 30))
        }
    }
) %>%
    compact() %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 2,
        ncol = ceiling(length(.) / 2)
    )
```

# Correlation
```{r}
tiff(
    "cor_biol.tiff",
    units = "px",
    width = 2500,
    height = 2500,
    res = 300
)
aidai_scores[[1]] %>% plot_mcor(method = "spearman")
dev.off()

plot_cor_network(aidai_scores[[1]], ratio_node = 24)

res <- aidai_scores[[1]] %>% correlate()
i <- res$r %>%
    `>`(0) %>%
    which(arr.ind = TRUE) %>%
    as.data.frame()
tmp <- mapply(
    function(x, y) c(rownames(res$r)[x], colnames(res$r)[y]) %>% sort(),
    i$row,
    i$col,
    SIMPLIFY = FALSE
) %>% unique()
color_var <- GimmeMyPlot:::palette_discrete()
list.map(
    tmp,
    f(i, j) ~ plot_cor2(
        select(aidai_scores[[1]], c(i[1], i[2])),
        color = color_var[j],
        cex = 1.7,
        wrap = 15
    )
) -> p
plot_grid(
    plotlist = p,
    align = "hv",
    nrow = 3,
    ncol = 4
)
```
