---
title: "clinics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clinics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages(library(MultiOmics4ImmunAID))
path <- set_environment()
```

# Clinic
```{r clinic}
# Extract items
date <- "20220512"
clin_path <- file.path(path, "clinical", "20220501")
files_raw <- list.files(clin_path)
files_export <- files_raw[grepl("export", files_raw)]
files <- str_split(files_export, "_")
(blocks <- unique(sapply(files, function(i) i[2])))
```

## Clinical
```{r clinical}
clinic <- read_batches()
sapply(clinic, dim)
clinic_tot <- Reduce(rbind, clinic)
clinic_tot <- clean_data(clinic_tot, FALSE)
clinic_code <- read_batches(, "codes")

# Descriptive plots
diagnose_category(clinic_tot[, "C_2649_3888"], top = 100) %>%
    select(-c(N, rank, variables)) %>%
    dplyr::rename(N = freq)
ggpiestats(clinic_tot, "C_2649_3888", ggtheme = theme_classic(base_size = 22), theme_config = theme_perso())
plot_bar(clinic_tot[, "C_2643_3798"], ggtheme = theme_classic(), theme_config = theme_perso())

# Common subject ID between batches
vars <- lapply(clinic, function(i) as.numeric(as.data.frame(i[, 2])[, 1]))
# vars <- lapply(clinic_code, function(i) as.data.frame(i[, 1])[, 1])
names(vars) <- seq(3)
plot_venn(vars)
(inter <- get_intersection(vars))
# Duplicates are identical ? TRUE
identical(as.data.frame(t(clinic[[1]][23, ])), as.data.frame(t(clinic[[2]][37, ])))
# QC from MS is in clinical ? Nope.
which(str_detect(rownames(clinic), "7174"))

# Create batch variable
n <- sapply(vars, length)
batches <- mapply(function(x, y) rep(x, y), seq(3), n)
t_batch <- cbind(unlist(vars), unlist(batches))
t_batch <- t_batch[-which(duplicated(t_batch[, 1])), ]

# Common subject ID with ELISA
vars_clin <- sort(as.numeric(unlist(vars)))
vars_ms <- list(MS = get_patient_id(ms))
vars_prot <- c(list(ELISA = get_patient_id(elisa)), vars_ms)
vars_rna <- list(RNA = get_patient_id(rna))
vars_clin_rna <- c(list(Clinic = vars_clin), vars_rna)
vars_tot <- c(vars_clin_rna, vars_prot)
vars_tot2 <- c(vars, vars_rna, vars_prot)
plot_venn(vars_prot)
plot_venn(vars_clin_rna)
plot_venn(c(vars_prot, vars_rna))
plot_venn(vars_tot) # N = 30
plot_venn(c(vars_ms, vars_clin_rna)) # N = 78 !
# all included in clinic data
plot_venn(vars_tot2)
plot_venn(c(vars, vars_rna, vars_ms))
# all from clinic batch 1
get_intersection(vars_tot)

# Missing data
# Convert some modalities into NA
var_na <- c("Unknown", "Not applicable", "Unreported (not tested or unknown)", "Not performed")
for (i in var_na) {
    clinic_tot[clinic_tot == i] <- NA
}
# find_na(clinic_tot)
# set_missing
clinic_tot_proc <- best_na_percent(clinic_tot, 50)
# clinic_tot_proc <- clinic

plot_missing(
    clinic_tot_proc,
    geom_label_args = list(
        label.size = NA,
        label.padding = unit(0, "lines"),
        size = 3
    ),
    group = list("25%" = 0.25, "50%" = 0.50, "75%" = 0.75, "100%" = 1)
)

(gg_miss_var(clinic_tot, show_pct = TRUE) + theme_classic() + theme_perso()) # %>% ggplotly()
vis_miss(clinic_tot_proc)

clinic_code_proc <- clean_data(clinic_code[[1]])
# vis_miss(clinic_code_proc)
# vis_miss(best_na_percent(clinic_tot_proc, 0))
# Imputation
# res <- summary(aggr(clinic_tot, sortVar = TRUE))$combinations

# Numeric
var_num <- get_name_num(clinic_tot_proc)
clinic_tot_proc <- update_columns(clinic_tot_proc, all_of(var_num), as.numeric)

diagnose_numeric(clinic_tot_proc)

# plot_violin(clinic_tot_proc, colors = rep("blue", 250))
# plot_violin2(clinic_tot_proc, colors = rep("black", 250))
# plot_violin3(clinic_tot_proc, colors = rep("black", 250))

# Date
var_dates <- c("C_2643_3800", "C_2643_3801", "C_2643_3802", "C_2648_3886", "C_2648_3887", "C_2728_4054_1", "C_2729_4054_1", "C_2745_4178_1", "C_2745_4178_2")

clinic_tot_proc <- update_columns(clinic_tot_proc, var_dates, complete_date)
clinic_tot_proc <- update_columns(clinic_tot_proc, var_dates, dmy)
for (i in var_dates) {
    qplot(as.data.frame(clinic_tot_proc[, i])[, 1])
}

clin_proc_year <- update_columns(clinic_tot_proc, var_dates, function(i) year(round_date(i, "year")))
plot_histogram(clin_proc_year)

for (i in var_dates) {
    y <- as.data.frame(as.character(as.data.frame(clin_proc_year[, i])[, 1]))
    diagnose_category(y, top = 100) %>% arrange(freq)
}

# Age in decades
decade <- as.data.frame(as.character(as.data.frame(clin_proc_year[, "C_2643_3800"] - clin_proc_year[, "C_2643_3800"] %% 10)[, 1]))
diagnose_category(decade, top = 100) %>%
    arrange(levels) %>%
    select(-variables)
qplot(decade[, 1])
qplot(as.character(2020 - as.numeric(decade[, 1])))

# Categorical variables
clin_categorial <- select(clinic_tot_proc, -all_of(c(var_dates)))
# clin_categorial <- select(clinic_tot, all_of(c(var_categorial)))
clin_categorial <- update_columns(clin_categorial, "C_2643_3798", as.character)
l_level_cols <- parse_levels(clin_categorial, clinic_code, FALSE)
cols_sim <- col_sim(clin_categorial, clinic_code, FALSE)
# sapply(apply(l_level_cols[-unique(unlist(i_rows)), ], 1, function(x) which(!is.na(x))), length) %>% sort()

regexes <- c("france", "AP-HP", "Mother", "control", "aspirin", "negative\t", "asian", "non african", "partial\t", "response", "flare", "male", "mild", "localized", "months")
i_rows <- lapply(regexes, function(i) detect_difficulty(l_level_cols, i))
j_rows <- seq(nrow(l_level_cols))[-unlist(i_rows)]
tot_rows <- c(i_rows, as.list(j_rows))
l_levels <- lapply(tot_rows, function(i) reformat(l_level_cols[i, ]))
lapply(tot_rows, function(i) unlist(get_level_name(cols_sim, clinic_code[[3]])[i]))
# get_table_occ(clin_categorial, clinic_code, seq(nrow(l_level_cols))[-j_rows], FALSE)

var_categorial <- unlist(cols_sim)
clinic_tot_proc <- update_columns(clinic_tot_proc, var_categorial, as.factor)

to_replace <- list(
    `0` = c("Non African", "No", "None", "Primary failure", "Out of flare", "Male", "Single", "Chronic : > 6 weeks", "Unique", "First episode", "Non symmetrical", "Random", "Negative"),
    `1` = c("African", "Yes", "Partial", "Mild", "Diffuse", "Partial response", "On flare", "Female", "Multiple", "Acute : < 6 weeks", "Recurrent (with remission period)", "Symmetrical", "Patterned", "Positive"),
    `2` = c("Total", "Moderate to severe", "Loss of efficacy", "Localized", "Continuous (without remission)"),
    `3` = c("Complete response")
)

# for (i in seq_along(to_replace)) {
#     for (j in seq_along(to_replace[[i]])) {
#         clinic_tot[clinic_tot == to_replace[[i]][j]] <- paste(i - 1)
#     }
# }
# [[15]]

# group_name
# The top bottom by frequency
diagnose_category(
    clinic_code_proc[, "group_name", drop = FALSE],
    top = 100
) %>% arrange(freq)
# Select the clinic data with 0 NA
var_na <- colnames(clinic_tot_proc)
# Look at the metadata in codes
(stats <- clinic_code_proc %>%
    filter(clinic_code_proc$column_code %in% var_na) %>%
    select(!(starts_with("repeat"))))

get_var_names(var_na, stats)

diagnose_category(as.data.frame(stats$group_name))
# Which is the frequence of this category
clinic_code_proc[, "group_name", drop = FALSE] %>%
    diagnose_category(top = 100) %>%
    filter(str_detect(levels, paste0(unique(stats$group_name), collapse = "|")))
# What are the most frequent modalities for each variable
plot_bar(clinic_tot_proc)
# Create country variable
clinic_tot_proc %>%
    update_columns("C_2643_3797", as.character) %>%
    mutate(
        country = case_when(
            str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg") ~ "France",
            str_detect(C_2643_3797, "Madrid|Barcelona") ~ "Spain",
            str_detect(C_2643_3797, "Leuven") ~ "Belgium",
            str_detect(C_2643_3797, "Rotterdam") ~ "Netherlands",
            str_detect(C_2643_3797, "Athens") ~ "Greece",
            str_detect(C_2643_3797, "Roma") ~ "Italy",
            str_detect(C_2643_3797, "Geneva") ~ "Switzerland",
            str_detect(C_2643_3797, "Ankara") ~ "Turkey",
            str_detect(C_2643_3797, "Münster|Berlin") ~ "Germany",
            str_detect(C_2643_3797, "Leeds") ~ "United Kingdom (UK)",
            str_detect(C_2643_3797, "Lubljana") ~ "Slovenia",
            TRUE ~ C_2643_3797
        )
    ) %>%
    select(country) %>%
    plot_bar(ggtheme = theme_classic(), theme_config = theme_perso())

# By French centers
clinic_tot_proc %>%
    filter(str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg")) %>%
    select(C_2643_3797) %>%
    plot_bar()

# clinic_tot_proc %>%
#     filter(str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg")) %>% select(C_2643_3797) %>% group_by(C_2643_3797) %>% summarise(n = n()) %>% arrange(desc(n))

# By French cities
clinic_tot_proc %>%
    mutate(
        town = case_when(
            str_detect(C_2643_3797, "Paris") ~ "Paris",
            str_detect(C_2643_3797, "Bordeaux") ~ "Bordeaux",
            str_detect(C_2643_3797, "Nantes") ~ "Nantes",
            str_detect(C_2643_3797, "Lyon") ~ "Lyon",
            str_detect(C_2643_3797, "Lille") ~ "Lille",
            str_detect(C_2643_3797, "Strasbourg") ~ "Strasbourg",
            TRUE ~ "Others"
        )
    ) %>%
    select(town) %>%
    plot_bar()

# %>% diagnose_category()

# Correlation
# (p <- select(clinic_tot_proc, all_of(var_num)) %>% plot_corr0(p_adjust = "BH"))
# save_tiff(p)

plot_corr(clinic_tot_proc, stats)
ggcorrmat(clinic_tot_proc)

# Format conversion
var_dates <- colnames(clinic_tot)[which(find_dates(clinic_tot))]
clinic_tot <- update_columns(clinic_tot, var_dates, complete_date)
clinic_tot <- update_columns(clinic_tot, var_dates, dmy)
var_num <- get_name_num(clinic_tot)
clinic_tot <- update_columns(clinic_tot, all_of(var_num), as.numeric)
var_categorial <- colnames(clinic_tot)[which(!(colnames(clinic_tot) %in% c(var_dates, var_num)))]
clinic_tot <- update_columns(clinic_tot, var_categorial, as.factor)

# Stats / outliers
var_num <- get_name_num(clinic_tot_proc)
# slice(clinic, which(clinic$bmi_automatic > 100)) %>%
#   select ("weight_kg", "height_cm", "bmi_automatic", "age_at_inclusion_tim")

col_outliers <- explore_outliers(clinic_tot_proc)
var_socio <- c("C_2643_3803", "C_2643_3804", "C_2649_3889", "C_2649_3890")
i <- col_outliers[1] # "C_2643_3804"
j <- col_outliers[2] # "C_2649_3889"
clin_melt <- melt(clinic_tot_proc) %>% select(variable, value)
outliers <- (clin_melt %>% filter(variable == var_socio[4]) %>% boxplot())$out

# Fix height and bmi errors
clinic_tot_proc <- clinic_tot
tab <- clinic_tot_proc %>%
    filter(C_2649_3890 > 100) %>%
    select(all_of(var_socio))
to_fix <- clinic_tot_proc$C_2649_3890 %in% tab$C_2649_3890
clinic_tot_proc$C_2649_3889[to_fix] <- c(173, 151)
clinic_tot_proc$C_2649_3890[to_fix] <- clinic_tot_proc$C_2643_3804[to_fix] / ((clinic_tot_proc$C_2649_3889[to_fix] / 100)^2)

get_outliers(clinic_tot_proc, i)
# get_outliers(clinic_tot_proc, j, probs = c(.025, .975), method = "percentiles")
# get_outliers(clinic_tot_proc, j, , method = "hampel", c = 3)

clinic_tot_proc <- finalise_data(clinic_tot_proc, clean_name = FALSE, row_name = 2)
codes_proc <- colnames(clinic_tot_proc)

colnames(clinic_tot_proc) <- get_var_names(codes_proc, clinic_code[[1]]) %>%
    str_sub(1, 20)
clinic <- clean_names(clinic_tot_proc)
attributes(clinic)$codes <- tibble(codes = codes_proc, name = colnames(clinic))
# use_data(clinic, overwrite = TRUE)
```

## Clinic transformation
```{r transf}
# Transformations
clinic_num <- select(clinic, sort(get_name_num(clinic)))

var_ord <- ordinal_variables(clinic_num)
var_not_ord <- colnames(select(clinic_num, -all_of(var_ord)))
plot_histo(log1p(select(clinic_num, all_of(var_not_ord))), colors = rep("blue", 250))

var_max <- c("creatinine_mmol_l", "alat_uln_upper_limi", "leucocytes_mm3", "neutrophils_mm3", "ggt_ui_l", "cardiac_manifestatio", "vascular_involvement", "other_neurological_m")
(out <- sapply(var_max, function(i) which.max(as.data.frame(clinic_num[, i])[[1]])))

p <- ggdraw()
for (i in seq(var_max)) {
    p <- p + plot_violin2(as.data.frame(clinic[-out[i], var_max[i]]))
}
p

get_not_normal0(log1p(select(clinic, all_of(var_not_ord))))

# levels from ordinal data
sapply(var_ord, function(i) unique(sort(as.data.frame(clinic_num[, i])[, 1])))
diagnose_category(as.data.frame(sapply(var_ord, function(i) as.factor(as.data.frame(clinic_num[, i])[, 1]))))

# Outliers removing
# plot_violin(select(clinic, alat_uln_upper_limi) %>% filter(alat_uln_upper_limi < 140))
clinic$alat_uln_upper_limi[which(clinic$alat_uln_upper_limi == 269)] <- NA

# Transformations
clinic_transf <- clinic

# X2
# clinic_transf <- update_columns(clinic, "height_cm", function(i) i^2)
# Log transformation
var_log <- c(
    # "abdominal_pain",
    "alat_ui_l",
    "alk_phosphatases_ui",
    "asat_ui_l",
    # "arthralgia_myalgia",
    "bmi_automatic",
    # "bone_pain",
    # "cardiac_manifestatio",
    # "charlson_score_auto",
    # "chest_pain",
    "creatinine_mmol_l",
    "crp_c_reactive_prot",
    # "diarrhea",
    "eosinophils_mm3",
    # "eye_manifestations",
    "fever_38_c_104_f",
    "ggt_ui_l",
    "ggt_uln_ui_l", # bof
    # "headaches",
    # "nausea_vomiting",
    "number_of_consecutiv",
    # "other_neurological_m",
    # "overall_symptoms",
    # "painful_nodes",
    # "skin_rash_other_sa",
    # "sore_throat_other",
    # "swelling_of_the_join",
    "total_bilirubin_mmo"
    # "vascular_involvement",
    # "weight_loss_uninten"
)
# clinic_transf <- update_columns(clinic_transf, var_log, log1p) # %>%
# arrange(immun_aid_identifier)
colnames(clinic_transf) <- codes_proc

# Rename
code_extracted <- extract_codes(codes_proc, clinic_code[[3]])
temp <- str_replace(code_extracted$item_name, " \\(.+\\)|^\\d{1,2}\\. ", "")
names(temp) <- codes_proc
temp <- sort(temp)
codes_temp <- names(temp)
temp <- janitor::make_clean_names(temp)
names(temp) <- codes_temp
temp <- temp[codes_proc]

vars <- c("_patient_included", "_of_disease_activity", "cytological_signs_of_", "_on_secondary_genetic_findings", "_treatment_in_the_last_2_weeks", "_other_said_dermatological_manifestations", "_other_ear_nose_throat_symptoms", "gfr_")
temp <- str_replace(temp, paste(vars, collapse = "|"), "")

keys <- c("date_2", "date", "by", "max")
values <- c("\\1_immunology", "\\1_biology", "consent_signed_by", "max_fever")
for (i in seq_along(keys)) {
    temp <- str_replace(temp, paste0("^(", keys[i], ")$"), values[i])
}

keys <- c("chf", "cva", "copd", "crp", "hb", "uln")
values <- c("Congestive Heart Failure", "Cerebrovascular Accident or Transient Ischemic Attack", "Chronic Obstructive Pulmonary Disease", "C-reactive protein", "Hemoglobine", "Upper Limit of Normal")
for (i in seq_along(keys)) {
    temp <- str_replace(temp, keys[i], janitor::make_clean_names(values[i]))
}

for (i in c(temp[sapply(temp, function(i) str_length(i) < 5)])) {
    if (!i %in% c("type", "urea")) {
        temp <- str_replace(temp, i, toupper(i))
    }
}

temp <- str_replace(temp, "^(neutrophils)_2$", "\\1_percent")
temp <- str_replace(temp, "value_due_to_the_disease", "")

names(temp) <- codes_temp

# code_extracted %>% filter(str_detect(item_name, regex(paste0("^", temp[sapply(temp, function(i) str_length(i) < 5)][-6], collapse = "|"), ignore_case = TRUE))) %>% select(c(group_name, item_name))

# Codes
code_info <- clinic_code[[3]] %>%
    filter(str_detect(column_code, paste0("^", codes_temp, "$", collapse = "|"))) %>%
    select(column_code, group_name)
code_info$group_name <- str_replace(code_info$group_name, " \\(.+\\)", "") %>%
    snakecase::to_any_case(unique_sep = NULL, parsing_option = 3) %>%
    as.factor()
colnames(clinic_transf) <- temp
temp2 <- cbind(code_info, item_name = as.character(temp))

# Dates
# date_vars <- clinic_transf %>% select(which(sapply(colnames(.), function(i) is.Date(as.data.frame(.[, i])[, 1]))))
# cou2 <- (temp2 %>% filter(str_detect(item_name, paste0("^", colnames(date_vars), "$", collapse = "|"))) %>% select(column_code))$column_code
# clinic_code[[3]] %>% filter(str_detect(column_code, paste0("^", cou2, "$", collapse = "|")))

date_biol <- (
    clinic_code[[3]] %>%
        filter(str_detect(group_name, "General biology")) %>%
        filter(str_detect(item_name, "Date"))
)$column_code
biol <- (
    temp2 %>% filter(str_detect(group_name, "biology")) %>%
        filter(!str_detect(item_name, "date"))
)$item_name
clinic_tot2 <- update_columns(clinic_tot, date_biol, dmy)
date_diff <- sapply(seq(4), function(i) clinic$date_of_inclusion - as.data.frame(clinic_tot2 %>% select(all_of(date_biol)))[, i])
# which(abs(date_diff) > 7)
# Closest date is not the first date only for  around 10 elements. And most of the data at these date are NA. So keep the first date that do not influence too much and to know for sure at which date the data are from.
date_corr <- sapply(seq(4), function(i) ifelse(abs(date_diff[, i]) > 7, NA, date_diff[, i]))
colnames(date_corr) <- paste("inclusion - general biology", seq(4))
which_min <- sapply(seq(nrow(date_corr)), function(i) which.min(abs(date_corr[i, ])))
which_min <- sapply(which_min, function(i) ifelse(length(i) == 0, 1, i))
# which(which_min > 1)
# which_min[which_min > 1]
# image(seq(213), 1, as.matrix(which_min), yaxt = "n", labels = FALSE); axis(1, las = 2, at = seq(213), labels = FALSE); axis(1, las = 2, at = seq(0, 213, 5), lwd.ticks = 3)
# as_tibble(date_diff) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))
# (clinic_tot %>% select(all_of(bloup2)) %>% slice(setdiff(which(which_min > 1), which(abs(date_diff) > 7))))[, (1+(8*k)):(8+(8*k))]

filter_week <- abs(date_diff) > 7
filter_week1 <- which(filter_week[, 1])

# for (i in biol) {
#     clinic_transf[filter_week1, i] <- NA
# }

#  clinic_transf %>% select(all_of(biol)) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))
# clinic_transf %>% select(date_biology) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))

t_batch <- arrange(as.data.frame(t_batch), V1)[, 2]

# Save
clinic_transf <- arrange(clinic_transf, immun_aid_identifier) %>%
    mutate(batch = t_batch)
clinic_transf <- finalise_data(clinic_transf, row_name = "immun_aid_identifier", clean_name = FALSE)
attributes(clinic_transf)$codes <- temp2
use_data(clinic_transf, overwrite = TRUE)
```

## Descriptive stats by disease
```{r}
clinic <- clinic_transf
# Filter by disease
diseases <- levels(clinic$disease)
# d2 <- diseases[9]
d1 <- diseases[1]
d0 <- diseases[14]
clinic_dis <- clinic %>%
    filter(
        str_detect(
            disease,
            replace_parenthesis(paste(c(d0, d1), collapse = "|"))
        )
    )
# levels(clinic_dis$disease)[d2 == levels(clinic$disease)] <- "2"
levels(clinic_dis$disease)[d1 == levels(clinic$disease)] <- "1"
levels(clinic_dis$disease)[d0 == levels(clinic$disease)] <- "0"
clinic_dis$disease <- clinic_dis$disease %>%
    factor(., levels = unique(.))

# clinic_dis <- clinic

# All confounding variables in numeric
levels(clinic_dis$gender) <- c(0, 1)
clinic_dis$gender <- as.numeric(as.character(clinic_dis$gender))

# Batch * centers effects
clinic_dis %>%
    group_by(clinical_center) %>%
    mutate(count_name_occurr = n()) %>%
    ggplot(aes(
        x = reorder(clinical_center, -count_name_occurr),
        fill = as.character(batch)
    )) +
    geom_bar(position = "stack") +
    labs(fill = "Batch") +
    stat_count(
        geom = "text",
        colour = "white",
        size = 3.5,
        aes(label = ..count..),
        position = position_stack(vjust = 0.5)
    )

# Filter by numeric variables
clinic_num <- get_name_num(clinic_dis) %>%
    select(clinic_dis, .)
clinic_qual <- which(sapply(seq_along(clinic_dis), function(i) is.factor(as.data.frame(clinic_dis)[, i]))) %>%
    select(clinic_dis, .)

# Remove columns with high levels of NA
# plot_missing(
#     clinic_dis,
#     geom_label_args = list(
#         label.size = NA,
#         label.padding = unit(0, "lines"),
#         size = 3
#     ),
#     group = list("25%" = 0.25, "50%" = 0.50, "75%" = 0.75, "100%" = 1)
# )
#
# gg_miss_var(clinic_dis, show_pct = TRUE) + theme_classic() + theme_perso()
# vis_miss(clinic_dis)

clinic_proc <- finalise_data0(clinic_num, clinic_dis)
clinic_qual_proc <- finalise_data0(clinic_qual, clinic_dis)
colnames(clinic_qual_proc) <- str_replace(colnames(clinic_qual_proc), "(do_you_still_have_the_results).*", "\\1") %>%
    str_replace("(cerebrovascular_accident_or_).*", "\\1ischemic")

# Remove individuals with high levels of NA
# x <- clinic_proc
# res <- sapply(rownames(x), function(i) round((length(which(is.na(x[i, ]))) / ncol(x)) * 100, 1))
# clinic_proc <- clinic_proc[-which(res > 70), ]
clinic_qual_proc <- clinic_qual_proc[-37, ]
use_data(clinic_qual_proc, overwrite = TRUE)

func <- function(x) names(ordinal_variables(clinic_qual_proc, x))
for (i in 2:60) {
    print(setdiff(func(i + 1), func(i)))
}
# sapply(clinic_qual_proc, unique) %>% sapply(length) %>% sort()

to_parse <- sapply(
    seq_along(clinic_qual_proc),
    function(i) any(grepl(";", as.data.frame(clinic_qual_proc[, i])[, 1]))
) %>% which()
l_levels <- sapply(
    to_parse,
    function(i) {
        as.data.frame(clinic_qual_proc[, i])[, 1] %>%
            str_split(";") %>%
            unlist() %>%
            str_trim() %>%
            unique() %>%
            as.character()
    }
)
t_levels <- lapply(
    seq_along(l_levels),
    function(i) {
        sapply(
            na.omit(l_levels[[i]]),
            function(j) {
                as.data.frame(clinic_qual_proc[, to_parse])[, i] %>%
                    str_detect(j) %>%
                    as.numeric()
            }
        ) %>%
            as_tibble() %>%
            clean_names() %>%
            remove_constant(na.rm = TRUE, quiet = FALSE)
    }
)

n_levels <- str_replace(colnames(clinic_qual_proc)[to_parse], "(at_least_3).*", "\\1") %>%
    str_replace(".*(parts_affected)", "\\1") %>%
    mapply(function(i, j) paste(i, j, sep = "_"), ., lapply(t_levels, colnames)) %>%
    unlist()

t_levels <- Reduce(cbind, t_levels) %>%
    set_colnames(n_levels)

clinic_qual_proc <- clinic_qual_proc %>%
    select(-to_parse) %>%
    cbind(t_levels)

# setdiff(names(ordinal_variables(clinic_qual_proc, 3)), names(ordinal_variables(clinic_qual_proc, 2)))

clinic_ord <- set_qualitative(clinic_qual_proc, 2)
mutate_all(clinic_ord, as.numeric) %>%
    as.matrix() %>%
    heatmap(na.rm = FALSE, scale = "none", Rowv = NA, Colv = NA, margins = c(13, 0), col = colorRampPalette(c("blue", "white", "#cd5b45"))(100))

to_remove1 <- (
    diagnose_category(clinic_ord) %>%
        filter(!is.na(levels)) %>%
        filter(freq < 5)
)$variables %>%
    unique()
clinic_ord0 <- set_qualitative(clinic_qual_proc, 3)
to_remove2 <- (
    diagnose_category(select(clinic_ord0, -c(to_remove1))) %>%
        filter(is.na(levels)) %>%
        filter(freq < 5)
)$variables

clinic_ord <- select(clinic_ord, -c(to_remove1))

# plot_histo(as.data.frame(clinic_proc %>% select(-disease)), colors = rep("blue", 200))

# Proportion of ordinal data modalities
perc <- mutate_all(clinic_ord, as.numeric) %>%
    pivot_longer(all_of(colnames(clinic_ord))) %>%
    group_by(name, value) %>%
    summarise(`%` = n()) %>%
    pivot_wider(names_from = name, values_from = c(`%`))
temp <- t(perc)[-1, ] %>%
    cbind(., round(. / nrow(clinic_qual_proc), 2)) %>%
    as.data.frame() %>%
    set_colnames(rep(c(paste("Cat.", seq(2)), "NA"), 2))
temp[is.na(temp)] <- 0
temp[seq(6)] <- lapply(temp[seq(6)], function(x) {
    cell_spec(
        x,
        color = "white",
        background = spec_color2(x, end = 0.9, option = "D")
    )
})

temp %>%
    kbl(escape = F, align = "c") %>%
    kable_minimal() %>%
    add_header_above(c(" " = 1, "N" = 3, "%" = 3)) %>%
    save_kable("table.temp.png")

# clinic_dis[, "disease"] %>% group_by(disease) %>% summarise(`%` = n())

# Remove all ordinal data with low occurrences
perc0 <- perc %>% filter(!is.na(value))
n <- 4
var_occ <- names(which(apply(perc0[, -1], 2, function(x) any(x <= n))))
perc0 %>% select(-var_occ)

# clinic_num0 <- clinic_proc %>%
#   select(
#     -all_of(
#       c(names(ordinal_variables(clinic_proc, 3)), "immun_aid_identifier")
#       )
#   )

# plot_histo(clinic_num0, colors = rep("blue", 200))

# Remove all ordinal data with low occurrences
clinic_proc0 <- clinic_proc[, sort(colnames(clinic_proc))] %>%
    select(-all_of(c(var_occ, "immun_aid_identifier", "gender")))
# clinic_proc0$disease <- factor(clinic_proc0$disease, labels = rev(c(diseases[9], diseases[1])))

# Descriptive statistics
stats <- clinic_proc0 %>%
    pivot_longer(!disease) %>%
    group_by(name, disease) %>%
    summarise(
        mean = mean(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
        n = length(which(!is.na(value)))
    ) %>%
    pivot_wider(names_from = disease, values_from = c(mean, sd, n)) %>%
    mutate(ratio = (n_0 / n_1))

sds <- apply((clinic_proc0 %>% select(-disease)), 2, function(x) sd(x, na.rm = TRUE))
stats$samplesize <- calculate_samplesize(stats$mean_0, stats$mean_1, sds, stats$ratio)
stats$effectsize <- abs(calculate_effectsize(stats$mean_0, stats$mean_1, sds))

# Remove the variables with only NA in control
stats0 <- stats %>% filter(!is.na(mean_0))
# stats0 %>% arrange(samplesize)

not_in_control <- (stats %>% filter(is.na(mean_0)))$name

# Mean difference tests
tests <- clinic_proc0 %>%
    select(-all_of(not_in_control)) %>%
    pivot_longer(!disease) %>%
    group_by(name) %>%
    wilcox_test(value ~ disease) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance()

# Total statistics
left_join(stats0, tests[, c(1, 8:10)]) %>% arrange(samplesize)

vars <- c("age_at_inclusion_time", "batch", "BMI", "gender")
vars2 <- c("disease", "immun_aid_identifier", "weight", "height")

row_names <- rownames(clinic_proc)
clinic_proc <- clinic_proc %>% select(-c(vars2, ends_with("_upper_limit_of_normal")))

# Transformation
norm_vars <- list()
norm_vars[[1]] <- normality(clinic_proc) %>%
    filter(p_value > 0.05) %>%
    select(vars)
skew <- ((clinic_proc) %>% select(-c(unlist(norm_vars))) %>%
    sapply(function(i) skewness(i)))
temp <- data.frame(var = skew) %>%
    filter(var < 0) %>%
    row.names() %>%
    select(clinic_proc, .)
norm_vars[[2]] <- temp^2 %>%
    normality() %>%
    filter(p_value > 0.05) %>%
    select(vars)
norm_vars[[3]] <- temp^3 %>%
    normality() %>%
    filter(p_value > 0.05) %>%
    select(vars)
norm_vars[[4]] <- (log(clinic_proc + 1)) %>%
    select(-c(unlist(norm_vars))) %>%
    normality() %>%
    filter(p_value > 0.05) %>%
    select(vars)
norm_vars[[5]] <- (1 / (clinic_proc + 1)) %>%
    select(-c(unlist(norm_vars))) %>%
    normality() %>%
    filter(p_value > 0.05) %>%
    select(vars)
norm_vars[[6]] <- ((clinic_proc)^(1 / 2)) %>%
    select(-c(unlist(norm_vars))) %>%
    normality() %>%
    filter(p_value > 0.01) %>%
    select(vars)

# transf <- c(function(i) i ^ 2, function(i) i ^ 3, function(i) log(i  + 1), function(i) 1 / (i + 1), function(i) i ^ (1 / 2))
# for (i in seq(transf)) {
#   clinic_proc <- update_columns(clinic_proc, all_of(unlist(norm_vars[[i + 1]])), transf[[i]])
# }
clinic_proc <- update_columns(clinic_proc, colnames(clinic_proc), log1p)
cl <- clinic_proc
cl$gender <- as.factor(cl$gender)
cl$batch <- as.factor(cl$batch)
blocks_cl <- clinic_proc %>% as.data.frame()
rownames(blocks_cl) <- clinic_proc$immun_aid_identifier
blocks_clinic_still <- remove_cofunding(list(CLINIC = blocks_cl), vars)

blocks_clinic_still[[1]] <- select(blocks_clinic_still[[1]], -all_of(c(vars))) #   <-  list(CLINIC = select(blocks_cl, -all_of(vars)))
blocks_clinic_still[[1]] <- clean_data(blocks_clinic_still[[1]])
attributes(blocks_clinic_still)$codes <- Reduce(rbind, lapply(colnames(blocks_clinic_still[[1]]), function(i) filter(temp2, str_detect(item_name, paste0("^", i, "$")))))
# Reduce(rbind, lapply(temp0$column_code, function(i) filter(clinic_code[[3]], str_detect(column_code, paste0("^", i, "$"))))) %>% select(-c(starts_with("repeat"), ends_with("_id"))) %>% as.data.frame()
clinic_control_still <- blocks_clinic_still
# use_data(clinic_control_still, overwrite = TRUE)
```

## Qualitative variables
```{r}
codes_qual <- Reduce(rbind, lapply(colnames(clinic_proc), function(i) filter(temp2, str_detect(item_name, paste0("^", i, "$")))))
codes_qual %>%
    group_by(group_name) %>%
    summarise(n = n()) %>%
    arrange(n)

# Reduce(rbind, lapply(temp, function(i) filter(clinic_code[[3]], str_detect(column_code, paste0("^", i, "$"))))) %>% select(-c( starts_with("repeat") )) %>% arrange(group_id)

clinic_proc <- mutate_all(clinic_qual_proc, factor)
clinic_proc$treatment_7[clinic_proc$treatment_7 == "Other"] <- NA
lvl <- c("No", "Yes", "Yes")
keys <- c("response_to_paracetamol", "response_to_nsai_ds", "active_manifestation_2")
val <- list(lvl, lvl, c("Continuous or reccurent", "First episode", "Continuous or reccurent"))
for (i in seq(3)) {
      clinic_proc[, keys[i]] <- recode_factor(as.numeric(clinic_proc[, keys[i]]), !!!val[[i]])
  }

i <- "response_to_biologic_treatments"
clinic_proc[, i] <- recode_factor(clinic_proc[, i], No = "Partial", .default = levels(clinic_proc[, i]))


for (i in c("fathers_ethnicity", "mothers_ethnicity")) {
      clinic_proc[, i] <- recode_factor(as.numeric(clinic_proc[, i]), !!!c(rep("Not European", 3), "European"))
  }

temp <- select(clinic_qual, starts_with("treatment_group"))
l_levels0 <- unlist(temp) %>%
    unique() %>%
    as.character()
temp <- unite(temp, col = "treatments_type", na.rm = TRUE, treatment_group:treatment_group_28, sep = " ; ")
l_levels1 <- na.omit(l_levels0)[-7]
temp <- sapply(
    l_levels1,
    function(j) {
        as.data.frame(temp)[, 1] %>%
            str_detect(replace_parenthesis(j)) %>%
            as.numeric()
    }
) %>% set_colnames(str_replace(l_levels1, "\\(.+\\)", ""))
temp <- temp %>%
    as_tibble() %>%
    set_colnames(paste0("treatment_", colnames(temp))) %>%
    clean_names()

for (i in c("response", "response_3")) {
      clinic_proc[, i] <- recode_factor(
          clinic_proc[, i],
          `Loss of efficacy` = "Failure or loss of efficacy",
          `Primary failure` = "Failure or loss of efficacy",
          .default = levels(clinic_proc[, i])
      )
  }

clinic_proc$response_2 <- recode_factor(as.numeric(clinic_proc$response_2), !!!c("Complete response", rep("Partial response or failure", 2)))


clinic_proc$treatment_group_3 <- recode_factor(as.numeric(clinic_proc$treatment_group_3), !!!c("Biologic", "Others", "DMARDs", rep("Others", 3)))
clinic_proc$treatment_group_2 <- recode_factor(as.numeric(clinic_proc$treatment_group_2), !!!c("Biologic", "Corticosteroid", "DMARDs", rep("Others", 3)))

clinic_proc$country_of_residence <- recode_factor(as.numeric(clinic_proc$country_of_residence), !!!c("Others", "France", rep("Others", 3)))
i <- "manifestation_s_2"
clinic_proc[, i] <- recode_factor(as.numeric(clinic_proc[, i]), !!!c(levels(clinic_proc[, i])[seq(2)], rep("Others", 3)))
clinic_proc$country_of_birth <- recode_factor(as.numeric(clinic_proc$country_of_birth), !!!c(rep("Others", 3), "France", rep("Others", 4)))
# clinic_proc <- clinic_proc %>%
#     update_columns("clinical_center", as.character) %>%
#     mutate(
#         country = case_when(
#             str_detect(clinical_center, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg") ~ "France",
#             TRUE ~ "Others"
#         )
#     )

clinic_qual <- select(clinic_proc, -c(to_remove1, to_remove2, "clinical_center", "liver_disease")) %>%
    cbind(data.frame(temp, immun_aid_identifier = clinic_dis$immun_aid_identifier)[-37, ])
clinic_qual <- finalise_data(clinic_qual, row_name = "immun_aid_identifier", clean_name = FALSE) %>%
    select(-c("immun_aid_identifier"))
attributes(clinic_qual)$codes <- codes_qual
# use_data(clinic_qual, overwrite = TRUE)
```

## Descriptive stats for each disease
```{r}
data(clinic)
vars <- c("ferritin_mg_l", "crp_c_reactive_prot", "leucocytes_mm3", "fever_38_c_104_f", "physician_global_ass")
i <- vars[2]
res <- clinic %>%
    select(all_of(c("disease", vars))) %>%
    filter(!str_detect(disease, "Negative control")) %>%
    pivot_longer(!disease) %>%
    group_by(name, disease) %>%
    summarise(
        mean = mean(value, na.rm = TRUE),
        median = median(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
        quantiles = paste(quantile(value, c(0.25, 0.75), na.rm = TRUE), collapse = "-"),
        range = paste(range(value, na.rm = TRUE), collapse = "-"),
        n = length(which(!is.na(value))),
        na = length(which(is.na(value)))
    )

res %>% filter(name == i)


tiff(
    paste0(i, ".tiff"),
    units = "px",
    width = 3000,
    height = 2000,
    res = 300
)
(ggbetweenstats(
    (clinic %>% select(all_of(c("disease", i)))),
    x = disease,
    y = crp_c_reactive_prot,
    p.adjust.method = "BH",
    type = "nonparametric",
    centrality.point.args = list(size = 0),
    centrality.label.args = list(
        size = 3,
        fill = NA,
        label.size = NA,
        segment.linetype = 0
    ),
    pairwise.comparisons = FALSE
)) %>%
    theme_perso0(colors = c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 9, name = "Set2"))) +
    guides(fill = "none", color = "none") +
    theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust = 1))
dev.off()
```

## Clinical0

```{r}
clinic0 <- read_tsv(file.path(path, "CleanBiologicalValues.tsv"))
clinic0 <- arrange(clinic0, ID) %>%
    clean_names()
colnames(clinic0) <- str_sub(colnames(clinic0), 1, 20)
clinic <- arrange(clinic, immun_aid_identifier)
# identical(clinic0$id, clinic$immun_aid_identifier)
to_exclude <- c(
    "description",
    "precise",
    "coombs_test_positive",
    "conj_bili_mmol_l",
    "in",
    "antibody_structure",
    "isotype",
    "light_chain",
    "serum_peak_g_l",
    "ldh_u_l",
    "triglycerides_mmol_l",
    "crp_2nd_visit",
    "saa_2nd_visit"
)
#  "neutrophils_mm3"    "schizocytes_percen" "erythrocyte_sedime"
to_select <- c(
    "immun_aid_identifier",
    "disease",
    "age_at_inclusion_tim",
    "gender",
    "type",
    "hb_g_d_l",
    "mean_red_cell_volume",
    "leucocytes_mm3",
    "lymphocytes_mm3",
    "neutrophils_percent",
    "eosinophils_mm3",
    "platelets_mm3",
    "cytological_signs_of",
    "evidence_of_active",
    "crp_c_reactive_prot",
    "max_crp_value_due_to",
    # "saa_serum_amyloid_a",
    # "fibrinogen_level_g",
    "total_bilirubin_mmo",
    "sodium_mmol_l",
    "potassium_mmol_l",
    # "protidemia_g_l",
    # "albuminemia_g_l",
    "creatinine_mmol_l",
    "gfr_glomerular_fil",
    "urea_mmol_l",
    "alat_ui_l",
    "alat_uln_upper_limi",
    "asat_ui_l",
    "asat_uln_ui_l",
    "ggt_ui_l",
    "ggt_uln_ui_l",
    # "alk_phosphatases_uln",
    # "ferritin_mg_l",
    # "glycosylated_ferriti",
    # "monoclonal_gammapath",
    "alk_phosphatases_ui"
)
clinic0 <- select(clinic0, -c(batch, days_from_inclusion, date_of_biological_a)) %>%
    select(-all_of(to_exclude))
# ,saa_serum_amyloid_a
clinic1 <- select(clinic, all_of(c(to_select)))
colnames(clinic0) <- str_sub(colnames(clinic0), 1, 18)
colnames(clinic1)[c(1, 3:4)] <- c("id", "age", "sex")
colnames(clinic1) <- str_sub(colnames(clinic1), 1, 18)
get_intersection0(list(A = colnames(clinic1), B = colnames(clinic0)))
clinic0[clinic0 == "Not performed"] <- NA
# save_tsv(clinic0, filename = "clinic0.temp")
# save_tsv(clinic1, filename = "clinic1.temp")
# i_rows <- which(!mapply(identical, as.numeric(clinic0$urea_mmol_l), as.numeric(clinic1$urea_mmol_l)))
```

## Extraction for Geneve lab
```{r}
clinic <- read_batches()
clinic_tot <- Reduce(rbind, clinic)
codes <- clinic_code[[3]] %>% select(!(starts_with("repeat")))
l_codes <- c()

l_codes <- c(l_codes, (codes %>% filter(str_detect(item_name, "identifier|Disease|Date of inclusion")) %>%
    filter(str_detect(group_name, "Patient information")))$column_code)
# l_codes <- c(l_codes, (codes %>% filter(str_detect(item_name, "Gender")))$column_code)

# Visite 1
## 1.7 Disease activity
vis1 <- codes %>% slice(-detect_difficulty(., "second"))
l_codes <- c(l_codes, (vis1 %>% filter(str_detect(item_name, "fatigue|global")))$column_code)
l_codes <- c(l_codes, (vis1 %>% slice(detect_difficulty(., "aidai")))$column_code)

## 2. Clinical manifestations
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "triggering")))$column_code)
l_codes <- c(l_codes, (vis1 %>% filter(str_detect(group_name, "Fever")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "response to therapie")))$column_code)
l_codes <- c(l_codes, (vis1 %>% slice(detect_difficulty(., "weight loss")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "other signs")))$column_code)

## 4.1 General biology
l_codes <- c(l_codes, (codes %>%
    filter(str_detect(item_name, "Date")) %>%
    filter(str_detect(group_name, "General biology")))$column_code)
l_codes <- c(l_codes, (vis1 %>%
    slice(detect_difficulty(., "CRP|SAA")) %>%
    filter(str_detect(group_name, "General biology")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "\tferritin")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "Erythrocyte")))$column_code)

## 5. Systemic therapies
sys <- codes %>% filter(str_detect(group_code, "SystemicTherapies"))
vars <- c(
    "Treatment group",
    "Date of beginning",
    "Response",
    "over",
    "Treatment category",
    "Treatment$",
    "Every",
    "[Dd]ose",
    "Period"
)
l_codes <- c(l_codes, (sys %>% filter(str_detect(item_name, paste(vars, collapse = "|"))))$column_code)

sys %>%
    filter(str_detect(item_name, "Treatment$")) %>%
    filter(str_detect(group_name, "Biologic$")) %>%
    count("item_code")
sys %>%
    filter(str_detect(item_name, "Every|Period")) %>%
    count("group_name")
unique((sys %>% slice(detect_difficulty(., "dose")))$item_name)
sys %>%
    slice(detect_difficulty(., "dose")) %>%
    count("group_name")
sys %>%
    slice(detect_difficulty(., "\tadministrated")) %>%
    count("group_name")
sys %>%
    filter(str_detect(group_name, "Corticosteroid")) %>%
    slice(detect_difficulty(., "dose")) %>%
    count("item_name")

# Visite 2 & follow up
vis2 <- codes %>% slice(detect_difficulty(., "second|followup"))
l_codes <- c(l_codes, (vis2 %>%
    slice(detect_difficulty(., "date of the visit|evolution|CRP|SAA")) %>%
    filter(!str_detect(item_name, "Persistant")))$column_code)

# Extraction codes
clinic_extraction <- clinic_tot %>% select(all_of(l_codes))
clinic_geneve <- clean_data(clinic_extraction, FALSE, FALSE)
codes_extraction <- extract_codes(colnames(clinic_geneve), clinic_code[[3]])
code_names0 <- sapply(
    seq(nrow(codes_extraction)),
    function(i) {
        paste0(
            codes_extraction[i, "item_name"],
            {
                res <- codes_extraction[i, "repeat_inds"]
                ifelse(is.na(res), "", paste0(" - ", res))
            }
        )
    }
)

code_names <- sapply(
    seq(nrow(codes_extraction)),
    function(i) {
        paste0(
            codes_extraction[i, "group_name"],
            " - ",
            code_names0[i]
        )
    }
)

i_rows <- which(code_names %>% str_detect("Biologic - Treatment"))
# code_names <- str_replace(code_names, "Biological values", "Second visit general biology")
pat <- str_replace(as.data.frame(codes_extraction[i_rows, "item_code"])[, 1], "IMA_SYSTHERAPY_TREATMENT_BIO(_TREAT_)?", "")
code_names[i_rows] <- str_trim(paste(pat, code_names[i_rows]))
i_rows <- which(code_names %>% str_detect("Biological values"))
code_names[i_rows] <- paste0(rep(c("Second visit", "Follow up"), each = 3), " general biology", str_replace(code_names[i_rows], "Biological values", ""))

t_clinic_geneve <- as_tibble(t(clinic_geneve))
colnames(t_clinic_geneve) <- clinic_geneve$C_2643_3796
t_clinic_geneve <- as_tibble(cbind(codes_extraction, t_clinic_geneve))

colnames(clinic_geneve) <- code_names

# Closest date for general biology
date_vars <- colnames(clinic_geneve)[which(find_dates(clinic_geneve))]
clinic_geneve <- update_columns(clinic_geneve, date_vars, dmy)
date_diff <- sapply(2:5, function(i) as.numeric(as.data.frame(clinic_geneve[, date_vars[1]] - clinic_geneve[, date_vars[i]])[, 1]))
date_corr <- sapply(seq(4), function(i) ifelse(abs(date_diff[, i]) > 7, NA, date_diff[, i]))
colnames(date_corr) <- paste("inclusion - general biology", seq(4))
which_min <- sapply(seq(nrow(date_corr)), function(i) which.min(abs(date_corr[i, ])))
which_min <- sapply(which_min, function(i) ifelse(length(i) == 0, 1, i))

get_min <- function(x) {
    temp <- as.data.frame(clinic_geneve[, colnames(clinic_geneve) %>% str_detect(paste0("General biology - ", x))])
    colnames(temp) <- seq(4)
    temp <- tibble(temp)
    temp[temp == "Not performed"] <- NA
    temp <- update_columns(temp, seq(4), as.numeric)
    unlist(sapply(seq(nrow(temp)), function(i) {
        res <- temp[i, which_min[i]]
        ifelse(is.na(res), ifelse(is.na(temp[i, 1]), temp[i, 2], temp[i, 1]), res)
    }))
    # View(cbind(which_min, temp, temp2))
}

vars <- c("CRP \\(", "Max CRP", "SAA", "Ferritin", "Erythrocyte")
temp <- sapply(vars, get_min)
colnames(temp) <- paste("closest", str_replace(vars, " \\\\\\(", ""))
colnames(clinic_geneve) <- code_names0
# sapply(seq(ncol(temp3)), function(i) length(which(is.na(temp3[, i]))))
clinic_geneve <- cbind(clinic_geneve, date_corr, temp)

# Output
library(openxlsx)
file_path <- file.path(golem::get_golem_wd(), "clinic_extraction.temp.xlsx")
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, "Sheet 1", clinic_geneve)
addWorksheet(wb, "Sheet 2")
writeData(wb, "Sheet 2", t_clinic_geneve)
saveWorkbook(wb, file = file_path, overwrite = TRUE)

# sapply(colnames(clinic_geneve), function(i) strsplit(i, " - ")[[1]][2:])
# common_vars <- setdiff(colnames(clinic_tot_proc), l_codes)
```

## Bruno
```{r}
clinic0 <- read_batches()
clinic_tot0 <- Reduce(rbind, clinic0)
clinic_tot1 <- clinic_tot0 %>%
    filter(str_detect(
        C_2643_3798,
        replace_parenthesis(paste(
            c("SOJIA", "AOSD"),
            collapse = "|"
        ))
    ))

data(clinic)
attributes(clinic)$codes
# extract_codes0("age_at_inclusion_tim")

clinic_tot <- clinic %>%
    filter(str_detect(
        disease,
        replace_parenthesis(paste(
            c("SOJIA", "AOSD"),
            collapse = "|"
        ))
    ))

data(clinic_qual)
# data(clinic_qual_proc)
# clinic_qual <- clinic_qual_proc
diagnose_category(clinic_qual)

get_item_name <- function(x) {
    (filter(
        clinic_code[[1]],
        str_detect(
            column_code,
            paste0("^", extract_codes0(x), "$")
        )
    )
    )$item_name
}

# persistant_systemic treatment_group
i <- "active_manifestation_2"
# will_have_a_second_v
summary_cat <- function(i) {
    df <- as.data.frame(clinic_tot[, i])[, 1] %>%
        fct_explicit_na() %>%
        as.data.frame() %>%
        set_colnames("var")
    print(diagnose_category(df))
    leg_title <- get_item_name(i)
    ggpiestats(
        df,
        var,
        label = "both",
        results.subtitle = FALSE
    ) +
        scale_fill_manual(
            values = brewer.pal(n = 9, name = "Set1"),
            na.value = "black"
        ) +
        guides(fill = guide_legend(title = leg_title)) # +
    # plot_bar(
    #     df,
    #     ggtheme = theme(
    #         strip.text.x = element_blank(),
    #         panel.border = element_blank(),
    #         panel.background = element_blank()
    #     ),
    #     theme_config = theme_perso()
    # )
}

var_cat <- c(
    "patient_ethnicity_n",
    "fathers_ethnicity",
    "mothers_ethnicity",
    "gender"
)
plot_piechart(
    clinic_tot$patient_ethnicity_n,
    colour = c("#af3e40", "#eaaab0"),
    cex = 40,
    dec = 1,
    label = FALSE
)
plot_piechart(
    clinic_tot$gender,
    colour = c("#3438a7", "#38bcbd"),
    cex = 20
)
plot_piechart(
    clinic_tot$will_have_a_second_v,
    colour = brewer.pal(9, "Paired")[7:8],
    cex = 20
)
df <- cut(clinic_tot$age_at_inclusion_tim, breaks = seq(0, 70, 10)) %>%
    data.frame() %>%
    set_colnames("ages")
apyramid::age_pyramid(
    data = df,
    age_group = "ages",
    split_by = "gender",
    proportional = FALSE,
    show_midpoint = FALSE
) +
    theme_bw() +
    scale_fill_manual(values = c("#3438a7", "#38bcbd"), na.value = "black")
data(clinic_still_raw)
summary_num <- function(i, colors = "red") {
    df <- data.frame(var = as.data.frame(clinic_tot[, i])[, 1])
    print(df$var)
    print(get_summary_stats(df)[, -1])
    print(diagnose(df)[, -1])
    print(diagnose_outlier(df)[, -1])
    plot_grid(
        gghistostats(
            data = df,
            x = var,
            results.subtitle = FALSE,
            bar.fill = "red",
            centrality.line.args = list(size = 1, color = "red")
        ) +
            theme_bw() +
            theme_perso() +
            labs(x = get_item_name(i)) +
            theme(panel.border = element_blank(), panel.grid.major = element_blank()),
        plot_violin(df, colors = colors) + theme(
            strip.text.x = element_blank(),
            axis.line = element_blank(),
            panel.grid.major = element_line()
        )
    )
}
# temp <- clinic_code[[1]] %>% filter(str_detect(group_code, "^IMA_NeuroManif")) ; select(clinic_tot0, temp$column_code) %>% set_colnames(temp$item_name) %>% View()
# na.omit(clinic_tot0$C_2663_3967_1) %>% str_split_fixed(" ; ", 6) %>% as.character() %>% str_subset(".+") %>% plot_bar()
# %>% as.data.frame() %>% set_colnames("x") %>% group_by(x) %>% summarise(n = n()) %>% arrange(desc(n))
# %>% as.factor() %>% fct_count() %>% arrange(desc(n))
# clinic_code[[1]] %>% filter(str_detect(group_code, "^IMA_ImpactedOrganOrSysTab")) %>% select(clinic_tot0, .$column_code) %>% set_colnames(.$item_name) %>% update_columns(colnames(.), function(i) recode_factor(i, "Yes" = 1, "No" = 0, "Unknown" = 0)) %>% update_columns(colnames(.), as.character) %>% update_columns(colnames(.), as.numeric) %>% rowSums(na.rm = TRUE)
# clinic_tot1$C_2745_4179_1 %>% fct_lump_min(min = 5, other_level = "Absence") %>% fct_count()  %>% arrange(desc(n))
# major criteria: skin_rash_other_sa, fever_38_c_104_f, leucocytes_mm3, neutrophils_mm3, eosinophils_mm3, arthralgia_myalgia
# biomarkers: crp_c_reactive_prot ferritin_mg_l (glycosylated_ferriti)
# LFT: total_bilirubin_mmo alk_phosphatases_ui alat_ui_l asat_ui_l
# cofounding: bmi_automatic, age_at_inclusion_tim
# to transform: diagnosis_day
i <- "ferritin_mg_l"
summary_num(i)
# plot_outlier(var)
plot_violin0(clinic_tot$bmi_automatic, brewer.pal(n, "Set2")[6], size = 3)
plot_violin0(clinic_tot$age_at_inclusion_tim, brewer.pal(n, "Set2")[5], size = 3)
# Manifestations
vars0 <- clinic_code[[3]] %>%
    filter(str_detect(group_code, "IMA_ImpactedOrganOrSysTab"))
vars1 <- vars0 %>%
    pull(item_name) %>%
    str_replace("(\\d{1,2}. )", "") %>%
    str_replace("\\s*\\([^\\)]+\\)", "")
manifs <- c("MUSCU", "CARDIO", "GASTRO", "HAEMATO")
# If all disease
# manifs <- c(manifs, "OPHTALMO", "OPHTALMO", "ENT")
# (PULMO) NEURO, URO
# vars <- vars1[c(1, 3:4, 7, 9, 9, 8, 11)]
vars <- vars1[c(1, 3:4, 7, 11)]
manifs <- c("MUCO_ACTIVE_LESIONS", paste0(manifs, "_MANIF"))

# list.map(as.list(manifs), f(i, j) ~{
#     immu_manif(i, df2 = clinic_tot1) %>%
#         collapse_mcat() %>%
#         plot_bar_mcat(cex = 8, ratio = 4, title = vars[j])
# }) -> p
# align_plots(plotlist = p, align = "vh") %>%
#     plot_grid(
#         plotlist = .,
#         nrow = 3,
#         ncol = 3,
#         # labels = "AUTO",
#         rel_heights = c(1.5, 1, 0.6)
#     )

list.map(as.list(manifs), f(i, j) ~ {
    immu_manif(i, df2 = clinic_tot1) %>%
        collapse_mcat() %>%
        plot_bar_mcat(cex = 12, ratio = 3, title = vars[j])
}) -> p
align_plots(plotlist = p, align = "vh") %>%
    plot_grid(
        plotlist = .,
        nrow = 3,
        ncol = 2,
        # labels = "AUTO",
        rel_heights = c(1.7, 1, 1)
    )
# ((colSums(temp0) / nrow(temp0)) * 100) %>% round(1)
# align_plots(plotlist = c(p2[-1], p2[1])) %>% plot_grid(plotlist = ., align = "vh", nrow = 4, ncol = 2, labels = LETTERS, rel_heights = c(rep(1, 3), 1.5))
vars <- vars0 %>%
    pull(column_code) %>%
    paste0("^", ., "$", collapse = "|")
vars <- filter(attributes(clinic_tot)$codes, str_detect(codes, vars)) %>% pull(name)
p <- list.map(
    as.list(vars),
    f(i, j) ~ plot_piechart(
        clinic_tot %>% pull(i),
        label = FALSE,
        cex = 25,
        dec = 1,
        threshold = 5,
        title = vars1[j],
        hsize = 1.5
    )
)
align_plots(plotlist = p, align = "vh") %>%
    plot_grid(
        plotlist = .,
        nrow = 3,
        ncol = 4
    )

codes <- attributes(clinic_still_processed)$codes
temp <- sapply(unique(codes$group_name), function(i) {
    filter(codes, group_name == i) %>%
        select(item_name) %>%
        unlist() %>%
        unname() %>%
        rename0()
})
temp <- unique(codes$group_name) %>%
    rename0(sep = "\n") %>%
    toupper() %>%
    set_names(temp, .)

names(temp)[5] <- "AIDI\nSCORE\nON 30 DAYS"
to_replace <- c("Asat", "Ggt", "Alat")
temp[[6]][temp[[6]] %in% to_replace] <- toupper(to_replace)
temp[[6]][temp[[6]] == "Neutrophils 5"] <- "Neutrophils %"

nodes <- data.frame(id = unlist(temp), size = rep(6, length(unlist(temp))))
edges <- lapply(seq_along(temp), function(i) {
      data.frame(
          from = names(temp)[i],
          to = temp[[i]],
          weight = .2
      )
  }) %>% Reduce(rbind, .)

nodes <- sapply(temp, length) %>%
    data.frame(id = names(.), size = .) %>%
    list(., nodes) %>%
    Reduce(rbind, .) %>%
    rbind(., data.frame(id = " ", size = 6))

edges <- data.frame(from = " ", to = names(temp), weight = .1) %>%
    list(., edges) %>%
    Reduce(rbind, .)

# edges <- combinations(length(names(temp)), 2, names(temp)) %>%
#   set_colnames(c("from", "to")) %>%
#   data.frame(., weight = .1) %>%
#   list(., edges) %>%
#   Reduce(rbind, .)

# plot_network2(
#     x = NULL,
#     C = NULL,
#     shape = "dot",
#     dashes = FALSE,
#     color = c("white", "gray60"),
#     nodes = nodes,
#     edges = edges,
#     cex_nodes = edges$weight * 20,
#     title = paste("")
# )

lapply(seq_along(temp), function(i) {
    t(temp[[i]]) %>%
        set_colnames(temp[[i]]) %>%
        as_tibble()
}) %>%
    set_names(rename0(unique(codes$group_name), "_")) %>%
    plot_str()

tree <- FromDataFrameNetwork(edges)
tree <- as.list(tree, mode = "explicit", unname = TRUE)
diagonalNetwork(tree, fontSize = 15, fontFamily = "arial", nodeStroke = "#ccc")

# Create color for node, link and text
n <- length(temp)
p <- length(unlist(temp))
p0 <- sapply(temp, length)
colors <- brewer.pal(n = 9, name = "Set1")[c(seq(5), 8)]
cols <- lapply(seq_along(temp), function(i) rep(colors[i], p0[i])) %>% unlist()
c(rep("white", n), cols) -> linkVector
nodeVector <- c("white", colors, cols) -> textVector

# apply js
network_vector <- lapply(list(nodeVector, linkVector, textVector), function(j) {
    JS(paste0("function(d, i) { return ", paste0('["', paste(j, collapse = '", "'), '"]'), "[i]; }"))
})

diagonalNetwork(tree,
    fontSize = 15, fontFamily = "arial",
    nodeStroke = "white",
    linkColour = network_vector[[2]],
    textColour = network_vector[[3]]
)
```

## Treatments
```{r}
# Before inclusion
temp <- clinic_code[[1]] %>% filter(str_detect(group_code, "^IMA_General_treatResp"))
select(clinic_tot1, temp$column_code) %>% set_colnames(temp$item_name) -> df
df[df == "Unreported (not tested or unknown)"] <- NA

df[!is.na(df[, 6]), 6]

separate_semicolon(df[, 5]) -> x
sapply(
    seq(ncol(x)),
    function(i) rep(colnames(x)[i], colSums(x)[i])
) %>%
    plot_piechart(df, label = FALSE, hsize = 1.5, title = "", dec = 1, cex = 25)

vars <- c("NSAIDs", "Paracetamol", "Prednisolone", "Biologic", "Biologic which", "Biologic precise")
p <- list.map(
    as.list(colnames(df)),
    f(i, j) ~ plot_piechart(
        df %>% pull(i),
        colour = c(get_colors()[-4], get_colors()[5]),
        label = FALSE,
        cex = 25,
        dec = 1,
        threshold = 4,
        title = vars[j],
        hsize = 1.5
    )
)
align_plots(plotlist = p[1:4], align = "vh") %>%
    plot_grid(
        plotlist = .,
        nrow = 2,
        ncol = 2
    )

# Follow-up
plot_piechart(clinic_tot1$C_2742_4229)

# Second visit
plot_piechart(clinic_tot1$C_2733_4213)
temp <- clinic_code[[1]] %>%
    filter(str_detect(group_code, "^IMA_SecondVisit_General_treatResp"))
df <- select(clinic_tot1, temp$column_code) %>% set_colnames(temp$item_name)
df[df == "Unreported (not tested or unknown)"] <- NA
# diagnose_category(df)
p <- list.map(
    as.list(colnames(df)[-6]),
    f(i, j) ~ plot_piechart(
        df %>% pull(i),
        colour = c(get_colors()[-4], get_colors()[5]),
        label = FALSE,
        cex = 25,
        dec = 1,
        threshold = 4,
        title = vars[j],
        hsize = 1.5
    )
)
align_plots(plotlist = p[1:4], align = "vh") %>%
    plot_grid(
        plotlist = .,
        nrow = 2,
        ncol = 2
    )
```

# Session information
```{r end, echo = FALSE}
sessionInfo()
```
