---
title: "descriptive_stats"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{descriptive_stats}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages(library(MultiOmics4ImmunAID))
load_libraries(
    c(
        "corrplot",
        "cowplot",
        # "datawizard",
        "DataExplorer",
        "dlookr",
        "ggpubr",
        "ggstatsplot",
        "janitor",
        "lubridate",
        "magrittr",
        "naniar",
        "RColorBrewer",
        "rstatix",
        "readxl",
        "reshape2",
        "see",
        "skimr",
        "tidyverse",
        "usethis",
        "VIM"
    )
)
path <- file.path(golem::get_golem_wd(), "inst", "extdata")
```

# Proteomics

## ELISA

```{r elisa}
# prot_path <- file.path(path, "ELISA/Batch1")
batch <- 1
date <- "20211116"
prefix <- paste(date, "Data", "", sep = "_")
blocks <- c("Calprotectin", "S100A12")
files_raw <- list()

# Read files
for (i in seq_along(blocks)) {
    files_raw[[i]] <- read_excel(
        file.path(
            path,
            "ELISA/Batch1",
            paste0(prefix, blocks[i], "_batch_", batch, ".xlsx")
        ),
        skip = 5
    )
}
# Clean colnames, remove empty rows, cols and constants
files <- lapply(files_raw, clean_data)
# Common IDs ?
setdiff(files[[1]][, 1], files[[2]][, 1]) # character(0) = Nope !
# Bind tables
elisa <- cbind(files[[1]], files[[2]][, 4, drop = FALSE]) %>% tibble()
colnames(elisa)[4:5] <- blocks

# Set constants into the attributes
for (i in 4:5) {
    var <- colnames(files_raw[[1]])[i]
    attributes(elisa)[var] <- unique(files_raw[[1]][, var])
}

# Convert into types
str(elisa)
elisa$patient_id <- as.character(elisa$patient_id)
elisa$visit <- factor(elisa$visit)

# View factor
diagnose_category(
    elisa[, -c(1:2)],
    top = 500
)
# %>% filter(is.na(levels))
# %>% filter(ratio <= 0.01)

# elisa %>% count(visit)  %>% mutate(freq = n / sum(n))
# elisa %>% count(patient_id, sort = TRUE)  %>% mutate(freq = n / sum(n))

diagnose_numeric(elisa) # %>% filter(minus > 0 | zero > 0)
# View duplicates
elisa %>% get_dupes("patient_id")

# Descriptive stats general
plot_str(elisa)
introduce(elisa)
plot_intro(elisa)
diagnose(elisa) %>%
    filter(missing_count > 0) %>%
    arrange(desc(missing_count))

# Descriptive stats per variables
# qplot(Calprotectin, data = elisa)
plot_bar(elisa)
plot_histogram(elisa)
# plot_boxplot(elisa)
skim(elisa)
plot_violin(elisa)

# str_squish

# Correlation
plot_correlation(elisa)
# continuous data
plot_correlation(elisa, type = "c")
get_correlation(elisa)
plot_correlate(elisa)

# Normality
plot_qq(elisa)
# Do not follow the normality with Shapiro-Wilk
plot_normal(elisa)


# Missing data
# set_missing
plot_missing(elisa)
find_na(elisa)
# impute_na(elisa)

# Outliers
# find_outliers(elisa) # wich variables
diagnose_outlier(elisa) %>% filter(outliers_ratio > 0)
plot_outlier(elisa, typographic = FALSE)
elisa_w_out <- elisa
for (i in find_outliers(elisa)) {
    var <- colnames(elisa)[i]
    elisa_w_out[var] <- imputate_outlier(elisa, all_of(var), method = "mean")
}

# PCA
pca_df <- na.omit(elisa[, 4:5])
plot_prcomp(pca_df, nrow = 2, ncol = 2)

# eda_report(elisa)

elisa <- finalise_data(elisa)
use_data(elisa, overwrite = TRUE)
```

## MS
```{r ms}
ms <- lapply(
    seq(5),
    function(i) {
        b <- ifelse(i < 3, 1, 2)
        read_csv(
            file.path(
                path,
                "MS",
                paste0("Batch", b),
                "data",
                paste0("log2_lfq_proteinGroups_S", i, ".csv")
            )
        )
    }
)

sapply(ms, dim)

ms_codes <- lapply(
    seq(2),
    function(i) {
        read_excel(
            file.path(
                path,
                "MS",
                paste0("Batch", i),
                "Annotations",
                "Samples_annotations.xlsx"
            )
        ) %>%
            clean_names()
    }
)

ms_codes_tot <- Reduce(rbind, ms_codes)
ms_codes_tot <- update_columns(ms_codes_tot, c(3:4, 6), as.factor) %>%
    update_columns(5, dmy)
summary(ms_codes_tot)

# Check for patient intersection : None
# get_intersection(lapply(ms, colnames))

# Get the intersection of the prot id
plot_venn(
    lapply(ms, function(i) i$MajorProteinIds),
    snames = paste("", seq(5))
)

# Combine batches
ms_tot <- Reduce(full_join, ms)
metadata <- get_intersection(lapply(ms, colnames))[[1]]
# Reorder the columns
ms_tot <- select(ms_tot, all_of(metadata), everything())

# Get a list of all the prot names
list_prot_names <- str_split(ms_tot$ProteinName, ";") %>%
    reformat()
list_gene_names <- str_split(ms_tot$GeneName, ";") %>%
    reformat()

# Join by samples
ms_codes_tot$sample_barcode <- str_replace(ms_codes_tot$sample_barcode, "_", "-")
# identical(colnames(ms_tot)[-seq(4)], ms_codes_tot$sample_barcode)

ms <- t(ms_tot) %>%
    t2tibble() %>%
    slice(-seq(4)) %>%
    clean_data(FALSE) %>%
    update_columns(seq(ncol(.)), as.numeric)
rownames(ms) <- ms_codes_tot$sample_barcode
colnames(ms) <- ms_tot$MajorProteinIds

ms_prot_code <- select(ms_tot, 2:4) %>%
    update_columns(3, as.factor)
rownames(ms_prot_code) <- ms_tot$MajorProteinIds

ms_sample_code <- ms_codes_tot[, -1]
rownames(ms_sample_code) <- ms_codes_tot$sample_barcode

use_data(ms, overwrite = TRUE)
use_data(ms_prot_code, overwrite = TRUE)
use_data(ms_sample_code, overwrite = TRUE)

get_correlation(ms, 0.9999)
# diagnose_outlier(ms) %>% filter(outliers_ratio > 0) %>% arrange(desc(outliers_ratio)) %>% select(-c(2, 4))
ms2 <- ms
colnames(ms2) <- seq(ncol(ms2))
# vis_miss(ms2)

qc <- rownames(ms)[str_detect(rownames(ms), "QC")]
length(qc)
```

# Transcriptomics
```{r, eval = FALSE}
rna <- read_tsv(file.path(path, "processed_gene_matrix.tsv"))
rna_t <- t(rna)[-1, ] %>%
    t2tibble() %>%
    clean_data(clean_name = FALSE) %>%
    update_columns(seq(ncol(.)), as.numeric)
colnames(rna_t) <- rna$GeneName
rownames(rna_t) <- colnames(rna)[-1]
rna <- rna_t

# Number of visit A or B
sapply(
    c("A", "B"),
    function(x) length_detect_row(rna, x)
)
use_data(rna, overwrite = TRUE)
```

# Clinic
```{r clinic}
# Extract items
date <- "20220512"
clin_path <- file.path(path, "clinical", "20220501")
files_raw <- list.files(clin_path)
files_export <- files_raw[grepl("export", files_raw)]
files <- str_split(files_export, "_")
(blocks <- unique(sapply(files, function(i) i[2])))
```

## Clinical
```{r clinical}
clinic <- read_batches()
sapply(clinic, dim)
clinic_tot <- Reduce(rbind, clinic)
clinic_tot <- clean_data(clinic_tot, FALSE)
clinic_code <- read_batches(, "codes")

# Descriptive plots
diagnose_category(clinic_tot[, "C_2649_3888"], top = 100) %>%
    select(-c(N, rank, variables)) %>%
    dplyr::rename(N = freq)
ggpiestats(clinic_tot, "C_2649_3888", ggtheme = theme_classic(base_size = 22), theme_config = theme_perso())
plot_bar(clinic_tot[, "C_2643_3798"], ggtheme = theme_classic(), theme_config = theme_perso())

# Common subject ID between batches
vars <- lapply(clinic, function(i) as.numeric(as.data.frame(i[, 2])[, 1]))
# vars <- lapply(clinic_code, function(i) as.data.frame(i[, 1])[, 1])
names(vars) <- seq(3)
plot_venn(vars)
(inter <- get_intersection(vars))
# Duplicates are identical ? TRUE
identical(as.data.frame(t(clinic[[1]][23, ])), as.data.frame(t(clinic[[2]][37, ])))
# QC from MS is in clinical ? Nope.
which(str_detect(rownames(clinic), "7174"))

# Create batch variable
n <- sapply(vars, length)
batches <- mapply(function(x, y) rep(x, y), seq(3), n)
t_batch <- cbind(unlist(vars), unlist(batches))
t_batch <- t_batch[-which(duplicated(t_batch[, 1])), ]

# Common subject ID with ELISA
vars_clin <- sort(as.numeric(unlist(vars)))
vars_ms <- list(MS = get_patient_id(ms))
vars_prot <- c(list(ELISA = get_patient_id(elisa)), vars_ms)
vars_rna <- list(RNA = get_patient_id(rna))
vars_clin_rna <- c(list(Clinic = vars_clin), vars_rna)
vars_tot <- c(vars_clin_rna, vars_prot)
vars_tot2 <- c(vars, vars_rna, vars_prot)
plot_venn(vars_prot)
plot_venn(vars_clin_rna)
plot_venn(c(vars_prot, vars_rna))
plot_venn(vars_tot) # N = 30
plot_venn(c(vars_ms, vars_clin_rna)) # N = 78 !
# all included in clinic data
plot_venn(vars_tot2)
plot_venn(c(vars, vars_rna, vars_ms))
# all from clinic batch 1
get_intersection(vars_tot)

# Missing data
# Convert some modalities into NA
var_na <- c("Unknown", "Not applicable", "Unreported (not tested or unknown)", "Not performed")
for (i in var_na) {
    clinic_tot[clinic_tot == i] <- NA
}
# find_na(clinic_tot)
# set_missing
clinic_tot_proc <- best_na_percent(clinic_tot, 50)
# clinic_tot_proc <- clinic

plot_missing(
    clinic_tot_proc,
    geom_label_args = list(
        label.size = NA,
        label.padding = unit(0, "lines"),
        size = 3
    ),
    group = list("25%" = 0.25, "50%" = 0.50, "75%" = 0.75, "100%" = 1)
)

(gg_miss_var(clinic_tot, show_pct = TRUE) + theme_classic() + theme_perso()) # %>% ggplotly()
vis_miss(clinic_tot_proc)

clinic_code_proc <- clean_data(clinic_code[[1]])
# vis_miss(clinic_code_proc)
# vis_miss(best_na_percent(clinic_tot_proc, 0))
# Imputation
# res <- summary(aggr(clinic_tot, sortVar = TRUE))$combinations

# Numeric
var_num <- get_name_num(clinic_tot_proc)
clinic_tot_proc <- update_columns(clinic_tot_proc, all_of(var_num), as.numeric)

diagnose_numeric(clinic_tot_proc)

# plot_violin(clinic_tot_proc, colors = rep("blue", 250))
# plot_violin2(clinic_tot_proc, colors = rep("black", 250))
# plot_violin3(clinic_tot_proc, colors = rep("black", 250))

# Date
var_dates <- c("C_2643_3800", "C_2643_3801", "C_2643_3802", "C_2648_3886", "C_2648_3887", "C_2728_4054_1", "C_2729_4054_1", "C_2745_4178_1", "C_2745_4178_2")

clinic_tot_proc <- update_columns(clinic_tot_proc, var_dates, complete_date)
clinic_tot_proc <- update_columns(clinic_tot_proc, var_dates, dmy)
for (i in var_dates) {
    qplot(as.data.frame(clinic_tot_proc[, i])[, 1])
}

clin_proc_year <- update_columns(clinic_tot_proc, var_dates, function(i) year(round_date(i, "year")))
plot_histogram(clin_proc_year)

for (i in var_dates) {
    y <- as.data.frame(as.character(as.data.frame(clin_proc_year[, i])[, 1]))
    diagnose_category(y, top = 100) %>% arrange(freq)
}

# Age in decades
decade <- as.data.frame(as.character(as.data.frame(clin_proc_year[, "C_2643_3800"] - clin_proc_year[, "C_2643_3800"] %% 10)[, 1]))
diagnose_category(decade, top = 100) %>%
    arrange(levels) %>%
    select(-variables)
qplot(decade[, 1])
qplot(as.character(2020 - as.numeric(decade[, 1])))

# Categorical variables
clin_categorial <- select(clinic_tot_proc, -all_of(c(var_dates)))
# clin_categorial <- select(clinic_tot, all_of(c(var_categorial)))
clin_categorial <- update_columns(clin_categorial, "C_2643_3798", as.character)
l_level_cols <- parse_levels(clin_categorial, clinic_code, FALSE)
cols_sim <- col_sim(clin_categorial, clinic_code, FALSE)
# sapply(apply(l_level_cols[-unique(unlist(i_rows)), ], 1, function(x) which(!is.na(x))), length) %>% sort()

regexes <- c("france", "AP-HP", "Mother", "control", "aspirin", "negative\t", "asian", "non african", "partial\t", "response", "flare", "male", "mild", "localized", "months")
i_rows <- lapply(regexes, function(i) detect_difficulty(l_level_cols, i))
j_rows <- seq(nrow(l_level_cols))[-unlist(i_rows)]
tot_rows <- c(i_rows, as.list(j_rows))
l_levels <- lapply(tot_rows, function(i) reformat(l_level_cols[i, ]))
lapply(tot_rows, function(i) unlist(get_level_name(cols_sim, clinic_code[[3]])[i]))
# get_table_occ(clin_categorial, clinic_code, seq(nrow(l_level_cols))[-j_rows], FALSE)

var_categorial <- unlist(cols_sim)
clinic_tot_proc <- update_columns(clinic_tot_proc, var_categorial, as.factor)

to_replace <- list(
    `0` = c("Non African", "No", "None", "Primary failure", "Out of flare", "Male", "Single", "Chronic : > 6 weeks", "Unique", "First episode", "Non symmetrical", "Random", "Negative"),
    `1` = c("African", "Yes", "Partial", "Mild", "Diffuse", "Partial response", "On flare", "Female", "Multiple", "Acute : < 6 weeks", "Recurrent (with remission period)", "Symmetrical", "Patterned", "Positive"),
    `2` = c("Total", "Moderate to severe", "Loss of efficacy", "Localized", "Continuous (without remission)"),
    `3` = c("Complete response")
)

# for (i in seq_along(to_replace)) {
#     for (j in seq_along(to_replace[[i]])) {
#         clinic_tot[clinic_tot == to_replace[[i]][j]] <- paste(i - 1)
#     }
# }
# [[15]]

# group_name
# The top bottom by frequency
diagnose_category(
    clinic_code_proc[, "group_name", drop = FALSE],
    top = 100
) %>% arrange(freq)
# Select the clinic data with 0 NA
var_na <- colnames(clinic_tot_proc)
# Look at the metadata in codes
(stats <- clinic_code_proc %>%
    filter(clinic_code_proc$column_code %in% var_na) %>%
    select(!(starts_with("repeat"))))

get_var_names(var_na, stats)

diagnose_category(as.data.frame(stats$group_name))
# Which is the frequence of this category
clinic_code_proc[, "group_name", drop = FALSE] %>%
    diagnose_category(top = 100) %>%
    filter(str_detect(levels, paste0(unique(stats$group_name), collapse = "|")))
# What are the most frequent modalities for each variable
plot_bar(clinic_tot_proc)
# Create country variable
clinic_tot_proc %>%
    update_columns("C_2643_3797", as.character) %>%
    mutate(
        country = case_when(
            str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg") ~ "France",
            str_detect(C_2643_3797, "Madrid|Barcelona") ~ "Spain",
            str_detect(C_2643_3797, "Leuven") ~ "Belgium",
            str_detect(C_2643_3797, "Rotterdam") ~ "Netherlands",
            str_detect(C_2643_3797, "Athens") ~ "Greece",
            str_detect(C_2643_3797, "Roma") ~ "Italy",
            str_detect(C_2643_3797, "Geneva") ~ "Switzerland",
            str_detect(C_2643_3797, "Ankara") ~ "Turkey",
            str_detect(C_2643_3797, "Münster|Berlin") ~ "Germany",
            str_detect(C_2643_3797, "Leeds") ~ "United Kingdom (UK)",
            str_detect(C_2643_3797, "Lubljana") ~ "Slovenia",
            TRUE ~ C_2643_3797
        )
    ) %>%
    select(country) %>%
    plot_bar(ggtheme = theme_classic(), theme_config = theme_perso())

# By French centers
clinic_tot_proc %>%
    filter(str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg")) %>%
    select(C_2643_3797) %>%
    plot_bar()

# clinic_tot_proc %>%
#     filter(str_detect(C_2643_3797, "Paris|Bordeaux|Nantes|Lyon|Lille|Strasbourg")) %>% select(C_2643_3797) %>% group_by(C_2643_3797) %>% summarise(n = n()) %>% arrange(desc(n))

# By French cities
clinic_tot_proc %>%
    mutate(
        town = case_when(
            str_detect(C_2643_3797, "Paris") ~ "Paris",
            str_detect(C_2643_3797, "Bordeaux") ~ "Bordeaux",
            str_detect(C_2643_3797, "Nantes") ~ "Nantes",
            str_detect(C_2643_3797, "Lyon") ~ "Lyon",
            str_detect(C_2643_3797, "Lille") ~ "Lille",
            str_detect(C_2643_3797, "Strasbourg") ~ "Strasbourg",
            TRUE ~ "Others"
        )
    ) %>%
    select(town) %>%
    plot_bar()

# %>% diagnose_category()

# Correlation
# (p <- select(clinic_tot_proc, all_of(var_num)) %>% plot_corr0(p_adjust = "BH"))
# save_tiff(p)

plot_corr(clinic_tot_proc, stats)
ggcorrmat(clinic_tot_proc)

# Format conversion
var_dates <- colnames(clinic_tot)[which(find_dates(clinic_tot))]
clinic_tot <- update_columns(clinic_tot, var_dates, complete_date)
clinic_tot <- update_columns(clinic_tot, var_dates, dmy)
var_num <- get_name_num(clinic_tot)
clinic_tot <- update_columns(clinic_tot, all_of(var_num), as.numeric)
var_categorial <- colnames(clinic_tot)[which(!(colnames(clinic_tot) %in% c(var_dates, var_num)))]
clinic_tot <- update_columns(clinic_tot, var_categorial, as.factor)

# Stats / outliers
var_num <- get_name_num(clinic_tot_proc)
# slice(clinic, which(clinic$bmi_automatic > 100)) %>%
#   select ("weight_kg", "height_cm", "bmi_automatic", "age_at_inclusion_tim")

col_outliers <- explore_outliers(clinic_tot_proc)
var_socio <- c("C_2643_3803", "C_2643_3804", "C_2649_3889", "C_2649_3890")
i <- col_outliers[1] # "C_2643_3804"
j <- col_outliers[2] # "C_2649_3889"
clin_melt <- melt(clinic_tot_proc) %>% select(variable, value)
outliers <- (clin_melt %>% filter(variable == var_socio[4]) %>% boxplot())$out

# Fix height and bmi errors
clinic_tot_proc <- clinic_tot
tab <- clinic_tot_proc %>%
    filter(C_2649_3890 > 100) %>%
    select(all_of(var_socio))
to_fix <- clinic_tot_proc$C_2649_3890 %in% tab$C_2649_3890
clinic_tot_proc$C_2649_3889[to_fix] <- c(173, 151)
clinic_tot_proc$C_2649_3890[to_fix] <- clinic_tot_proc$C_2643_3804[to_fix] / ((clinic_tot_proc$C_2649_3889[to_fix] / 100)^2)

get_outliers(clinic_tot_proc, i)
# get_outliers(clinic_tot_proc, j, probs = c(.025, .975), method = "percentiles")
# get_outliers(clinic_tot_proc, j, , method = "hampel", c = 3)


clinic_tot_proc <- finalise_data(clinic_tot_proc, clean_name = FALSE, row_name = 2)
codes_proc <- colnames(clinic_tot_proc)

colnames(clinic_tot_proc) <- get_var_names(codes_proc, clinic_code[[1]]) %>%
    str_sub(1, 20)
clinic <- clean_names(clinic_tot_proc)
attributes(clinic)$codes <- tibble(codes = codes_proc, name = colnames(clinic))
# use_data(clinic, overwrite = TRUE)
```

## Clinic transformation
```{r transf}
# Transformations
clinic_num <- select(clinic, sort(get_name_num(clinic)))

var_ord <- ordinal_variables(clinic_num)
var_not_ord <- colnames(select(clinic_num, -all_of(var_ord)))
plot_histo(log1p(select(clinic_num, all_of(var_not_ord))), colors = rep("blue", 250))

var_max <- c("creatinine_mmol_l", "alat_uln_upper_limi", "leucocytes_mm3", "neutrophils_mm3", "ggt_ui_l", "cardiac_manifestatio", "vascular_involvement", "other_neurological_m")
(out <- sapply(var_max, function(i) which.max(as.data.frame(clinic_num[, i])[[1]])))

p <- ggdraw()
for (i in seq(var_max)) {
    p <- p + plot_violin2(as.data.frame(clinic[-out[i], var_max[i]]))
}
p

get_not_normal0(log1p(select(clinic, all_of(var_not_ord))))

# levels from ordinal data
sapply(var_ord, function(i) unique(sort(as.data.frame(clinic_num[, i])[, 1])))
diagnose_category(as.data.frame(sapply(var_ord, function(i) as.factor(as.data.frame(clinic_num[, i])[, 1]))))

# Outliers removing
# plot_violin(select(clinic, alat_uln_upper_limi) %>% filter(alat_uln_upper_limi < 140))
clinic$alat_uln_upper_limi[which(clinic$alat_uln_upper_limi == 269)] <- NA

# Transformations
clinic_transf <- clinic

# X2
# clinic_transf <- update_columns(clinic, "height_cm", function(i) i^2)
# Log transformation
var_log <- c(
    # "abdominal_pain",
    "alat_ui_l",
    "alk_phosphatases_ui",
    "asat_ui_l",
    # "arthralgia_myalgia",
    "bmi_automatic",
    # "bone_pain",
    # "cardiac_manifestatio",
    # "charlson_score_auto",
    # "chest_pain",
    "creatinine_mmol_l",
    "crp_c_reactive_prot",
    # "diarrhea",
    "eosinophils_mm3",
    # "eye_manifestations",
    "fever_38_c_104_f",
    "ggt_ui_l",
    "ggt_uln_ui_l", # bof
    # "headaches",
    # "nausea_vomiting",
    "number_of_consecutiv",
    # "other_neurological_m",
    # "overall_symptoms",
    # "painful_nodes",
    # "skin_rash_other_sa",
    # "sore_throat_other",
    # "swelling_of_the_join",
    "total_bilirubin_mmo"
    # "vascular_involvement",
    # "weight_loss_uninten"
)
# clinic_transf <- update_columns(clinic_transf, var_log, log1p) # %>%
# arrange(immun_aid_identifier)
colnames(clinic_transf) <- codes_proc

# Rename
code_extracted <- extract_codes(codes_proc, clinic_code[[3]])
temp <- str_replace(code_extracted$item_name, " \\(.+\\)|^\\d{1,2}\\. ", "")
names(temp) <- codes_proc
temp <- sort(temp)
codes_temp <- names(temp)
temp <- janitor::make_clean_names(temp)
names(temp) <- codes_temp
temp <- temp[codes_proc]

vars <- c("_patient_included", "_of_disease_activity", "cytological_signs_of_", "_on_secondary_genetic_findings", "_treatment_in_the_last_2_weeks", "_other_said_dermatological_manifestations", "_other_ear_nose_throat_symptoms", "gfr_")
temp <- str_replace(temp, paste(vars, collapse = "|"), "")

keys <- c("date_2", "date", "by", "max")
values <- c("\\1_immunology", "\\1_biology", "consent_signed_by", "max_fever")
for (i in seq_along(keys)) {
    temp <- str_replace(temp, paste0("^(", keys[i], ")$"), values[i])
}

keys <- c("chf", "cva", "copd", "crp", "hb", "uln")
values <- c("Congestive Heart Failure", "Cerebrovascular Accident or Transient Ischemic Attack", "Chronic Obstructive Pulmonary Disease", "C-reactive protein", "Hemoglobine", "Upper Limit of Normal")
for (i in seq_along(keys)) {
    temp <- str_replace(temp, keys[i], janitor::make_clean_names(values[i]))
}

for (i in c(temp[sapply(temp, function(i) str_length(i) < 5)])) {
    if (!i %in% c("type", "urea")) {
        temp <- str_replace(temp, i, toupper(i))
    }
}

temp <- str_replace(temp, "^(neutrophils)_2$", "\\1_percent")
temp <- str_replace(temp, "value_due_to_the_disease", "")

names(temp) <- codes_temp

# code_extracted %>% filter(str_detect(item_name, regex(paste0("^", temp[sapply(temp, function(i) str_length(i) < 5)][-6], collapse = "|"), ignore_case = TRUE))) %>% select(c(group_name, item_name))

# Codes
code_info <- clinic_code[[3]] %>%
    filter(str_detect(column_code, paste0("^", codes_temp, "$", collapse = "|"))) %>%
    select(column_code, group_name)
code_info$group_name <- str_replace(code_info$group_name, " \\(.+\\)", "") %>%
    snakecase::to_any_case(unique_sep = NULL, parsing_option = 3) %>%
    as.factor()
colnames(clinic_transf) <- temp
temp2 <- cbind(code_info, item_name = as.character(temp))

# Dates
# date_vars <- clinic_transf %>% select(which(sapply(colnames(.), function(i) is.Date(as.data.frame(.[, i])[, 1]))))
# cou2 <- (temp2 %>% filter(str_detect(item_name, paste0("^", colnames(date_vars), "$", collapse = "|"))) %>% select(column_code))$column_code
# clinic_code[[3]] %>% filter(str_detect(column_code, paste0("^", cou2, "$", collapse = "|")))

date_biol <- (clinic_code[[3]] %>% filter(str_detect(group_name, "General biology")) %>% filter(str_detect(item_name, "Date")))$column_code
biol <- (temp2 %>% filter(str_detect(group_name, "biology")) %>% filter(!str_detect(item_name, "date")))$item_name
clinic_tot2 <- update_columns(clinic_tot, date_biol, dmy)
date_diff <- sapply(seq(4), function(i) clinic$date_of_inclusion - as.data.frame(clinic_tot2 %>% select(all_of(date_biol)))[, i])
# which(abs(date_diff) > 7)
# Closest date is not the first date only for  around 10 elements. And most of the data at these date are NA. So keep the first date that do not influence too much and to know for sure at which date the data are from.
date_corr <- sapply(seq(4), function(i) ifelse(abs(date_diff[, i]) > 7, NA, date_diff[, i]))
colnames(date_corr) <- paste("inclusion - general biology", seq(4))
which_min <- sapply(seq(nrow(date_corr)), function(i) which.min(abs(date_corr[i, ])))
which_min <- sapply(which_min, function(i) ifelse(length(i) == 0, 1, i))
# which(which_min > 1)
# which_min[which_min > 1]
# image(seq(213), 1, as.matrix(which_min), yaxt = "n", labels = FALSE); axis(1, las = 2, at = seq(213), labels = FALSE); axis(1, las = 2, at = seq(0, 213, 5), lwd.ticks = 3)
# as_tibble(date_diff) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))
# (clinic_tot %>% select(all_of(bloup2)) %>% slice(setdiff(which(which_min > 1), which(abs(date_diff) > 7))))[, (1+(8*k)):(8+(8*k))]

filter_week <- abs(date_diff) > 7
filter_week1 <- which(filter_week[, 1])

# for (i in biol) {
#     clinic_transf[filter_week1, i] <- NA
# }

#  clinic_transf %>% select(all_of(biol)) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))
# clinic_transf %>% select(date_biology) %>% slice(intersect(which(abs(date_diff) > 7), which(which_min > 1)))

t_batch <- arrange(as.data.frame(t_batch), V1)[, 2]

# Save
clinic_transf <- arrange(clinic_transf, immun_aid_identifier) %>%
    mutate(batch = t_batch)
clinic_transf <- finalise_data(clinic_transf, row_name = "immun_aid_identifier", clean_name = FALSE)
attributes(clinic_transf)$codes <- temp2
use_data(clinic_transf, overwrite = TRUE)
```

## Descriptive stats by disease
```{r}
clinic <- clinic_transf
# Filter by disease
diseases <- levels(clinic$disease)
d1 <- diseases[1]
d0 <- diseases[14]
clinic_dis <- clinic %>%
    filter(
        str_detect(
            disease,
            replace_parenthesis(paste(c(d0, d1), collapse = "|"))
        )
    )
levels(clinic_dis$disease)[d1 == levels(clinic$disease)] <- "1"
levels(clinic_dis$disease)[d0 == levels(clinic$disease)] <- "0"
clinic_dis$disease <- clinic_dis$disease %>%
    factor(., levels = unique(.))

# All cofonding variables in numeric
levels(clinic_dis$gender) <- c(0, 1)
clinic_dis$gender <- as.numeric(as.character(clinic_dis$gender))

# Batch * centers effects
clinic_dis %>%
  group_by(clinical_center) %>%
  mutate(count_name_occurr = n()) %>%
  ggplot(aes(
    x = reorder(clinical_center, -count_name_occurr),
    fill = as.character(batch)
  )) +
  geom_bar(position = "stack") +
  labs(fill = "Batch") +
  stat_count(
    geom = "text",
    colour = "white",
    size = 3.5,
    aes(label = ..count..),
    position = position_stack(vjust = 0.5)
  )

# Filter by numeric variables
clinic_num <- get_name_num(clinic_dis) %>%
    select(clinic_dis, .)

# Remove columns with high levels of NA
# plot_missing(
#     clinic_num,
#     geom_label_args = list(
#         label.size = NA,
#         label.padding = unit(0, "lines"),
#         size = 3
#     ),
#     group = list("25%" = 0.25, "50%" = 0.50, "75%" = 0.75, "100%" = 1)
# )
#
# gg_miss_var(clinic_num, show_pct = TRUE) + theme_classic() + theme_perso()
# vis_miss(clinic_num)

clinic_proc <- best_na_percent(clinic_num, 38)

# Remove constant variables
clinic_proc <- clean_data(clinic_proc, clean_name = FALSE)
rownames(clinic_proc) <- clinic_proc$immun_aid_identifier
colnames(clinic_proc) %>% sort()

# Remove individuals with high levels of NA
# x <- clinic_proc
# res <- sapply(rownames(x), function(i) round((length(which(is.na(x[i, ]))) / ncol(x)) * 100, 1))
# clinic_proc <- clinic_proc[-which(res > 70), ]

# plot_histo(as.data.frame(clinic_proc %>% select(-disease)), colors = rep("blue", 200))

ordinal_vars <- names(ordinal_variables(clinic_proc, 3))
# setdiff(names(ordinal_variables(clinic_proc, 3)), names(ordinal_variables(clinic_proc, 2)))

# Proportion of ordinal data modalities
clinic_ord <- update_columns(clinic_proc[, ordinal_vars], ordinal_vars, as.numeric)
perc <- pivot_longer(clinic_ord, all_of(ordinal_vars)) %>%
    group_by(name, value) %>%
    summarise(`%` = n()) %>%
    pivot_wider(names_from = name, values_from = c(`%`))

# clinic_dis[, "disease"] %>% group_by(disease) %>% summarise(`%` = n())

# Remove all ordinal data with low occurrences
perc0 <- perc %>% filter(!is.na(value))
n <- 4
var_occ <- names(which(apply(perc0[, -1], 2, function(x) any(x <= n))))
perc0 %>% select(-var_occ)

# clinic_num0 <- clinic_proc %>%
#   select(
#     -all_of(
#       c(names(ordinal_variables(clinic_proc, 3)), "immun_aid_identifier")
#       )
#   )

# plot_histo(clinic_num0, colors = rep("blue", 200))

# Remove all ordinal data with low occurrences
clinic_proc0 <- clinic_proc[, sort(colnames(clinic_proc))] %>%
    select(-all_of(c(var_occ, "immun_aid_identifier", "gender")))
# clinic_proc0$disease <- factor(clinic_proc0$disease, labels = rev(c(diseases[9], diseases[1])))

# Descriptive statistics
stats <- clinic_proc0 %>%
    pivot_longer(!disease) %>%
    group_by(name, disease) %>%
    summarise(
        mean = mean(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
        n = length(which(!is.na(value)))
    ) %>%
    pivot_wider(names_from = disease, values_from = c(mean, sd, n)) %>%
    mutate(ratio = (n_0 / n_1))

sds <- apply((clinic_proc0 %>% select(-disease)), 2, function(x) sd(x, na.rm = TRUE))
stats$samplesize <- calculate_samplesize(stats$mean_0, stats$mean_1, sds, stats$ratio)
stats$effectsize <- abs(calculate_effectsize(stats$mean_0, stats$mean_1, sds))

# Remove the variables with only NA in control
stats0 <- stats %>% filter(!is.na(mean_0))
# stats0 %>% arrange(samplesize)

not_in_control <- (stats %>% filter(is.na(mean_0)))$name

# Mean difference tests
tests <- clinic_proc0 %>%
    select(-all_of(not_in_control)) %>%
    pivot_longer(!disease) %>%
    group_by(name) %>%
    wilcox_test(value ~ disease) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance()

# Total statistics
left_join(stats0, tests[, c(1, 8:10)]) %>% arrange(samplesize)

vars <- c("age_at_inclusion_time", "batch", "BMI", "gender")
vars2 <- c("immun_aid_identifier", "weight", "disease", "height")

row_names <- rownames(clinic_proc)
clinic_proc <- clinic_proc %>% select(-c(vars2, ends_with("_upper_limit_of_normal")))

# Transformation
norm_vars <- list()
norm_vars[[1]] <- normality(clinic_proc) %>% filter(p_value > 0.05) %>% select(vars)
skew <- ((clinic_proc) %>% select(-c(unlist(norm_vars))) %>% sapply(function(i) skewness(i)))
temp <- data.frame(var = skew) %>% filter(var < 0) %>% row.names() %>% select(clinic_proc, .)
norm_vars[[2]] <- temp ^ 2 %>% normality() %>% filter(p_value > 0.05) %>% select(vars)
norm_vars[[3]] <- temp ^ 3 %>% normality() %>% filter(p_value > 0.05) %>% select(vars)
norm_vars[[4]] <- (log(clinic_proc + 1)) %>% select(-c(unlist(norm_vars))) %>% normality() %>% filter(p_value > 0.05) %>% select(vars)
norm_vars[[5]] <- (1/(clinic_proc + 1)) %>% select(-c(unlist(norm_vars))) %>% normality() %>% filter(p_value > 0.05) %>% select(vars)
norm_vars[[6]] <- ((clinic_proc) ^ (1/2)) %>% select(-c(unlist(norm_vars))) %>% normality() %>% filter(p_value > 0.01) %>% select(vars)

transf <- c(function(i) i ^ 2, function(i) i ^ 3, function(i) log(i  + 1), function(i) 1 / (i + 1), function(i) i ^ (1 / 2))
for (i in seq(transf)) {
  clinic_proc <- update_columns(clinic_proc, all_of(unlist(norm_vars[[i + 1]])), transf[[i]])
}
# # clinic_proc <- update_columns(clinic_proc, colnames(clinic_proc), log1p)
cl <- clinic_proc
cl$gender <- as.factor(cl$gender)
cl$batch <- as.factor(cl$batch)
blocks_cl <- clinic_proc %>% as.data.frame()
blocks_clinic_still <- remove_cofunding(list(CLINIC = blocks_cl), vars)

blocks_clinic_still[[1]] <- select(blocks_clinic_still[[1]], -all_of(vars)) #  <-  list(CLINIC = select(blocks_cl, -all_of(vars))) #
rownames(blocks_clinic_still[[1]]) <- row_names
clinic_still_processed <- blocks_clinic_still
use_data(clinic_still_processed, overwrite = TRUE)
```

## Descriptive stats for each disease
```{r}
vars <- c("ferritin_mg_l", "crp_c_reactive_prot", "leucocytes_mm3", "fever_38_c_104_f", "physician_global_ass")
i <- vars[2]
res <- clinic %>%
    select(all_of(c("disease", vars))) %>%
    filter(!str_detect(disease, "Negative control")) %>%
    pivot_longer(!disease) %>%
    group_by(name, disease) %>%
    summarise(
        mean = mean(value, na.rm = TRUE),
        median = median(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
        quantiles = paste(quantile(value, c(0.25, 0.75), na.rm = TRUE), collapse = "-"),
        range = paste(range(value, na.rm = TRUE), collapse = "-"),
        n = length(which(!is.na(value))),
        na = length(which(is.na(value)))
    )

res %>% filter(name == i)


tiff(
    paste0(i, ".tiff"),
    units = "px",
    width = 3000,
    height = 2000,
    res = 300
)
(ggbetweenstats(
    (clinic %>% select(all_of(c("disease", i)))),
    x = disease,
    y = crp_c_reactive_prot,
    p.adjust.method = "BH",
    type = "nonparametric",
    centrality.point.args = list(size = 0),
    centrality.label.args = list(
        size = 3,
        fill = NA,
        label.size = NA,
        segment.linetype = 0
    ),
    pairwise.comparisons = FALSE
)) %>%
    theme_perso0(colors = c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 9, name = "Set2"))) +
    guides(fill = "none", color = "none") +
    theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust = 1))
dev.off()
```

## Clinical0

```{r}
clinic0 <- read_tsv(file.path(path, "CleanBiologicalValues.tsv"))
clinic0 <- arrange(clinic0, ID) %>%
    clean_names()
colnames(clinic0) <- str_sub(colnames(clinic0), 1, 20)
clinic <- arrange(clinic, immun_aid_identifier)
# identical(clinic0$id, clinic$immun_aid_identifier)
to_exclude <- c(
    "description",
    "precise",
    "coombs_test_positive",
    "conj_bili_mmol_l",
    "in",
    "antibody_structure",
    "isotype",
    "light_chain",
    "serum_peak_g_l",
    "ldh_u_l",
    "triglycerides_mmol_l",
    "crp_2nd_visit",
    "saa_2nd_visit"
)
#  "neutrophils_mm3"    "schizocytes_percen" "erythrocyte_sedime"
to_select <- c(
    "immun_aid_identifier",
    "disease",
    "age_at_inclusion_tim",
    "gender",
    "type",
    "hb_g_d_l",
    "mean_red_cell_volume",
    "leucocytes_mm3",
    "lymphocytes_mm3",
    "neutrophils_percent",
    "eosinophils_mm3",
    "platelets_mm3",
    "cytological_signs_of",
    "evidence_of_active",
    "crp_c_reactive_prot",
    "max_crp_value_due_to",
    # "saa_serum_amyloid_a",
    # "fibrinogen_level_g",
    "total_bilirubin_mmo",
    "sodium_mmol_l",
    "potassium_mmol_l",
    # "protidemia_g_l",
    # "albuminemia_g_l",
    "creatinine_mmol_l",
    "gfr_glomerular_fil",
    "urea_mmol_l",
    "alat_ui_l",
    "alat_uln_upper_limi",
    "asat_ui_l",
    "asat_uln_ui_l",
    "ggt_ui_l",
    "ggt_uln_ui_l",
    # "alk_phosphatases_uln",
    # "ferritin_mg_l",
    # "glycosylated_ferriti",
    # "monoclonal_gammapath",
    "alk_phosphatases_ui"
)
clinic0 <- select(clinic0, -c(batch, days_from_inclusion, date_of_biological_a)) %>% select(-all_of(to_exclude))
# ,saa_serum_amyloid_a
clinic1 <- select(clinic, all_of(c(to_select)))
colnames(clinic0) <- str_sub(colnames(clinic0), 1, 18)
colnames(clinic1)[c(1, 3:4)] <- c("id", "age", "sex")
colnames(clinic1) <- str_sub(colnames(clinic1), 1, 18)
get_intersection0(list(A = colnames(clinic1), B = colnames(clinic0)))
clinic0[clinic0 == "Not performed"] <- NA
# save_tsv(clinic0, filename = "clinic0.temp")
# save_tsv(clinic1, filename = "clinic1.temp")
# i_rows <- which(!mapply(identical, as.numeric(clinic0$urea_mmol_l), as.numeric(clinic1$urea_mmol_l)))
```

## Extraction for Geneve lab
```{r}
clinic <- read_batches()
clinic_tot <- Reduce(rbind, clinic)
codes <- clinic_code[[3]] %>% select(!(starts_with("repeat")))
l_codes <- c()

l_codes <- c(l_codes, (codes %>% filter(str_detect(item_name, "identifier|Disease|Date of inclusion")) %>%
    filter(str_detect(group_name, "Patient information")))$column_code)
# l_codes <- c(l_codes, (codes %>% filter(str_detect(item_name, "Gender")))$column_code)

# Visite 1
## 1.7 Disease activity
vis1 <- codes %>% slice(-detect_difficulty(., "second"))
l_codes <- c(l_codes, (vis1 %>% filter(str_detect(item_name, "fatigue|global")))$column_code)
l_codes <- c(l_codes, (vis1 %>% slice(detect_difficulty(., "aidai")))$column_code)

## 2. Clinical manifestations
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "triggering")))$column_code)
l_codes <- c(l_codes, (vis1 %>% filter(str_detect(group_name, "Fever")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "response to therapie")))$column_code)
l_codes <- c(l_codes, (vis1 %>% slice(detect_difficulty(., "weight loss")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "other signs")))$column_code)

## 4.1 General biology
l_codes <- c(l_codes, (codes %>%
    filter(str_detect(item_name, "Date")) %>%
    filter(str_detect(group_name, "General biology")))$column_code)
l_codes <- c(l_codes, (vis1 %>%
    slice(detect_difficulty(., "CRP|SAA")) %>%
    filter(str_detect(group_name, "General biology")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "\tferritin")))$column_code)
l_codes <- c(l_codes, (codes %>% slice(detect_difficulty(., "Erythrocyte")))$column_code)

## 5. Systemic therapies
sys <- codes %>% filter(str_detect(group_code, "SystemicTherapies"))
vars <- c(
    "Treatment group",
    "Date of beginning",
    "Response",
    "over",
    "Treatment category",
    "Treatment$",
    "Every",
    "[Dd]ose",
    "Period"
)
l_codes <- c(l_codes, (sys %>% filter(str_detect(item_name, paste(vars, collapse = "|"))))$column_code)

sys %>%
    filter(str_detect(item_name, "Treatment$")) %>%
    filter(str_detect(group_name, "Biologic$")) %>%
    count("item_code")
sys %>%
    filter(str_detect(item_name, "Every|Period")) %>%
    count("group_name")
unique((sys %>% slice(detect_difficulty(., "dose")))$item_name)
sys %>%
    slice(detect_difficulty(., "dose")) %>%
    count("group_name")
sys %>%
    slice(detect_difficulty(., "\tadministrated")) %>%
    count("group_name")
sys %>%
    filter(str_detect(group_name, "Corticosteroid")) %>%
    slice(detect_difficulty(., "dose")) %>%
    count("item_name")

# Visite 2 & follow up
vis2 <- codes %>% slice(detect_difficulty(., "second|followup"))
l_codes <- c(l_codes, (vis2 %>%
    slice(detect_difficulty(., "date of the visit|evolution|CRP|SAA")) %>%
    filter(!str_detect(item_name, "Persistant")))$column_code)

# Extraction codes
clinic_extraction <- clinic_tot %>% select(all_of(l_codes))
clinic_geneve <- clean_data(clinic_extraction, FALSE, FALSE)
codes_extraction <- extract_codes(colnames(clinic_geneve), clinic_code[[3]])
code_names0 <- sapply(
    seq(nrow(codes_extraction)),
    function(i) {
        paste0(
            codes_extraction[i, "item_name"],
            {
                res <- codes_extraction[i, "repeat_inds"]
                ifelse(is.na(res), "", paste0(" - ", res))
            }
        )
    }
)

code_names <- sapply(
    seq(nrow(codes_extraction)),
    function(i) {
        paste0(
            codes_extraction[i, "group_name"],
            " - ",
            code_names0[i]
        )
    }
)

i_rows <- which(code_names %>% str_detect("Biologic - Treatment"))
# code_names <- str_replace(code_names, "Biological values", "Second visit general biology")
pat <- str_replace(as.data.frame(codes_extraction[i_rows, "item_code"])[, 1], "IMA_SYSTHERAPY_TREATMENT_BIO(_TREAT_)?", "")
code_names[i_rows] <- str_trim(paste(pat, code_names[i_rows]))
i_rows <- which(code_names %>% str_detect("Biological values"))
code_names[i_rows] <- paste0(rep(c("Second visit", "Follow up"), each = 3), " general biology", str_replace(code_names[i_rows], "Biological values", ""))

t_clinic_geneve <- as_tibble(t(clinic_geneve))
colnames(t_clinic_geneve) <- clinic_geneve$C_2643_3796
t_clinic_geneve <- as_tibble(cbind(codes_extraction, t_clinic_geneve))

colnames(clinic_geneve) <- code_names

# Closest date for general biology
date_vars <- colnames(clinic_geneve)[which(find_dates(clinic_geneve))]
clinic_geneve <- update_columns(clinic_geneve, date_vars, dmy)
date_diff <- sapply(2:5, function(i) as.numeric(as.data.frame(clinic_geneve[, date_vars[1]] - clinic_geneve[, date_vars[i]])[, 1]))
date_corr <- sapply(seq(4), function(i) ifelse(abs(date_diff[, i]) > 7, NA, date_diff[, i]))
colnames(date_corr) <- paste("inclusion - general biology", seq(4))
which_min <- sapply(seq(nrow(date_corr)), function(i) which.min(abs(date_corr[i, ])))
which_min <- sapply(which_min, function(i) ifelse(length(i) == 0, 1, i))

get_min <- function(x) {
    temp <- as.data.frame(clinic_geneve[, colnames(clinic_geneve) %>% str_detect(paste0("General biology - ", x))])
    colnames(temp) <- seq(4)
    temp <- tibble(temp)
    temp[temp == "Not performed"] <- NA
    temp <- update_columns(temp, seq(4), as.numeric)
    unlist(sapply(seq(nrow(temp)), function(i) {
        res <- temp[i, which_min[i]]
        ifelse(is.na(res), ifelse(is.na(temp[i, 1]), temp[i, 2], temp[i, 1]), res)
    }))
    # View(cbind(which_min, temp, temp2))
}

vars <- c("CRP \\(", "Max CRP", "SAA", "Ferritin", "Erythrocyte")
temp <- sapply(vars, get_min)
colnames(temp) <- paste("closest", str_replace(vars, " \\\\\\(", ""))
colnames(clinic_geneve) <- code_names0
# sapply(seq(ncol(temp3)), function(i) length(which(is.na(temp3[, i]))))
clinic_geneve <- cbind(clinic_geneve, date_corr, temp)

# Output
library(openxlsx)
file_path <- file.path(golem::get_golem_wd(), "clinic_extraction.temp.xlsx")
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, "Sheet 1", clinic_geneve)
addWorksheet(wb, "Sheet 2")
writeData(wb, "Sheet 2", t_clinic_geneve)
saveWorkbook(wb, file = file_path, overwrite = TRUE)

# sapply(colnames(clinic_geneve), function(i) strsplit(i, " - ")[[1]][2:])
# common_vars <- setdiff(colnames(clinic_tot_proc), l_codes)
```

## PedsQL
```{r pedsql}
# Extract items
block <- "PedsQL"
peds_files <- files[grepl(block, files)]
batch <- unique(sapply(peds_files, function(i) i[5]))
max(gsub("batch(\\d)", "\\1", batch))
peds_files <- peds_files[grepl("batch1", peds_files)]
ql <- unique(sapply(peds_files, function(i) i[2]))
(ql <- sort(as.numeric(gsub("PedsQL(\\d+)", "\\1", ql))))
years <- unique(sapply(peds_files, function(i) i[3]))
(years <- sort(as.numeric(gsub("(\\d+)years", "\\1", years))))

# Load data
pql_blocks <- paste0(block, ql, "_", years, "years")
pql <- lapply(pql_blocks, read_batches)
# pql <- lapply(pql, function(i) lapply(i, function(j) clean_data(j, FALSE, FALSE)))
names(pql) <- pql_blocks
lapply(pql, function(i) sapply(i, dim))
# pql1 <- lapply(pql, function(i) sapply(i, colnames))[[4]]; plot_venn(lapply(seq(ncol(pql1)), function(i) pql1[, i]))

# Duplicate individuals between batches
lapply(pql, function(i) get_intersection(lapply(i, function(i) as.data.frame(i[, 1])[, 1])))
plot_venn(lapply(pql, function(i) colnames(i[[1]])))

# Metada
pql_codes <- lapply(pql_blocks, function(i) read_batches(i, "codes"))
colnames(pql_codes[[1]][[3]])
pql_names <- lapply(pql_codes, function(i) i[[3]]$item_name)
plot_venn(pql_names)
get_intersection(pql_names)
get_difference(pql_names)

# Select level variables
level_vars <- lapply(pql_codes, get_codes_levels)
level_ <- get_levels(unlist(mapply(function(x, y) select(x[[3]], all_of(y)), pql, level_vars)))

# group_code
peds_regex <- "PedsQL(\\d{1,2})_(\\d{1,2})_"
group_codes <- pql_codes[[4]][[3]]$group_code
pql_groups <- unique(gsub(peds_regex, "", group_codes))
pql_groups0 <- unique(gsub("V\\d_", "", pql_groups))
sapply(pql_groups0, function(i) length(group_codes[str_detect(group_codes, i)]))

# item codes
pql_item_code <- lapply(pql_codes, function(i) gsub(peds_regex, "", i[[3]]$item_code))
plot_venn(pql_item_code)
# Compare item_name for each group_code between ages
get_intersection(pql_item_code)
# $`B:C:D` "SCHOOL_FUNCTIONING_4" "SCHOOL_FUNCTIONING_5"

# TODO: Reduce
pql_tot <- lapply(pql, function(i) Reduce(rbind, i))

# Duplicates individuals
get_dup_name(pql_tot[[3]])
get_dup(pql_tot[[3]])

for (i in seq_along(pql)) {
    colnames(pql_tot[[i]]) <- pql_item_code[i][[1]]
}

i_cols <- which(str_detect(pql_item_code[1][[1]], "SCHOOL_FUNCTIONING_1"))
# name_cols <- rep(paste0("SCHOOL_FUNCTIONING_", seq(2)), 2)
# Add SCHOOL_FUNCTIONING_[45] in 24 25 48 49 with NA
for (i in seq(2)) {
    pql_tot[[1]] <- add_column(pql_tot[[1]], SCHOOL_FUNCTIONING_4 = NA, SCHOOL_FUNCTIONING_5 = NA, .before = i_cols[i])
}
colnames(pql_tot[[1]]) <- colnames(pql_tot[[4]])
# Then add Date in 26 for i = {1, ,2, 3} with NA
i_col <- which(str_detect(pql_item_code[4][[1]], "DATE"))[2]
for (i in 2:3) {
    pql_tot[[i]] <- add_column(pql_tot[[i]], DATE = NA, .before = i_col)
}

pql_tot <- Reduce(rbind, pql_tot)
# sapply(as.data.frame(pql_tot)[, which(str_detect(pql_item_code[4][[1]], "SCHOOL_FUNCTIONING"))], unique)

for (i in 0:4) {
    pql_tot[pql_tot == level_[i + 1]] <- paste0(i)
}

pedsql <- finalise_data(pql_tot)
use_data(pedsql, overwrite = TRUE)
```

## SF36
```{r}
block <- blocks[10]
sf36 <- read_batches(block)
sapply(sf36, dim)
sf36_tot <- Reduce(rbind, sf36)
sf36_code <- read_batches(block, "codes")
sf36_tot[sf36_tot == "None of the Time"] <- "None of the time"

# Levels
l_level_cols <- parse_levels(sf36_tot, sf36_code)

cols_sim <- col_sim(sf36_tot, sf36_code)
get_var_names(cols_sim[[3]], sf36_code[[3]])

plot_venn(as.list(as.data.frame(t(l_level_cols))))
reformat(l_level_cols[c(8, 11:13), ])
reformat(l_level_cols[c(3, 10), ])

l_level_cols[-c(3, 10, 8, 11:13), ]

get_intersection(as.list(as.data.frame(t(l_level_cols[c(5:7), ]))))
reformat(l_level_cols[c(5:7), ])

# group_code
group_codes <- sf36_code[[1]]$group_code
get_group_occ(group_codes, "SF36_")

# Save
sf36 <- finalise_data(sf36_tot, group_codes)
use_data(sf36, overwrite = TRUE)
```

## HAQ
```{r}
block <- blocks[5]
haq <- read_batches(block)
sapply(haq, dim)
haq_tot <- Reduce(rbind, haq)
haq_code <- read_batches(block, "codes")

# Pre-replacement
keys <- c("Bathtub seat", "Bathtub bar", "Devices used for Dressing (button hook, zipper pull, etc.)", "dressing and grooming")
values <- c("Bath seat", "Bath rail", "Devices used for dressing", "Dressing")
haq_tot <- replace_levels(haq_tot, keys, values)

# Levels
l_level_cols <- parse_levels(haq_tot, haq_code)
cols_sim <- col_sim(haq_tot, haq_code)
get_var_names(cols_sim[[3]], haq_code[[3]])

i_rows <- c(1:2, 7, 10)
# unlist(cols_sim[i_rows])
haq_level0 <- reformat(l_level_cols[i_rows, ])
# get_level_name(cols_sim, haq_code[[3]])
level1 <- reformat(l_level_cols[-i_rows, ])

haq_level_tot <- parse_levels0(level1)
get_table_occ(haq_tot, haq_code, i_rows)

# group_code
group_codes <- haq_code[[1]]$group_code
get_group_occ(group_codes, "haq")

for (i in (seq(haq_level0) - 1)) {
    haq_tot[haq_tot == haq_level0[i + 1]] <- paste0(3 - i)
}

# Save
haq <- finalise_data(haq_tot, group_codes)
use_data(haq, overwrite = TRUE)
```

## CHAQ
```{r}
block <- blocks[2]
chaq <- read_batches(block)
sapply(chaq, dim)
chaq_tot <- Reduce(rbind, chaq)
chaq_code <- read_batches(block, "codes")

# Replace
na_vars <- c("Not applicable", "pas adapter à l'age", "NONE")
for (i in na_vars) {
    chaq_tot[chaq_tot == i] <- NA
}
chaq_tot <- mutate_all(chaq_tot, ~ str_replace_all(., paste(na_vars, collapse = ", "), ""))

# Levels
l_level_cols <- parse_levels(chaq_tot, chaq_code)
cols_sim <- col_sim(chaq_tot, chaq_code)
get_var_names(cols_sim[[3]], chaq_code[[3]])

i_rows <- detect_difficulty(l_level_cols)
# unlist(cols_sim[i_rows])
chaq_level0 <- reformat(l_level_cols[i_rows, ])[-1]
# get_level_name(cols_sim, chaq_code[[3]])
level1 <- reformat(l_level_cols[-i_rows, ])

# str_detect(as.data.frame(chaq_code)[, 1], paste0(i_rows, collapse = "|"))
chaq_level_tot <- parse_levels0(level1)
# get_table_occ(chaq_tot, chaq_code, i_rows)
inter <- list(haq = haq_level_tot, chaq = chaq_level_tot)
plot_venn(inter)
(res <- get_intersection0(inter))

group_codes <- chaq_code[[1]]$group_code
get_group_occ(group_codes, "chaq")

keys <- c("Devices used for dressing (button hook, zipper pull, long-handled shoe horn, etc.)", "Dressing and personal care")
values <- c("Devices used for dressing", "Dressing")
chaq_tot <- replace_levels(chaq_tot, keys, values)

# Missing "UNABLE TO DO"
for (i in seq(chaq_level0)) {
    chaq_tot[chaq_tot == chaq_level0[i + 1]] <- paste0(4 - i)
}

# Save
chaq <- finalise_data(chaq_tot, group_codes)
use_data(chaq, overwrite = TRUE)
```

## BEHCET
```{r}
block <- blocks[1]
behcet <- read_batches(block)
sapply(behcet, dim)
behcet_tot <- Reduce(rbind, behcet)
behcet_code <- read_batches(block, "codes")

# Pre-replacement
keys <- c("(no)|(not at all present)$", "(yes)|(for up to 4 weeks)$")
values <- c("0", "1")
behcet_tot <- replace_levels(behcet_tot, keys, values)

# Levels
l_level_cols <- parse_levels(behcet_tot, behcet_code)
cols_sim <- col_sim(behcet_tot, behcet_code)
get_level_name(cols_sim, behcet_code[[3]])

i_rows <- detect_difficulty(l_level_cols, "face")
# unlist(cols_sim[i_rows])
behcet_level0 <- reformat(l_level_cols[i_rows, ])

behcet_level_tot <- parse_levels0(behcet_level0)
# get_table_occ(behcet_tot, behcet_code, .Machine$double.xmax)

group_codes <- behcet_code[[1]]$group_code
get_group_occ(group_codes, "behcet")

# Save
behcet <- finalise_data(behcet_tot, group_codes)
use_data(behcet, overwrite = TRUE)
```

## DIET
```{r}
block <- blocks[4]
diet <- read_batches(block)
sapply(diet, dim)
diet_tot <- Reduce(rbind, diet)
diet_code <- read_batches(block, "codes")

# Pre-replacement
keys <- c("n/a", "N[AD]", "DM", "o", "xxx", "unknown", "[-\\/?]", "not done", "no[nt] applicable", "not specified", "Missing answer", "ne sais plus", "don't know", "not answered", "not checked by the patient", "not done")
values <- rep("NA", length(keys))
diet_tot <- replace_levels(diet_tot, paste0("^", keys, "$"), values)
diet_tot[diet_tot == "NA"] <- NA

# Levels
l_level_cols <- parse_levels(diet_tot, diet_code)
cols_sim <- col_sim(diet_tot, diet_code)
# get_level_name(cols_sim, diet_code[[3]])

i_rows <- detect_difficulty(l_level_cols, "l or less")
get_level_name0(diet_tot, cols_sim, i_rows)
diet_level0 <- reformat(l_level_cols[i_rows, ])
j_rows <- detect_difficulty(l_level_cols, "g or less")
diet_level1 <- reformat(l_level_cols[j_rows, ])
k_rows <- detect_difficulty(l_level_cols, " day")
diet_level2 <- reformat(l_level_cols[k_rows, ])
l_rows <- rownames(l_level_cols)[-c(i_rows, j_rows, k_rows, 11)]
diet_level3 <- unique(tolower(reformat(l_level_cols[l_rows, ])))
cols_diet <- get_level_name0(diet_tot, cols_sim, l_rows)
cols_diet %>% get_var_names(diet_code)
diet_tot <- update_columns(diet_tot, cols_diet, tolower)

# get_table_occ(diet_tot, diet_code, k_rows)

group_codes <- diet_code[[1]]$group_code

# Save
diet <- finalise_data(diet_tot, group_codes)
use_data(diet, overwrite = TRUE)
```

# Session information
```{r end, echo = FALSE}
sessionInfo()
```
