---
title: "Manifestations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Manifestations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
library(MultiOmics4ImmunAID)
```

# Load data
```{r, eval = FALSE}
clinic <- read_batches() %>%
    Reduce(rbind, .) %>%
    formate_immunaid()
clinic_code <- read_batches(, "codes")

modified_disease <- read_tsv(file.path(golem::get_golem_wd(), "inst", "extdata", "modified_disease.txt")) %>% arrange(ID)

clinic <- filter(clinic, !C_2643_3796 %in% c("06055", "06058", "06063"))
clinic[which(as.numeric(clinic$C_2643_3796) %in% modified_disease$ID), "C_2643_3798"] <-  modified_disease$Disease

var_na <- c(
    "none",
    "None",
    "none actually",
    "no sequelae",
    "No sequelae",
    "No sequellea",
    "NO"
)
for (i in var_na) {
    clinic[clinic == i] <- "No"
}

var_na <- c(
    "null",
    "Unknown"
)
for (i in var_na) {
    clinic[clinic == i] <- NA
}
```

# Metadata
```{r}
metadata <- clinic_code[[1]] %>%
    filter(str_detect(group_code, "IMA_ImpactedOrganOrSysTab"))
df0 <- select(clinic, metadata$column_code)
vars <- gather(df0, "manifestation", "impacted") %>%
    table() %>%
    as.data.frame() %>%
    filter(impacted == "Yes") %>%
    arrange(desc(Freq)) %>%
    pull(manifestation) %>%
    as.character()

titles <- list.mapv(
    vars, ~ {
        filter(clinic_code[[1]], column_code == .) %>%
            pull(item_name)
    }
) %>%
    str_replace("(\\d{1,2}. )", "") %>%
    str_replace("\\s*\\([^\\)]+\\)", "") %>%
    str_replace_all("Ear.*", "ENT") %>%
    str_replace("and", "/")

list.map(
    select(clinic, vars),
    f(i, j, k) ~ {
        plot_pie(
            i,
            colour = c(get_colors()[c(1, 3)], "gray"),
            cex = 22,
            digits = 1,
            hsize = 1.5,
            title = titles[j],
            sort = FALSE,
            t = -1
        )
    }
) %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 3,
        ncol = 4
    )

df_manifs0 <- select(clinic, vars) %>%
    list.map(f(i) ~ as.factor(i) %>%
        fct_recode(`0` = "No", `1` = "Yes", `NA` = "Unknown") %>%
        as.character() %>%
        as.numeric()) %>%
    list_cbind() %>%
    set_colnames(titles) %>%
    set_rownames(pull(clinic, "C_2643_3796"))

apply(df_manifs0, 2, function(x) sum(x, na.rm = TRUE)) %>%
    as.data.frame() %>%
    set_colnames(c("N")) %>%
    arrange(desc(N)) %>%
    kable0()

# Bar plot
select(df0, vars) %>%
    set_colnames(titles) %>%
    gather("manifestation", "impacted") %>%
    relocate("impacted", .before = 1) %>%
    GimmeMyPlot:::plot_bar_2cat(
        stats = FALSE,
        colour1 = get_colors()[c(3, 1)],
        colour3 = "black",
        legend = c("Yes", "No")
    )

# Per disease
clinic0 <- mutate(
    clinic,
    C_2643_3798 = str_remove_all(C_2643_3798, " \\(.*") %>%
        str_replace_all("Adult.*", "AOSD") %>%
        str_replace_all("Systemic.*", "SOJIA") %>%
        str_replace_all("Chronic.*", "CRO") %>%
        str_replace_all("Inflammation.*", "IUO") %>%
        str_replace_all("Pediatric.*", "MIS-C")
) %>% filter(!str_detect(C_2643_3798, "control"))

n <- pull(clinic0, C_2643_3798) %>%
    fct_count() %>%
    rename(n_tot = n)

disease_to_remove <- filter(n, n_tot == 1) %>% pull(f) %>% as.character()
clinic0 <- filter(clinic0, !C_2643_3798 %in% disease_to_remove)

# Bar plot
per_manif <- list.map(
    seq(vars),
    f(i) ~ {
        df <- select(clinic0, c(vars[i], C_2643_3798)) %>%
            set_colnames(c(titles[i], "Disease"))
        # p <- GimmeMyPlot:::plot_bar_2cat(
        #     df,
        #     cex = 0.8,
        #     stats = FALSE,
        #     width_title = 30,
        #     colour1 = get_colors()[c(3, 1)],
        #     colour3 = "black",
        #     title = titles[i],
        #     threshold = 1,
        #     legend = c("Yes", "No"),
        #     sort = TRUE
        # ) + theme(
        #     axis.title.y = element_blank(),
        #     legend.position = "none")
        df1 <- filter(df, !!sym(titles[i]) == "Yes") %>%
            pull(Disease) %>%
            fct_infreq() %>%
            fct_rev() %>%
            fct_count() %>%
            left_join(n)
        res <- mutate(df1, perc = n / n_tot * 100) %>%
            arrange(desc(perc))
        p <- filter(df, !!sym(titles[i]) == "Yes") %>%
            pull(Disease) %>%
            plot_bar_mcat(
                sample_size = pull(df1, "n_tot"),
                inverse = TRUE,
                title = titles[i],
                cex = 6,
                width_text = 30,
                colour = c("gray", "#99000d"),
                colour2 = "white"
            )
        # res$perc %>%
        #     set_names(res$f) %>%
        #     GimmeMyPlot:::post_hoc_chi2(count = TRUE) %>%
        #     filter(FDR <= 0.05) %>%
        #     arrange(desc(FDR))
        list(p = p, res = res)
    }
)

list.map(per_manif, .$res) %>% set_names(titles)
list.map(per_manif, .$p) %>%
    plot_grid(
        plotlist = .,
        ncol = 4,
        nrow = 3,
        align = "hv"
    )

# Spider plots
diseases <- pull(clinic0, C_2643_3798) %>%
    fct_count() %>%
    arrange(desc(n)) %>%
    filter(n >= 15) %>%
    pull(f) %>%
    as.character()
diseases0 <- pull(clinic0, C_2643_3798) %>%
    fct_infreq() %>%
    levels()
per_disease0 <- list.map(
    diseases0,
    f(x) ~ {
        df <- filter(clinic0, C_2643_3798 == x) %>%
            select(vars) %>%
            set_colnames(titles)
        list.mapv(
            sort(titles),
            f(y) ~ {
                res <- select(df, y) %>%
                    filter(!!sym(y) == "Yes")
                ifelse(nrow(res) > 0, nrow(res), 0)
            }
        )
    }
) %>% set_names(diseases0)

per_disease <- list.cbind(per_disease0)
sample_size <- colnames(per_disease) %>%
    data.frame(f = .) %>%
    left_join(., n) %>%
    pull(n_tot)
per_disease_perc <- mapply(function(x, y) x * 100 / y, per_disease0, sample_size)

# path <- file.path(golem::get_golem_wd(), "inst", "results", "img")
# tiff(
#     file.path(path, "manif", ".manif.tiff"),
#     units = "px",
#     width = 3500 * cex,
#     height = 1500 * cex,
#     res = 300
# )
sample_size0 <- left_join(data.frame(f = diseases), n) %>% pull(n_tot)
par(mfrow = c(2, 4))
for (x in seq_along(diseases0[9:16])) {
    per_disease_perc[, diseases0[9:16][x]] %>%
        set_names(
            names(.) %>%
                str_replace_all("(Musculo)(skeletal)", "\\1- \\2")
        ) %>%
        plot_radar(
            add_percent = TRUE,
            alpha = 0.25,
            n_max = 100,
            n_interval = 4,
            cex_main = 1.7,
            cex_axis = 1.5,
            cex_sub = 1,
            width_text = 5,
            colour = GimmeMyPlot:::palette_discrete()[x],
            title = paste0(diseases0[9:16][x], ", N = ", sample_size0[9:16][x])
        )
}
# dev.off()
```

# Functions
```{r}
parse_manif0 <- function(x, y, z, a, b = NULL, type = 0, parse = FALSE) {
    x0 <- pull(x, column_code) %>%
        select(clinic, .) %>%
        set_rownames(ids)
    n <- ncol(x0)
    if (n > 0) {
        x0 %>%
            set_colnames(rep(seq(n), n / n)) %>%
            list.parse() %>%
            list.map(f(i, it) ~ {
                temp <- list.map(
                    i,
                    f(j, jt) ~ {
                        nb_lesions <- NULL
                        j <- j %>%
                            str_remove_all(" \\(.+\\)") %>%
                            str_replace_all("(CLINICAL EXAMINATION)|(Clinically)|(physcial examination)|((Clinical ?)?[Ee]xamination)", "Clinical examination") %>%
                            str_replace_all("UVEITE ANTERIEURE", "Anterior uveitis") %>%
                            str_replace_all("MYALGI[AE]", "Myalgia") %>%
                            str_replace_all("rthralgie", "rthralgia") %>%
                            str_replace_all("rthrite", "rthritis") %>%
                            str_replace_all("(Artthralgie-myalgie)|(myalgia, arthralgia)|(Myalgia\\, arthralgia)|(Athralgia + myalgia)", "Arthralgia ; Myalgia") %>%
                            str_replace_all("pieds gauche", "Foot left") %>%
                            str_replace_all("the (lateral tibial plateau)", "\\1") %>%
                            str_replace_all(" Limb", " limb") %>%
                            str_replace_all("Thoracic Anterior", "Thoracic anterior") %>%
                            str_replace_all("No [Ss]equell?[ae]{1,2}", "None") %>%
                            str_remove_all("=.*") %>%
                            # str_replace_all("(\\w)/(\\w)", "\\1; \\2") %>%
                            str_replace_all(".*rayon main gauche", "Interphalangeal toe left") %>%
                            str_replace_all("I( right) finger", "Interphalangeal\\1") %>%
                            str_replace_all("[Nn]o [Ss]equell?[ae]{1,2}", "None") %>%
                            # str_replace_all("arthralgia des bras", "Arthralgia") %>%
                            str_replace_all("I p p 1er rayon main gauche", "Interphalangeal toe left") %>%
                            str_replace_all("^I ", "Interphalangeal") %>%
                            str_remove_all(" ((is)|(describes)) [at].*") %>%
                            str_remove_all(" – severe unremitting") %>%
                            str_replace_all(" weakness, e(ar pain)", " paralysis; E\\1") %>%
                            str_replace_all("(Enteritis)/(colitis)", "\\1; \\2") %>%
                            str_replace_all("schizophrénie", "Schizophrenia") %>%
                            str_replace_all("thrombophlébite cérébrale", "Cerebral thrombophlebitis") %>%
                            str_replace_all("l’épiphyse distale du tibia gauche", "Distal epiphysis of the left tibia") %>%
                            str_replace_all("(knee)s", "\\1") %>%
                            str_remove_all("-6") %>%
                            str_replace_all("mal de gorge", "Sore throat") %>%
                            str_replace_all("P(haryngitis)", "p\\1") %>%
                            str_replace_all("Conjonctivite", "Conjunctivitis") %>%
                            str_replace_all("(ECG), Cardiac US, (Chest pain)", "\\1; Ultrasound; \\2") %>%
                            str_replace_all("(ECHOGRAPHIE)|(echographie)|(^US$)", "Ultrasound") %>%
                            str_replace_all("([Bb]lood ((sample)|(exams)))|(bilan sanguin)|(BILAN BIOLOGIQUE)", "Blood test") %>%
                            str_replace_all("Conjonctivite", "Conjunctivitis") %>%
                            str_replace_all("Adénopathies cervicales bilatérales non nécrotiques", "Bilateral non-necrotic cervical adenopathy") %>%
                            str_replace_all("diarrhée", "Diarrhea") %>%
                            str_replace_all("des bras", "of the arms") %>%
                            str_replace_all("difficultés alimentaires", "Eating disorders") %>%
                            str_replace_all(".*panchement articulaire gauche", "Left joint effusion") %>%
                            str_replace_all("jenoux inflammatoire", "Inflammatory knees") %>%
                            str_replace_all("nausée", "Inflammatory knees") %>%
                            str_replace_all(" des genoux", " of the knees") %>%
                            str_replace_all("s(yndrome) de (Budd-Chiari)", "\\2 s\\1") %>%
                            str_squish() %>%
                            to_title()
                        if (type == 1) {
                            j <- str_remove_all(j, "[\\[\\{\\}\\]\\\"]") %>%
                                str_remove_all("x:\\d+(\\.\\d+)?,y:\\d+(\\.\\d+)?,pathId:") %>%
                                str_replace_all("([A-Z])", " \\1") %>%
                                str_squish() %>%
                                str_split(", ") %>%
                                pluck(1)
                            # nb_lesions <- ifelse(all(is.na(j)), 0, length(j))
                            j <- list.map(j, f(k) ~ if (is.na(k) | (length(k) == 1 && str_detect(k, ";"))) k else str_to_sentence(k)) %>%
                                unlist() %>%
                                paste0(collapse = " ; ")
                        }
                        if (type == 2) {
                            j <- str_to_sentence(j) %>%
                                str_replace_all(" gauche séquellaire.*", "; Cognitive impairment") %>%
                                str_replace_all(" occurs together.*", "; Skin lesions") %>%
                                str_replace_all(".*[Hh][ée]mipar[ée]si[es] ?.*", "Hemiparesis") %>%
                                str_replace_all("Irritable", "Irritability") %>%
                                str_replace_all(".*[Mm]enin?git[ei]s?.*", "Menigitis") %>%
                                str_replace_all("Severe chest", "Chest pain") %>%
                                str_replace_all(".*bardet-biedl syndrome.*", "Bardet-Biedl syndrom; Polydactylia") %>%
                                str_replace_all("(.*)?((Céphalées)|([Hh]eadache)|(Holo crânienne permanantes))( .*)?", "Headache")
                        }
                        if (type == 3) {
                            j <- ifelse(j == "Yes", pull(x, item_name)[jt], j)
                        }
                        if (type == 4) {
                            j <- str_split(j, "\\$\\$") %>% pluck(1)
                            if (length(j) > 1) {
                                j <- j[2:1] %>% paste0(collapse = ": ")
                            }
                        }
                        if (type == 5 | parse) {
                            pattern <- " ((\\+)|(and)|(et)) "
                            if (!is.na(j) && str_detect(j, pattern)) {
                                j <- str_split(j, pattern) %>%
                                    pluck(1) %>%
                                    str_squish() %>%
                                    to_title() %>%
                                    paste0(collapse = " ; ")
                            }
                            j <- str_remove_all(j, "\\.$")
                        }
                        j <- str_split(j, " ?; ?") %>%
                            list.map(~ str_squish(.)) %>%
                            to_title() %>%
                            list(.) %>%
                            set_names(z)
                        # if (!is.null(nb_lesions)) {
                        #     c(j, list(`Nb lesions` = nb_lesions))
                        # } else {
                        #     j
                        # }
                    }
                ) %>% discard(function(x) all(is.na(x) | x == "NA"))
                if (type == 3) {
                    temp <- purrr::discard(temp, function(x) str_detect(x, "No"))
                }
                if (!is.null(b)) {
                    temp <- list(temp) %>%
                        set_names(b) %>%
                        compact()
                }
                list(temp) %>%
                    set_names(a) %>%
                    compact() %>%
                    list(.) %>%
                    set_names(y) %>%
                    compact()
            }) %>%
            compact()
    }
}

parse_manif1 <- function(x, y, z, a, type = 0, parse = TRUE) {
    if (pull(x, repeat_inds) %>% purrr::discard(is.na) %>% length(.) > 0 && pull(x, repeat_inds) %>%
        str_detect("\\.") %>%
        any()) {
        n <- pull(x, repeat_inds) %>%
            str_split("\\.") %>%
            list.map(f(i) ~ pluck(i, 1)) %>%
            unlist() %>%
            max() %>%
            as.numeric()
        list.map(seq(n), f(i, j) ~ filter(x, str_detect(repeat_inds, paste0(i, "\\."))) %>% parse_manif0(y, z, a, j, type = type, parse = parse)) %>%
            compact() %>%
            Reduce(function(x, y) list.merge(x, y), .)
    } else {
        parse_manif0(x, y, z, a, type = type, parse = parse)
    }
}

parse_manif <- function(x, y, z, a, type = 0, parse = TRUE) {
    id <- unique(pull(x, item_id))
    if (length(id > 1)) {
        list.map(id, f(i) ~ filter(x, item_id == i) %>% parse_manif1(y, z, a, type = type, parse = parse)) %>%
            compact() %>%
            Reduce(function(x, y) list.merge(x, y), .)
    } else {
        parse_manif1(x, y, z, a, type = type, parse = parse)
    }
}
```

# Parsing
```{r}
vars <- c(
    "NEURO",
    "MUSCU",
    "CARDIO",
    "RENAL",
    "PULMO",
    "GASTRO",
    "ENT",
    "OPHTALMO",
    "URO",
    "HAEMATO"
)
var_names <- c(
    "is_active",
    "active_description",
    "non_active_description",
    "date_non_active",
    rep("diagnosis", 2)
)

ids <- pull(clinic, C_2643_3796) %>% as.integer()
list_manif <- ids %>%
    setNames(ids) %>%
    data.frame(id = .) %>%
    list.parse()
list_manif <- list.map(
    vars,
    f(x, y) ~ {
        list.map(
            c(paste0("MANIF", c(paste0(c("_IS", "", "_NON"), "_ACTIVE"), "_NON_ACTIVE_DATE", "_DIAGNOSIS")), "OTHER_NEW_VALUE"),
            f(i, j) ~ {
                clinic_code[[1]] %>%
                    filter(str_detect(group_code, paste0("^IMA_", str_to_title(x), "Manif(Bloc|Activity|Workup)$"))) %>%
                    filter(str_detect(item_code, paste0("^IMA_", i, "$"))) %>%
                    parse_manif(x, var_names[j], "manif")
            }
        ) %>%
            compact() %>%
            Reduce(function(x, y) list.merge(x, y), .)
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

# x <- "non_active_description"; list.map(tmp0, f(a) ~ list.map(a, f(b) ~ list.map(b$manif, f(d) ~ if(!is.null(d[[x]])) d[[x]] %>% compact()) %>% compact()) %>% compact()) %>% unlist() %>% unname() %>% unique()
#  x <- "diagnosis"; list.map(tmp0, f(a) ~ list.map(a, f(b) ~ list.map(b$manif, f(d) ~ list.map(d, f(e) ~ if(is.list(e) && !is.null(e[[x]])) e[[x]] %>% compact()) %>% compact()) %>% compact())%>% compact()) %>% unlist() %>% unique()

list_manif <- list.map(
    vars,
    f(x, y) ~ {
        clinic_code[[1]] %>%
            filter(str_detect(group_code, paste0("^IMA_", str_to_title(x), "ManifBloc$"))) %>%
            filter(str_detect(item_code, paste0("^IMA_", x, "_MANIF$"))) %>%
            parse_manif(x, "manif", "manif", type = 4)
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

# lapply(tmp, function(x) x %>% unlist() %>% unname() %>% unique())

list_manif <- list.map(
    c("LESION_IS_ACTIVE", "ACTIVE_LESIONS", "NON_ACTIVE_LESIONS"), f(i, j) ~ {
        filter(clinic_code[[1]], str_detect(group_code, paste0("^IMA_Mucocutaneous_manifestations"))) %>%
            filter(str_detect(item_code, paste0("^IMA_MUCO_", i, "$"))) %>%
            parse_manif("MUCO", var_names[j], "manif")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)


list_manif <- filter(clinic_code[[1]], str_detect(item_code, "^IMA_MUSCU_MANIF_ACTIVE_OSTEISIS$")) %>%
    parse_manif("MUSCU", "active_description_osteitis", "manif") %>%
    list.merge(list_manif, .)

list_manif <- list.map(vars, f(i) ~ {
    list.map(seq(2), f(j) ~ {
        temp <- filter(clinic_code[[1]], str_detect(group_code, paste0("^IMA_", str_to_title(i), "SequellaeBloc$")))
        if (j == 1) {
            temp <- filter(temp, str_detect(item_code, paste0("^IMA_", i, "_SEQUELLAE$")))
        } else {
            temp <- filter(temp, str_detect(item_code, paste0("^IMA_OTHER_NEW_VALUE$")))
        }
        parse_manif(temp, i, "sequellae", "sequellae", type = 5)
    }) %>%
        compact() %>%
        Reduce(function(x, y) list.merge(x, y), .)
}) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

# list.search(list_manif, str_detect(., "Sterility"))
sympt_names <- c("symptom", "frequency")
list_manif <- list.map(vars, f(i, it) ~ {
    list.map(paste0("_FIRST_QUESTION", c("", "_FREQ")), f(j, jt) ~ {
        temp <- filter(clinic_code[[1]], str_detect(group_code, paste0("^IMA_", str_to_title(i), "FirstQuestionBloc$")))
        if (it == 8 && jt == 1) {
            type <- 3
        } else {
            type <- 0
        }
        if (it == 1) {
            temp <- filter(temp, str_detect(item_code, paste0("^IMA_MANIF_DESCRIPTION$")))
        } else {
            temp <- filter(temp, str_detect(item_code, paste0("^IMA_", i, j, "$")))
        }
        parse_manif(temp, i, sympt_names[jt], "symptom", type = type)
    }) %>%
        compact() %>%
        Reduce(function(x, y) list.merge(x, y), .)
}) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)


list_manif <- filter(clinic_code[[1]], str_detect(group_code, "^IMA_NeuroManifDescription$")) %>%
    parse_manif("NEURO", "symptom", "symptom", type = 2) %>%
    list.merge(list_manif, .)

list_manif <- filter(clinic_code[[1]], str_detect(group_code, "^IMA_RenalManifBloc$")) %>%
    parse_manif0("RENAL", "manif", "manif", type = 3) %>%
    list.merge(list_manif, .)

list_manif <- filter(clinic_code[[1]], str_detect(item_code, "^IMA_MANIF_DIAGNOSIS_DESCRIPTION$")) %>%
    parse_manif("MUSCU", "diag_description", "manif") %>%
    list.merge(list_manif, .)

list_manif <- list.map(
    c("CERVICAL_ADENITIS", "PAIN"),
    f(i, j) ~ {
        filter(clinic_code[[1]], str_detect(item_code, paste0("^IMA_HAEMATO_MANIF_", i, "$"))) %>%
            parse_manif("HAEMATO", str_to_lower(i), "manif")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

list_manif <- list.map(
    c("PULM_HYP", "CHRO_CAR", "AMP", "ANEURYSM"),
    f(i, j) ~ {
        filter(clinic_code[[1]], str_detect(item_code, paste0("^IMA_CARDIO_SEQUELLAE_FOR_", i, "$"))) %>%
            parse_manif("CARDIO", str_to_lower(i), "sequellae")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

var_names0 <- c("localisation_configuration", "localisation_number_lesion", "localisation_body_parts", "localisation_distribution", "localisation_symetry", "localisation_exposition", "localisation_other_signs", "localisation_disease_specific")
list_manif <- list.map(
    c(paste0("LESION_", c("CONF", "LOC_S_OR_M", "LOC_ON_BODY", "DISTRIBUTION_1", "DISTRIBUTION_2", "ON_SKIN", "OTHER_CLIN_SIGNS")), "DISEASE_SPEC_LESIONS"),
    f(i, j) ~ {
        filter(clinic_code[[1]], str_detect(item_code, paste0("^IMA_MUCO_", i, "$"))) %>%
            parse_manif("MUCO", var_names0[j], "manif")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

# list.map(list_manif, f(i) ~ if(!is.null(i$NEURO)) i$NEURO) %>% compact()
# list.map(list_manif, f(i) ~ if(!is.null(i$NEURO$manif)) list.map(i$NEURO$manif, f(j) ~ j$manif) %>% compact()) %>% compact()
# list.map(list_manif, f(i) ~ if(!is.null(i$NEURO$manif)) list.map(i$NEURO$manif, f(j) ~ if(!is.null(j$manif) && str_detect(j$manif, "Cranial")) j$manif) %>% compact()) %>% compact()
# pluck(list_manif, "8002") %>% pluck("MUSCU")

list_manif <- list.map(
    vars,
    f(x, y) ~ {
        clinic_code[[1]] %>%
            filter(str_detect(group_code, paste0("^IMA_", str_to_title(x), "(Loc|Manif)"))) %>%
            filter(str_detect(item_code, paste0("^IMA_MANIF_LEFT_RIGHT_BILATERAL$"))) %>%
            parse_manif(x, "laterality", "manif")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

list_manif <- list.map(
    vars,
    f(x, y) ~ {
        temp <- filter(clinic_code[[1]], str_detect(group_code, paste0("^IMA_", str_to_title(x)))) %>%
            filter(str_detect(item_code, "_LOCALISATION")) %>%
            filter(!str_detect(column_code, "C_2674_4001"))
        if (y == 2) {
            type <- 1
        } else if (y == 3) {
            type <- 4
        } else {
            type <- 0
        }
        parse_manif(temp, x, "localisation", "manif", type = type, parse = TRUE)
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)


list_manif <- filter(clinic_code[[1]], str_detect(column_code, "^C_2720_3885")) %>%
    parse_manif("HAEMATO", "localisation", "manif", type = 1) %>%
    list.merge(list_manif, .)

list_manif <- list.map(
    vars,
    f(x, y) ~ {
        clinic_code[[1]] %>%
            filter(str_detect(group_code, paste0("^IMA_", str_to_title(x), "Manif"))) %>%
            filter(str_detect(item_code, paste0("_TYPE|_TRANS|_DIF_INTER"))) %>%
            parse_manif(x, "type", "manif")
    }
) %>%
    compact() %>%
    Reduce(function(x, y) list.merge(x, y), .) %>%
    list.merge(list_manif, .)

list_manif <- filter(clinic_code[[1]], str_detect(group_code, "^IMA_EntSequellaeBloc$")) %>%
    filter(str_detect(item_code, paste0("^IMA_MANIF_LEFT_RIGHT_BILATERAL$"))) %>%
    parse_manif("ENT", "laterality", "sequellae") %>%
    list.merge(list_manif, .)

list_manif <- filter(clinic_code[[1]], str_detect(item_code, paste0("^IMA_OPHTALMO_SEQUELLAE_LEFT_RIGHT_BILATERAL_FOR"))) %>%
    parse_manif("OPHTALMO", "laterality", "sequellae") %>%
    list.merge(list_manif, .)
# use_data(list_manif, overwrite = TRUE)
```

# QC
```{r, eval = FALSE}
l_names <- list.map(list_manif, f(x) ~ list.map(x, f(i, ii) ~ if (ii > 1) list.map(i, f(j) ~ list.map(j, f(k) ~ names(k))))) %>%
    unlist() %>%
    unique() %>%
    sort() %>%
    discard(function(x) x %in% seq(10))

list.map(l_names, f(xx) ~ list.map(list_manif, f(x) ~ list.map(x, f(i, ii) ~ if (ii > 1) list.map(i, f(j) ~ list.map(j, f(k) ~ if (!is.null(k[[xx]])) k[[xx]])))) %>% unlist() %>% unique() %>% sort())

# cou$localisation_disease_specific %>% str_replace_all(".*[Ee]rythema.*", "Erythema") %>% unique()

# list.search(list_manif, .[grepl(".*[Hh][ée]mipar[ée]si[es] .*", .)], classes = "character", unlist = TRUE)
l_names0 <- list.map(list_manif, f(x) ~ list.map(x, f(i, ii) ~ if (ii > 1) list.map(i, f(j) ~ list.map(j, f(k) ~ list.map(k, f(l) ~ names(l)))))) %>%
    unlist() %>%
    unique() %>%
    sort() %>%
    discard(function(x) x %in% seq(10))

# list.map(
#     l_names0,
#     f(i) ~ {
#          list.map(
#              list_manif,
#              f(x) ~ {
#                  list.map(
#                      x,
#                      f(i, ii) ~ {
#                              if (ii > 1) {
#                                  list.map(
#                                      i,
#                                      f(j) ~ {
#                                          list.map(
#                                              j,
#                                              f(k) ~ {
#                                                  if (!is.null(k)) {
#                                                  list.map(
#                                                      k,
#                                                      f(l) ~ if(is.list(l) && !is.null(l[[i]])) l[[i]])
#                                                  }
#                                              }
#                                              )
#                                      }
#                                      ) %>%
#                                      unlist() %>%
#                                      unique() %>%
#                                      sort() %>%
#                                      discard(function(x) x %in% seq(10))
#                              }
#                          }
#                  )
#              }
#          )
#     }
# )

list.map(
    c(vars, "MUCO"),
    f(x) ~ list.map(
        list_manif,
        f(i) ~ list.map(
            i[[x]]$manif,
            f(j) ~ list.map(j, f(k) ~ k) %>% compact()
        ) %>%
            compact()
    ) %>%
        compact() %>%
        unlist() %>%
        unique() %>% sort()
) %>% compact()

ids <- list.map(
    c(vars, "MUCO"),
    f(x) ~ {
        list.map(
            list_manif,
            f(i) ~ {
                list.map(
                    i[[x]]$manif,
                    f(j) ~ list.map(j, f(k) ~ names(k)) %>%
                        compact()
                ) %>%
                    compact()
            }
        ) %>% compact()
    }
) %>%
    compact() %>%
    unlist() %>%
    unique()
list.map(ids, f(x) ~ list.map(vars, f(y) ~ get_manif0(y, x, l = list_manif)) %>%
    compact() %>%
    unlist() %>%
    unique() %>%
    sort()) %>% compact()
# use_data(list_manif, overwrite = TRUE)
```

# Function (2)
```{r}
get_manif <- function(x, y, z = "manif", pattern = ".*", l = list_manif) {
    list.map(
        l,
        f(i) ~ list.map(
            i[[x]][[z]],
            f(j) ~ keep(j[[y]], str_detect(j[[y]], pattern))
        ) %>% compact()
    )
}

get_manif0 <- function(x, y, z = "manif", pattern = ".*", l = list_manif) {
    list.map(
        l,
        f(i) ~ list.map(
            i[[x]]$manif,
            f(j) ~ list.map(
                j,
                f(k) ~ if (is.list(k)) keep(k[[y]], str_detect(k[[y]], pattern)) %>% compact()
            ) %>% compact()
        ) %>% compact()
    )
}

get_occ_list <- function(x, fx = function(x) x) {
    vars <- unlist(x) %>%
        fx() %>%
        unique() %>%
        sort() %>%
        discard(function(x) str_detect(x, "^\\d*$")) %>%
        discard(function(x) str_detect(x, "^Other$"))
    list.map(vars, f(i) ~ {
        list.mapv(x, f(j) ~ {
            i <- str_remove_all(i, "\\s*\\([^\\)]+\\)")
            j <- unlist(j) %>% fx()
            if (length(j) < 1) FALSE else any(str_detect(j, i))
        }) %>% as.numeric()
    }) %>%
        list_cbind0() %>%
        set_rownames(names(x))
}
```

# Plot
```{r}
(vars0 <- list.map(c(vars, "MUCO"), f(x) ~ list.map(list_manif, f(i) ~ names(i[[x]])) %>%
    compact() %>%
    unlist() %>%
    unique()) %>% compact())
(vars1 <- list.map(
    c(vars, "MUCO"),
    f(x) ~ list.map(
        list_manif,
        f(i) ~ list.map(
            i[[x]]$manif,
            f(j) ~ list.map(j, f(k) ~ names(k)) %>% compact()
        ) %>%
            compact()
    ) %>%
        compact() %>%
        unlist() %>%
        unique()
) %>% compact())
# $NEURO
# [1] "diagnosis"  "laterality" "type"
#
# $MUSCU
# [1] "diagnosis"        "diag_description"
#
# $CARDIO
# [1] "diagnosis"    "localisation" "laterality"
#
# $PULMO
# [1] "diagnosis"
#
# $GASTRO
# [1] "diagnosis"
#
# $ENT
# [1] "diagnosis"
#
# $OPHTALMO
# [1] "diagnosis"
#
# $HAEMATO
# [1] "diagnosis"    "pain"         "localisation"
```

# Mucocutaneous
```{r}
list.map(
    unlist(vars0) %>% unique(),
    f(i) ~ {
        list.map(
            c(vars, "MUCO"),
            f(x) ~ {
                list.map(
                    list_manif,
                    f(y) ~ list.map(y[[x]][[i]], ~ names(.))
                ) %>%
                    compact() %>%
                    unlist() %>%
                    unique() %>%
                    discard(function(x) str_detect(x, "^\\d*$"))
            }
        ) %>% compact()
    }
)

(l_manifs <- list.map(vars, f(x) ~ get_manif(x, "manif") %>% get_occ_list()) %>% compact())
list.map(l_manifs, f(x) ~ apply(x, 2, function(i) sum(i, na.rm = TRUE)))

list.map(list_manif, f(i) ~ list.map(i[["MUCO"]]$manif, f(j) ~ names(j))) %>%
    compact() %>%
    unlist() %>%
    unique() -> ids
var_names1 <- c("Active manifestation", "Affected body parts", "Specific disease", "Configuration", "Other signs", "Non-active manifestation")
l_muco <- list.map(ids, f(i, j) ~ get_manif("MUCO", i) %>% get_occ_list(
    fx = function(x) {
        str_replace_all(x, "Axillary", "Lower limbs") %>%
            str_replace_all("((Digits.*)|(Palms.*))", "Extremities") %>%
            str_replace_all("((Buttocks)|(Inguinal))", "Seat") %>%
            str_replace_all("((Neck)|(Scalp)|(Face))", "Head")
    }
))
colnames(l_muco$localisation_body_parts) <- str_replace_all(colnames(l_muco$localisation_body_parts), "(.*) =.*", "\\1")

names(l_muco) %in% c("active_description", "localisation_body_parts", "localisation_disease_specific", "localisation_configuration", "localisation_other_signs", "non_active_description") %>%
    l_muco[.] %>%
    list.map(
        f(i, j) ~ {
            plot_bar_mcat(
                i,
                collapse = TRUE,
                cex = 8,
                width_text = 35,
                n_max = 100,
                ratio = 5,
                title = var_names1[j]
            )
        }
    ) %>%
    list.sort(nrow(.$data)) %>%
    rev() %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 3,
        ncol = 2,
        rel_heights = c(1.5, 1, 0.55)
    )

titles <- c("Active manifestation", "N. of manifestation", "Distribution", "Symetry", "Exposition")
names(l_muco) %in% c("is_active", "localisation_number_lesion", "localisation_distribution", "localisation_symetry", "localisation_exposition") %>%
    l_muco[.] %>%
    lapply(. %>% mutate(., `NA` = rowSums(.) %>% `==`(0) %>% as.numeric())) %>%
    list.map(
        f(i, j) ~ {
            plot_pie(
                i,
                cex = 20,
                digits = 1,
                hsize = 1.5,
                colour = c(get_colors()[c(1, 3)], "gray"),
                title = titles[j],
                # legend = FALSE,
                t = -1,
                width_text = 30
            )
        }
    ) %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 3,
        ncol = 2
    )

t_muco <- Reduce(cbind, l_muco)
colnames(t_muco)[c(1:2)] <- c("Non active", "Active")
apply(t_muco, 2, sum) %>%
    `>`(2) %>%
    apply(t_muco, 2, sum)[.]
use_data(t_muco, overwrite = TRUE)

t_muco_manif <- get_manif("MUCO", "active_description") %>%
    get_occ_list() %>%
    apply(1, function(x) any(x == 1) %>% as.numeric()) %>%
    data.frame(Mucocutaneous = .)
```

# Other manifestations
## Barplots
```{r}
t_local <- get_manif("MUSCU", "localisation") %>%
    get_occ_list(
        fx = function(x) {
            str_replace_all(x, "(.*[Ii]nterphalangeal.*)|(Metacarpophalangeal.*)|(Hands)|(Wrist)", "Hand") %>%
                str_replace_all("(Metatarsophalangeal.*)|(Ankle)", "Foot") %>%
                str_replace_all("(Pubis)|(Hip)|(Sacroiliac)", "Pelvis") %>%
                str_replace_all("clavicular?", "Shoulder") %>%
                str_replace_all("(femoral)|(.*tibia).*", "Inferior limb") %>%
                str_replace_all("(Lumbar column)|(Cervical column)|(Thoracic column)", "Spine") %>%
                str_remove_all("(right)|([Ll]eft)|(Lateral)|(l plateau)|(joint)|(Acromio)|(Sterno)") %>%
                str_replace_all("Temporomandibular", "Skull") %>%
                str_squish()
        }
    ) %>%
    select(apply(., 2, sum) %>% keep(function(x) x > 3) %>% names())

#  %>% str_replace_all("((Foot)|(Knee))", "Lower limb") %>% str_replace_all("((Hand)|(Elbow))", "Superior limb") %>% str_replace_all("clavicula", "Elbow") %>% str_replace_all("Temporomandibular", "Skull")

x <- "MUSCU"
list.map(list_manif, f(i) ~ list.map(i[[x]]$manif, f(j) ~ names(j))) %>%
    compact() %>%
    unlist() %>%
    unique() %>%
    discard(function(x) str_detect(x, "^\\d*$")) -> ids
l_manif <- list.map(ids, f(i, j, k) ~ get_manif(x, i) %>%
    get_occ_list(
        fx = function(x) {
            str_replace_all(x, "(.*interphalangeal.*)|(Metacarpophalangeal.*)|(Hands)|(Wrist)", "Hand") %>%
                str_replace_all("(Metatarsophalangeal.*)|(Ankle)|(^Interphalangeal.*)", "Foot") %>%
                str_replace_all("(Pubis)|(Hip)|(Sacroiliac)", "Pelvis") %>%
                str_replace_all("clavicular?", "Shoulder") %>%
                str_replace_all("(femoral)|(.*tibia).*", "Inferior limb") %>%
                str_replace_all("(Lumbar column)|(Cervical column)|(Thoracic column)", "Spine") %>%
                str_remove_all("(right)|([Ll]eft)|(Lateral)|(l plateau)|(joint)|(Acromio)|(Sterno)") %>%
                str_replace_all("Temporomandibular", "Skull") %>%
                str_replace_all("P(haryngitis)", "p\\1") %>%
                str_squish() %>%
                # str_remove_all("\\:.*") %>%
                str_remove_all(" manifestations")
        }
    ) %>%
    select(-contains(c("Skull", "Proximal"))))

titles <- c("Localisation", "Manifestation") %>% rev()
names(l_manif) %in% c("localisation", "manif") %>%
    l_manif[.] %>%
    list.map(
        f(i, j) ~ {
            plot_bar_mcat(
                i,
                collapse = TRUE,
                cex = 8,
                width_text = 30,
                ratio = 5,
                title = titles[j]
            )
        }
    ) -> p

list.map(
    unlist(vars1) %>% unique() %>% sort() %>% .[-1],
    f(i) ~ {
        res <- get_manif0(x, i)
        if (compact(res) %>% length() %>% `>`(0)) {
            get_occ_list(
                res # ,
                # fx = function(x)
                # str_remove_all(x, ".*\\: ")
            ) %>%
                plot_bar_mcat(
                    collapse = TRUE,
                    cex = 8,
                    width_text = 30,
                    n_collapse = 5,
                    ratio = 5,
                    title = to_title(i)
                )
        }
    }
) %>% compact() -> p2

y <- "localisation"
get_manif0(x, y) %>%
    get_occ_list(
        fx = function(x) {
            str_remove_all(x, "\\:.*")
        }
    ) %>%
    plot_bar_mcat(
        collapse = TRUE,
        cex = 8,
        width_text = 20,
        ratio = 5,
        title = to_title(y)
    ) -> p5

y <- "laterality"
get_manif0(x, y) %>%
    get_occ_list() %>%
    mutate(`NA` = rowSums(.) %>% `==`(0) %>% as.numeric()) %>%
    plot_pie(
        cex = 15,
        digits = 1,
        hsize = 1.5,
        colour = c(get_colors()[c(1, 4, 2)], "gray"),
        title = to_title(y),
        legend = TRUE,
        t = -0.9, # .75,
        width_title = 30,
        width_text = 30
    )

list.map(
    c("symptom", "frequency"),
    f(i) ~ {
        res <- get_manif(x, i, "symptom")
        if (compact(res) %>% length() %>% `>`(0)) {
            get_occ_list(
                res,
                fx = function(x) {
                    str_replace_all(x, "(Arthralgia).*", "\\1") %>%
                        str_replace_all(".*pros?thesis.*", "Prosthesis") %>%
                        str_replace_all(".*a(rthrosis).*", "A\\1")
                }
            ) %>%
                select(-contains(c("Other", "None", "Pains"))) %>%
                plot_bar_mcat(
                    collapse = TRUE,
                    cex = 8,
                    width_text = 30,
                    ratio = 5,
                    title = to_title(i)
                )
        }
    }
) %>% compact() -> p3

y <- "frequency"
get_manif(x, y, "symptom") %>%
    get_occ_list() %>%
    mutate(`NA` = rowSums(.) %>% `==`(0) %>% as.numeric()) %>%
    plot_pie(
        cex = 15,
        digits = 1,
        hsize = 1.5,
        colour = c(get_colors()[c(1, 3)], "gray"),
        title = to_title(y),
        legend = TRUE,
        t = -0.9, # .75,
        width_title = 30,
        width_text = 10
    ) -> p6
# "aneurysm"
# $`7024`$`1`
# [1] "Aortic"
#
# $`16001`$`1`
# [1] "Aortic"

# "chro_car"
# $`17002`$`1`
# [1] "40"

# "pulm_hyp"
# $`10004`$`1`
# [1] "80"

list.map(
    c("sequellae", "laterality"),
    f(i) ~ {
        res <- get_manif(x, i, "sequellae")
        if (compact(res) %>% length() %>% `>`(0)) {
            get_occ_list(
                res,
                fx = function(x) {
                    str_replace_all(x, "(Arthralgia).*", "\\1") %>%
                        str_replace_all(".*pros?thesis.*", "Prosthesis") %>%
                        str_replace_all(".*a(rthrosis).*", "A\\1") %>%
                        str_replace_all(".*(ypertension)", "H\\1")
                }
            ) %>%
                select(-contains(c("None", "Pains"))) %>%
                plot_bar_mcat(
                    collapse = TRUE,
                    cex = 8,
                    width_text = 30,
                    n_collapse = 6,
                    ratio = 5,
                    title = to_title(i)
                )
        }
    }
) %>% compact() -> p4

list_p <- c(p, p2, p3, p4, list(p5)) %>%
    compact() %>%
    list.sort(nrow(.$data)) %>%
    rev()
length(list_p)
plot_grid(
    plotlist = list_p,
    align = "hv",
    nrow = 2,
    ncol = 3,
    rel_heights = c(1.5, 1)
)


ids <- l_manif[["manif"]][apply(l_manif[["manif"]] != 0, 1, any), , drop = FALSE]
clinic %>%
    mutate(ID = as.numeric(C_2643_3796)) %>%
    filter(ID %in% rownames(ids)) %>%
    get_metadata(col = c("C_2686_4014", "C_2686_4015", "C_2686_4016"))
# select(c(ID, C_2643_3798)) %>% write_tsv("temp.tsv")
```

## Pie charts
```{r}
titles <- c("Is active?", "Chronicity", "Distribution", "N. of manifestation", "Laterality")
l_manif0 <- names(l_manif) %in% c("is_active", "active_description", "type", "non_active_description", "laterality") %>%
    l_manif[.]

p1 <- l_manif0 %>%
    lapply(. %>% mutate(., `NA` = rowSums(.) %>% `==`(0) %>% as.numeric())) %>%
    list.map(
        f(i, j, k) ~ {
            colour <- c(get_colors()[c(3, 1)], "gray")
            if (k == "is_active") {
                legend <- c("Yes", "No")
            } else if (k == "active_description") {
                colour <- colour <- c(brewer_pal(, "Reds")(9)[c(3, 6, 9)], "gray")
                legend <- c("First episode", "Recurrent", "Continuous", "NA")
            } else {
                legend <- TRUE
            }
            plot_pie(
                i,
                cex = 15,
                digits = 1,
                hsize = 1.5,
                colour = colour,
                title = titles[j],
                legend = TRUE,
                # t = -0.9,#.75,
                width_title = 30,
                width_text = 30,
                sort = legend
            )
        }
    )

list_p <- c(p1, list(p6)) %>% compact()
plot_grid(
    plotlist = list_p,
    align = "hv",
    nrow = 1,
    ncol = length(list_p)
)
```


```{r}
t_muscu <- l_manif$active_description_osteitis %>%
    apply(1, function(x) any(x == 1) %>% as.numeric()) %>%
    data.frame(`Active osteitis` = .) %>%
    list() %>%
    c(l_manif[2:4]) %>%
    Reduce(cbind, .)
use_data(t_muscu, overwrite = TRUE)

# manifs <- list.map(list_manif, f(i) ~names(i)) %>% unlist() %>% unique()
list.map(c("manif", "symptom", "sequellae"), f(z) ~ {
    list.map(c(vars, "MUCO"), f(x) ~ list.map(list_manif, f(i) ~ list.map(i[[x]][[z]], f(j) ~ names(j))) %>% compact()) %>%
        unlist() %>%
        unique() %>%
        purrr:::discard(function(x) str_detect(x, "\\d")) %>%
        list.map(f(x) ~ list.map(vars, f(y) ~ get_manif(y, x, z, l = list_manif)) %>%
            compact() %>%
            unlist() %>%
            unique() %>%
            sort()) %>%
        compact()
})
```

```{r}
vars0 <- clinic_code[[3]] %>%
    filter(str_detect(group_code, "IMA_ImpactedOrganOrSysTab"))
vars1 <- vars0 %>%
    pull(item_name) %>%
    str_replace("(\\d{1,2}. )", "") %>%
    str_replace("\\s*\\([^\\)]+\\)", "")
manifs <- c("MUSCU", "CARDIO", "GASTRO", "HAEMATO")
# If all disease
# manifs <- c(manifs, "OPHTALMO", "OPHTALMO", "ENT")
# (PULMO) NEURO, URO
# vars <- vars1[c(1, 3:4, 7, 9, 9, 8, 11)]
vars <- vars1[c(1, 3:4, 7, 11)]
manifs <- c("MUCO_ACTIVE_LESIONS", paste0(manifs, "_MANIF"))

filter(clinic, str_detect(C_2643_3796, c("20011", "06027", "06009", "24003", "26103") %>% paste0("^", ., "$", collapse = "|"))) %>%
    mutate(C_2643_3797 = str_remove_all(C_2643_3797, "\\d{2} - ")) %>%
    select(metadata$column_code) %>%
    set_colnames(str_remove_all(metadata$item_name, "\\(.+\\)")) %>%
    select(2:6, 1) %>%
    mutate(Manifestation = c("Neurological", "Musculoskeletal", rep("Gastro-intestinal", 3))) %>%
    relocate(Manifestation) %>%
    kable0()

# plot_pie(tmp1$MUSCU$MANIF_ACTIVE, colour = brewer_pal(, "Reds")(9)[c(3, 9, 6)], digits = 1, cex = 20, hsize = 1.6, legend = FALSE, title = "Chronicity")
# plot_pie(tmp0[[1]][[2]], colour = get_colors()[c(1, 3)], digits = 1, cex = 20, hsize = 1.6, legend = FALSE, title = "Is Active?")
# plot_pie(tmp0[[5]][[2]], colour = get_colors(), digits = 1, cex = 20, hsize = 1.6, legend = FALSE, title = "Diagnostic", width_text = 20) -> p
# plot_bar_mcat(cex = 12, ratio = 2, title = "Is active ?", collapse = TRUE, colors = c(brewer.pal(8, "Set2")[5:6]))

list.map(manifs, f(i, j, k) ~ {
    tmp <- immu_manif(i, df2 = clinic)
    if (!is.null(nrow(tmp))) {
        plot_bar_mcat(tmp, cex = 8, ratio = 4, title = vars1[j], collapse = TRUE)
    }
}) %>% compact() -> p
align_plots(plotlist = p[c(3, 1)]) %>%
    plot_grid(
        plotlist = .,
        nrow = 2,
        ncol = 1,
        # labels = "AUTO",
        rel_heights = c(1.5, 1)
    )
temp <- filter(clinic_code[[1]], str_detect(group_code, paste0("^IMA_ImpactedOrganOrSysTab$")))

df_manifs <- list.map(manifs, f(i) ~ {
    immu_manif(i, df2 = clinic)
})
# df_manifs[[2]] <- df_manifs[[2]][, seq(3)]

# Table
ids <- pull(clinic, 2) %>% as.numeric()
still_manif <- df_manifs %>%
    list.cbind() %>%
    set_colnames(colnames(.) %>% str_remove_all(" \\(.+\\)")) %>%
    as_tibble() %>%
    mutate(ids = ids) %>%
    arrange(ids) %>%
    select(-ids) %>%
    set_rownames(ids) %>%
    cbind(df_manifs0, .)
use_data(still_manif, overwrite = TRUE)
apply(still_manif, 2, sum) %>% kable0()

p <- list.map(df_manifs, f(i, j) ~ {
    plot_bar_mcat(i, cex = 12, ratio = 3, title = vars[j])
})
align_plots(plotlist = p, align = "vh") %>%
    plot_grid(
        plotlist = .,
        nrow = 3,
        ncol = 2,
        # labels = "AUTO",
        rel_heights = c(1.7, 1, 1)
    )
# ((colSums(temp0) / nrow(temp0)) * 100) %>% round(1)
# align_plots(plotlist = c(p2[-1], p2[1])) %>% plot_grid(plotlist = ., align = "vh", nrow = 4, ncol = 2, labels = LETTERS, rel_heights = c(rep(1, 3), 1.5))
```

# Per disease
```{r}
vars <- c("MUCO", vars)
titles <- filter(clinic_code[[1]], column_code %in% vars) %>%
    pull(item_name) %>%
    str_replace("(\\d{1,2}. )", "") %>%
    str_replace("\\s*\\([^\\)]+\\)", "") %>%
    str_replace_all("Ear.*", "ENT") %>%
    str_replace("and", "/")

# Diagnosis
ids <- list.map(vars, f(y) ~ get_manif0(y, "diagnosis", l = list_manif)) %>%
    unlist() %>%
    unique() %>%
    discard(function(x) x == "Chest pain")
res <- list.map(
    ids,
    f(x) ~ {
        list.mapv(
            list_manif,
            f(y) ~ {
                list.search(y, . == x, unlist = TRUE) %>%
                    discard(function(x) x == "FALSE") %>%
                    length() %>%
                    `>`(0) %>%
                    as.numeric()
            }
        )
    }
) %>% list.cbind()
apply(res, 2, sum) %>% plot_bar(
    colour = brewer.pal(4, "Reds")[-1] %>% rev(),
    threshold = 5
)

manifs <- list.map(
    vars[-1], f(y) ~ {
        get_manif(y, "manif", l = list_manif) %>%
            unlist() %>%
            unique() %>% 
            sort() %>% 
            str_remove_all(".*: ") %>%
            str_remove_all(" \\(.*")
    }
    ) %>% c(
        get_manif("MUCO", "active_description", l = list_manif) %>% 
    unlist() %>%
    unique() %>% 
    sort() %>% 
    list(MUCO = .), .
    ) %>% set_names(titles)

symptoms <- list.map(
    c("symptom", "sequellae"),
    f(x) ~{
        list.map(vars, f(y) ~ get_manif(y, x, x, l = list_manif) %>%
    unlist() %>%
    unique() %>% 
    sort()) %>% set_names(titles)
    }
)
ids <- c(symptoms, list(manifs)) %>%
    unlist() %>%
    unique() %>% 
    sort() %>%
     discard(function(x) x %in% c("Arthralgia of the arms", "Des chevilles", "No", "None"))
ids <- list(
    c("Multiple", "Unique"),
    c("First episode", "Recurrent", "Continuous"),
    c(ids)
)
res <- list.map(
    ids,
    f(i) ~ {
        list.map(
    i,
    f(x) ~ {
        list.mapv(
            list_manif,
            f(y) ~ {
                list.search(y, str_remove_all(., ".*: ") %>%
            str_remove_all(" \\(.*") == x, unlist = TRUE) %>%
                    discard(function(x) x == "FALSE") %>%
                    length() %>%
                    `>`(0) %>%
                    as.numeric()
            }
        )
    }
) %>% list.cbind()
        })
titles <- c("Non active manifestations", "Chronicity")
colors <- list(get_colors()[c(3, 1)], brewer.pal(4, "Reds")[-1])
p <- list.map(
    seq(2),
    f(i) ~{
    apply(res[[i]], 2, sum) %>%
    list.map(f(x, y, z) ~ rep(z, x)) %>% unlist() %>% 
    plot_bar_mcat(
        colour = colors[[i]], 
        sample_size = nrow(clinic0),
        title = titles[i],
        width_title = 50,
        hjust_title = 0.5
    )
    }
)

apply(res[[2]], 2, sum) %>%
    list.map(f(x, y, z) ~ rep(z, x)) %>% unlist() %>% 
    plot_bar_mcat(
        colour = , 
        sample_size = 450,
        title = "Non active manifestations",
        width_title = 50
    )
res0 <- res[[3]] %>% as.data.frame() %>% mutate(`Abdominal pain` = ifelse(`Abdominal pain` == 1 | `Acute abdomen` == 1, 1, 0)) %>% select(-`Acute abdomen`)
stat_manifs <- apply(res0, 2, sum) %>% sort(TRUE) %>% head(10)
manif_cat <- names(stat_manifs) %>%
    list.mapv(
        f(x) ~ {
            tmp <- list.which(manifs, f(y) ~ str_detect(x, y) %>% any())
            if (length(tmp) == 0) {
                tmp <- list.which(symptoms[[1]], f(y) ~ if (!is.null(y)) str_detect(x, y) %>% any())
            }
            if (length(tmp) == 0) {
                tmp <- list.which(symptoms[[2]], f(y) ~ if (!is.null(y)) str_detect(x, y) %>% any())
            }
            return(tmp)
            }
        )
# %>% titles[.] 
p2 <- plot_bar(
    stat_manifs,
    colour = GimmeMyPlot:::palette_discrete()[manif_cat], 
    sample_size = nrow(clinic0),
    title = "Manifestations",
    width_title = 50,
    cex = 1.4
)
plot_grid(
    plotlist = c(p, list(p2)),
    align = "hv",
    nrow = 3,
    rel_heights = c(1, 1.1, 2.5)
)

clinic0 <- mutate(clinic0, C_2643_3796 = as.numeric(C_2643_3796)) %>% select(c(C_2643_3796, C_2643_3798))
res1 <- as.data.frame(res0) %>% rownames_to_column("C_2643_3796") %>% mutate( C_2643_3796 = as.numeric(C_2643_3796)) %>% right_join(clinic0)
sample_size <- pull(clinic0, C_2643_3798) %>%
    fct_count() %>%
    arrange(desc(n)) %>% 
    pull(n)
p <- list.map(
    diseases0,
    f(x, y) ~{
        res2 <- filter(res1, C_2643_3798 == x) %>% 
            select(-c(C_2643_3796, C_2643_3798)) %>%
            set_colnames(
                colnames(.) %>% 
                    str_remove_all(".*: ") %>%
                    str_remove_all(" \\(.*")
                )
        stat_manifs <- apply(res2, 2, sum) %>% 
            sort(TRUE) %>%
            discard(function(x) x == 0)  %>%
             head(10)
         manif_cat <- names(stat_manifs) %>%
    list.mapv(
        f(x) ~ {
            tmp <- list.which(manifs, f(y) ~ str_detect(x, y) %>% any())
            if (length(tmp) == 0) {
                tmp <- list.which(symptoms[[1]], f(y) ~ if (!is.null(y)) str_detect(x, y) %>% any())
            }
            if (length(tmp) == 0) {
                tmp <- list.which(symptoms[[2]], f(y) ~ if (!is.null(y)) str_detect(x, y) %>% any())
            }
            return(tmp)
            }
        )
         if (!is.null(manif_cat))
         plot_bar(
            stat_manifs,
            colour = GimmeMyPlot:::palette_discrete()[manif_cat], 
            sample_size = nrow(res2),
            title = paste0(x, ", N = ", sample_size[y]),
            width_title = 50,
            n_max = 10,
            ratio = 4
        )
    #      apply(res2, 2, sum) %>%
    # mapply(function(x, y) rep(x, y), names(.), .) %>%
    # unlist() %>% plot_bar_mcat(colour = rev(manif_cat))
    }
) 

plot_grid(
    plotlist = p,
    nrow = 3,
    ncol = 3,
    align = "hv"
)
```
