---
title: "miRNA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mirna}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
suppressPackageStartupMessages(library(MultiOmics4ImmunAID))
path <- set_environment()
options("tidylog.display" = list())
# options("tidylog.display" = NULL)

# Get the file parameters
name <- "CPM_miRNACounts"
date <- "20221019"
path_data <- file.path(path, "miRNA")
files_all <- list.files(path_data)
pattern <- str_detect(files_all, name)
```

# Metadata
```{r, echo = FALSE}
# Metadata
metadata <- file.path(path_data, files_all[!pattern]) %>% read_excel()

# Samples
# Sample in common
# Visit A
l_metadata <- list.parse(metadata)
l_metadata_A <- list.filter(l_metadata, Visit == "A") %>% list.group(Cell_type)
l_metadata_A_names <- l_metadata_A %>%
    list.map(. %>>% list.mapv(Patient_Id)) %>%
    list.map(f(., i) ~ as.numeric(.) %>% sort())
# Venn(l_metadata_A_names) %>%
#     process_region_data() %>%
#     pull(item)
# plot_venn1(l_metadata_A_names, cex = 1.25, color = get_colors()[c(3, 5, 1, 2)])
# Visit B
l_metadata_B <- list.filter(l_metadata, Visit == "B") %>% list.group(Cell_type)
l_metadata_B_names <- l_metadata_B %>%
    list.map(. %>>% list.mapv(Patient_Id)) %>%
    list.map(f(., i) ~ as.numeric(.) %>% sort())
# plot_venn1(l_metadata_B_names, cex = 1.25, color = get_colors()[c(3, 5, 1, 2)])
# Both visit
# list(l_metadata_A_names, l_metadata_B_names) %>%
#     list.map(unlist(.) %>% unique(.)) %>%
#     set_names(paste(c("1rst", "2nd"), "visit")) %>%
#     plot_venn1(n = 6, color = brewer.pal(9, "Paired")[7:8], vjust = 0) +
#     scale_x_continuous(expand = c(1, 0)) +
#     scale_y_continuous(expand = c(1, 0))

# Samples per visit
fct_count(metadata$Visit) %>%
    set_colnames(c("Visit", "N")) %>%
    kable0()
plot_piechart(
    metadata$Visit,
    colour = brewer.pal(9, "Paired")[7:8],
    cex = 40,
    title = "",
    hsize = 1.6,
    label = FALSE,
    dec = 1
)
# Number of cell types
fct_count(metadata$Cell_type) %>%
    set_colnames(c("Cell type", "N")) %>%
    kable0()
plot_piechart(
    metadata$Cell_type,
    colour = brewer.pal(9, "Set1")[c(seq(3), 5)],
    cex = 40,
    title = "",
    hsize = 1.6,
    label = FALSE,
    dec = 1
)

# Dates
dates <- dmy(metadata$Date_of_experiment) %>% tibble(date = .)
dates <- mutate(
    dates,
    year = year(date),
    month = month(date, label = TRUE, abbr = FALSE),
    day = day(date)
)
days <- as.factor(dates$date) %>%
    fct_count() %>%
    mutate(f = as.Date(f)) %>%
    arrange(f)
ggplot(days, aes(f, n)) +
    geom_line(color = "red") +
    geom_point(color = "red") +
    theme_minimal() +
    scale_x_date(date_breaks = "1 month", date_labels = "%Y (%b)") +
    ylab("Nb. samples") +
    xlab("")

# Samples per years
as.factor(dates$year) %>%
    fct_count() %>%
    set_colnames(c("Year", "N")) %>%
    kable0()
# Sample per months
# lapply(unique(dates$year), function(i) {
#     dates[dates$year == i, ] %>%
#         pull(month) %>%
#         as.factor() %>%
#         fct_drop() %>%
#         fct_count()
# })
format(dates$date, "%Y-%m") %>%
    fct_count() %>%
    mutate(f = ym(f)) %>%
    mutate(year = year(f), month = format(f, "%B")) %>%
    select(month, n) %>%
    set_colnames(str_to_title(colnames(.))) %>%
    kable0("r") %>%
    pack_rows("2021", 1, 1) %>%
    pack_rows("2022 (N = 595)", 2, 6)
# format(dates$date, "%Y-%m") %>%
#     fct_count() %>%
#     mutate(f = ym(f)) %>%
#     ggplot(aes(f, n)) +
#     geom_line(color = "red") +
#     geom_point(color = "red") +
#     theme_minimal() +
#     scale_x_date(date_breaks = "1 month", date_labels = "%Y (%b)") +
#     ylab("Nb. samples") +
#     xlab("")
```

# Demographic effects
```{r, echo = FALSE}
# Subset in common with miRNA data
ids <- metadata$Patient_Id %>%
    unique() %>%
    as.numeric() %>%
    sort()
length(ids)
data(clinic)
clinic_intersect <- filter(
    clinic_transf,
    str_detect(
        immun_aid_identifier,
        paste0("^", ids, "$", collapse = "|")
    )
)

# Descriptive stats
vars <- c("BMI", "age_at_inclusion_time")
keys <- c(6, 5)
list.map(as.list(vars), f(j, i) ~ {
    plot_violin0(
        pull(clinic_intersect, vars[i]),
        brewer.pal(8, "Set2")[keys[i]],
        size = 3,
        title = ""
    )
}) %>%
    plot_grid(
        plotlist = .,
        align = "vh",
        ncol = 2
    )
clinic_intersect %>%
    select(all_of(vars)) %>%
    descriptive_stats() %>%
    kable0()

# Age
df_years <- mutate(
    clinic_intersect,
    years = cut(
        age_at_inclusion_time,
        breaks = seq(0, 90, 10),
        right = FALSE
    )
) %>% drop_na(gender)
df_year_gender <- as.list(levels(clinic_intersect$gender)) %>%
    list.map(f(i) ~ {
        fct_count(subset(df_years, gender == i)$years) %>%
            mutate(perc = (n / sum(n) * 100) %>% round(1), Gender = i)
    })
df_year_gender[[1]]$n <- -df_year_gender[[1]]$n
df_year_gender <- list.stack(df_year_gender)
df_year_gender <- df_years$years %>%
    fct_count() %>%
    right_join(df_year_gender, by = "f")
# Age pyramid
ggplot(df_year_gender, aes(x = n.y, y = f, fill = Gender)) +
    geom_col(width = 0.95, alpha = 0.75) +
    geom_text(
        aes(label = ifelse(Gender == "Male", n.x, "")),
        hjust = -1,
        color = "gray",
        size = 5
    ) +
    theme_minimal(base_family = "Verdana", base_size = 18) +
    scale_fill_manual(values = c("#3438a7", "#38bcbd")) +
    scale_x_continuous(
        name = "Count",
        labels = abs,
        expand = c(0.1, 0)
    ) +
    scale_y_discrete(
        name = "Age (decades)",
        labels = function(x) {
              str_remove_all(x, "\\[|\\)") %>% str_replace_all(",", "-")
          }
    )

# Gender, ethnicity
plot_piechart(
    clinic_intersect$patient_ethnicity,
    colour = c("#af3e40", "#eaaab0", "gray80"),
    title = "",
    cex = 40,
    dec = 1,
    label = FALSE,
    hsize = 1.6
)
plot_piechart(
    drop_na(clinic_intersect, gender) %>% pull(gender),
    colour = c("#3438a7", "#38bcbd"),
    cex = 40,
    title = "",
    hsize = 1.6,
    label = FALSE,
    dec = 1
)

# Disease, clinical_center

plot_bar_mcat(clinic_intersect$disease, cex = 3, wrap = 50)
plot_bar_mcat(clinic_intersect$clinical_center, cex = 3, wrap = 50)
```

# miRNA QC
```{r, echo = FALSE}
file_names <- files_all[pattern]
cells <- str_replace_all(file_names, paste0(name, "_(.*)_", date, ".xlsx"), "\\1")
files <- file.path(path_data, files_all[pattern]) %>%
    lapply(read_excel) %>%
    set_names(cells)

sapply(files, dim)
# Check that all the miRNA in row are identical
all(sapply(files, function(i) {
    pull(i, "...1") %>%
        unique() %>%
        length()
}) == nrow(files[[1]]))
# Check that all the samples in column are different
get_intersection(sapply(files, colnames)) %>%
    unlist() %>%
    length() == 1

# Data cleaning
mirna <- Reduce(full_join, files) %>%
    select(-1) %>%
    t() %>%
    tibble() %>%
    update_columns(ncol(.), as.numeric) %>%
    set_colnames(pull(files[[1]], 1))
colnames(mirna) <- colnames(mirna) %>% str_remove_all("^hsa-(let|miR)-")

cst <- mirna %>%
    dplyr::select_at(setdiff(names(.), names(remove_constant(.)))) %>%
    unique() %>%
    colnames() %>%
    str_remove_all("hsa-miR-")
length(cst) / ncol(mirna) * 100

mirna <- sort(colnames(mirna)) %>%
    select(mirna, .) %>%
    clean_data(FALSE)

# Number of 0 an NAs per variables
temp <- diagnose_numeric(mirna)
zeros <- select(temp, zero) %>%
    arrange(desc(zero)) %>%
    pull(zero)
zeros <- (nrow(mirna) - zeros) / nrow(mirna) * 100
plot_histo0(zeros)
nas <- list.mapv(colnames(mirna), f(i) ~ {
    pull(mirna, i) %>%
        is.na() %>%
        length()
})
nas <- nrow(mirna) - nas
summary(nas)

# Skewness, kurtosis
un_mirna <- unlist(mirna)
tibble(un_mirna) %>%
    descriptive_stats() %>%
    kable0()
samp <- log10(sample(un_mirna, 1e4) + 1)
p1 <- plot_violin0(samp, pch_colour = "red", pch_alpha = 0.1, colour = NA)
skew <- list.map(
    as.list(colnames(mirna)),
    f(i) ~ skewness(pull(mirna, i), na.rm = TRUE)
) %>% unlist()
kurt <- list.map(
    as.list(colnames(mirna)),
    f(i) ~ kurtosis(pull(mirna, i), na.rm = TRUE)
) %>% unlist()
list.map(list(skew, kurt), f(i) ~ plot_histo0(i)) %>%
    plot_grid(
        plotlist = .,
        align = "vh",
        ncol = 2
    )
p2 <- colnames(mirna)[which.max(kurt)] %>%
    pull(mirna, .) %>%
    plot_violin0(pch_colour = "red", pch_alpha = 0.3, colour = NA)
plot_grid(p1, p2,
    align = "vh",
    ncol = 2
)
plot_violin0(kurt, probs = c(0.1, 0.9), pch_alpha = 0.2, pch_colour = "black")

temp0 <- update_columns(mirna, names(mirna), function(i) log10(i + 1)) %>%
    descriptive_stats()
tmp <- apply(temp0[, -1], 2, mean) %>% round(1)
tmp <- data.frame(
    "Mean_SD" = paste0(tmp[1], "\u00b1", tmp[3]),
    "Median_IQR" = paste0(tmp[2], "\u00b1", tmp[4]),
    Range = paste(
        tmp[7],
        tmp[8],
        sep = "-"
    ), as.data.frame(tmp[9:13]) %>% t()
)

# colnames(tmp) %>% str_replace("_", "\u00b") %>% set_colnames(tmp, .)
quant <- quantile(un_mirna, c(0, 1))
quant[2] <- format(quant[2], scientific = TRUE, digits = 2)
tmp[3] <- paste(quant, collapse = "-")
tmp[6] <- "***"
tmp[7] <- paste0(tmp[7], "%")
# un_mirna %>% t() %>% data.frame() %>% descriptive_stats()

col_names <- sapply(files, function(x) colnames(x)[-1]) %>%
    unlist() %>%
    str_remove_all("^S|02PB\\d{1,2}")

t_mirna <- t(mirna) %>%
    data.frame() %>%
    tibble() %>%
    set_colnames(col_names)
# TODO: sort data by IDs

t_mirna0 <- scale(t_mirna) %>%
    data.frame() %>%
    tibble() %>%
    set_colnames(colnames(t_mirna))
mirna0 <- scale(mirna) %>%
    data.frame() %>%
    tibble() %>%
    set_colnames(colnames(mirna))
# Outliers samples
outliers <- sapply(colnames(t_mirna), function(i) {
    t_mirna0 %>%
        pull(i) %>%
        get_outliers(c = 3, method = "sd", replace = FALSE)
})
n <- outliers %>%
    list.mapv(f(., x) ~ length(.)) %>%
    sort()
as.data.frame(n) %>% descriptive_stats()
sum(n) / dim(mirna) %>% prod() * 100
as.data.frame(n) %>% plotHistogram(df = ., n = 50) -> p10
n0 <- set_names(n, str_extract(names(n), "[BDM]C|NK$"))
sapply(cells, function(i) n0[names(n0) == i]) %>% sapply(mean)
outlier_vars <- outliers %>% list.map(colnames(mirna)[as.numeric(names(.))])
unlist(outlier_vars) %>%
    fct_count() %>%
    set_rownames(.$f) %>%
    as.data.frame() %>%
    select(2) %>%
    plotHistogram(df = .) -> p1
# as.data.frame(n) %>% mutate(Cell = str_extract(rownames(.), "[BDM]C|NK$")) %>% group_by(Cell)

# Outliers vars
outliers0 <- sapply(colnames(mirna), function(i) {
    mirna0 %>%
        pull(i) %>%
        get_outliers(c = 3, method = "sd", replace = FALSE)
})
n0 <- outliers0 %>%
    list.mapv(f(., x) ~ length(.)) %>%
    sort()
as.data.frame(n0) %>% descriptive_stats()
sum(n0) / dim(mirna) %>% prod() * 100
sum(n0)
as.data.frame(n0) %>% plotHistogram(df = ., n = 50) -> p20
outlier_inds <- outliers0 %>% list.map(colnames(t_mirna)[as.numeric(names(.))])
outlier_inds0 <- unlist(outlier_inds) %>%
    fct_count() %>%
    set_rownames(.$f) %>%
    as.data.frame() %>%
    select(2)
plotHistogram(df = outlier_inds0, n = 50) -> p2
outlier_inds0 %>%
    mutate(Cell = str_extract(rownames(.), "[BDM]C|NK$")) %>%
    group_by(Cell) %>%
    summarise(mean = mean(n, na.rm = TRUE)) # %>% mutate(value = n) %>% descriptive_stats() %>% kable0()

plot_grid(
    p10 + scale_y_continuous(expand = c(0.1, 0)),
    p20 + scale_y_continuous(expand = c(0.1, 0)),
    align = "vh",
    ncol = 2
)

outliers_celltype <- mutate(
    outlier_inds0,
    Cell = str_extract(rownames(outlier_inds0), "[BDM]C|NK$")
)
pivot_longer(outliers_celltype, !Cell) %>%
    group_by(name) -> stats
# filter(!is.na(value)) %>%
anova_test(stats, value ~ Cell) %>% add_significance0() -> anov
kruskal_test(stats, value ~ Cell) %>% add_significance0() -> ks
# post_hoc <- tukey_hsd(stats, value ~ Cell)
post_hoc <- dunn_test(stats, value ~ Cell)
post_hoc$p.adj.signif <- str_replace_all(post_hoc$p.adj.signif, "\\*\\*\\*\\*", "\\*\\*\\*")
pwd <- post_hoc %>% add_xy_position(x = "Cell")

outliers_celltype %>%
    plot_violin0(
        class = "Cell",
        value = "n",
        guide = TRUE,
        title = "",
        colour = get_colors()[-4][seq(4)],
        caption = print_mean_test(ks, method = "ks"),
        pch_alpha = 0.25
    ) + stat_pvalue_manual(pwd, label = "p.adj.signif", color = "darkgray")


# Correlation
t_mirna %>%
    slice(sample(nrow(.), 50)) %>%
    select(sample(ncol(.), 100)) -> x
plot_corr0(x)
get_corr(x, TRUE, method = "spearman") %>%
    tibble() %>%
    descriptive_stats() %>%
    kable0()
plot_corr_network(x)

# correlation(mirna, method = "spearman", p_adjust = "holm") -> r1
# correlation(t_mirna, method = "spearman", p_adjust = "holm") -> r2
# plot_corr0(mirna) -> p
# plot_corr0(t_mirna) -> p2
# plot_corr_network(mirna) -> p3
```

