---
title: "omics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{omics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages(library(MultiOmics4ImmunAID))
path <- set_environment()
```

# Proteomics

## ELISA

```{r elisa}
# prot_path <- file.path(path, "ELISA/Batch1")
batch <- 1
date <- "20211116"
prefix <- paste(date, "Data", "", sep = "_")
blocks <- c("Calprotectin", "S100A12")
files_raw <- list()

# Read files
for (i in seq_along(blocks)) {
    files_raw[[i]] <- read_excel(
        file.path(
            path,
            "ELISA/Batch1",
            paste0(prefix, blocks[i], "_batch_", batch, ".xlsx")
        ),
        skip = 5
    )
}
# Clean colnames, remove empty rows, cols and constants
files <- lapply(files_raw, clean_data)
# Common IDs ?
setdiff(files[[1]][, 1], files[[2]][, 1]) # character(0) = Nope !
# Bind tables
elisa <- cbind(files[[1]], files[[2]][, 4, drop = FALSE]) %>% tibble()
colnames(elisa)[4:5] <- blocks

# Set constants into the attributes
for (i in 4:5) {
    var <- colnames(files_raw[[1]])[i]
    attributes(elisa)[var] <- unique(files_raw[[1]][, var])
}

# Convert into types
str(elisa)
elisa$patient_id <- as.character(elisa$patient_id)
elisa$visit <- factor(elisa$visit)

# View factor
diagnose_category(
    elisa[, -c(1:2)],
    top = 500
)
# %>% filter(is.na(levels))
# %>% filter(ratio <= 0.01)

# elisa %>% count(visit)  %>% mutate(freq = n / sum(n))
# elisa %>% count(patient_id, sort = TRUE)  %>% mutate(freq = n / sum(n))

diagnose_numeric(elisa) # %>% filter(minus > 0 | zero > 0)
# View duplicates
elisa %>% get_dupes("patient_id")

# Descriptive stats general
plot_str(elisa)
introduce(elisa)
plot_intro(elisa)
diagnose(elisa) %>%
    filter(missing_count > 0) %>%
    arrange(desc(missing_count))

# Descriptive stats per variables
# qplot(Calprotectin, data = elisa)
plot_bar(elisa)
plot_histogram(elisa)
# plot_boxplot(elisa)
skim(elisa)
list.map(
    colnames(elisa)[4:5],
    f(i, j) ~ {
        pull(elisa, i) %>%
            plot_violin0(colour = get_colors()[j], title = i)
    }
) %>% plot_grid(
    plotlist = .,
    align = "vh",
    ncol = 2
)


# str_squish

# Correlation
plot_correlation(elisa)
# continuous data
plot_correlation(elisa, type = "c")
get_correlation(elisa)
plot_correlate(elisa)

# Normality
plot_qq(elisa)
# Do not follow the normality with Shapiro-Wilk
plot_normal(elisa)


# Missing data
# set_missing
plot_missing(elisa)
find_na(elisa)
# impute_na(elisa)

# Outliers
# find_outliers(elisa) # wich variables
diagnose_outlier(elisa) %>% filter(outliers_ratio > 0)
plot_outlier(elisa, typographic = FALSE)
elisa_w_out <- elisa
for (i in find_outliers(elisa)) {
    var <- colnames(elisa)[i]
    elisa_w_out[var] <- imputate_outlier(elisa, all_of(var), method = "mean")
}

# PCA
pca_df <- na.omit(elisa[, 4:5])
plot_prcomp(pca_df, nrow = 2, ncol = 2)

# eda_report(elisa)

elisa <- finalise_data(elisa)
use_data(elisa, overwrite = TRUE)
```

## MS
```{r ms}
ms <- lapply(
    seq(5),
    function(i) {
        b <- ifelse(i < 3, 1, 2)
        read_csv(
            file.path(
                path,
                "MS",
                paste0("Batch", b),
                "data",
                paste0("log2_lfq_proteinGroups_S", i, ".csv")
            )
        )
    }
)

sapply(ms, dim)

ms_codes <- lapply(
    seq(2),
    function(i) {
        read_excel(
            file.path(
                path,
                "MS",
                paste0("Batch", i),
                "Annotations",
                "Samples_annotations.xlsx"
            )
        ) %>%
            clean_names()
    }
)

ms_codes_tot <- Reduce(rbind, ms_codes)
ms_codes_tot <- update_columns(ms_codes_tot, c(3:4, 6), as.factor) %>%
    update_columns(5, dmy)
summary(ms_codes_tot)

# Check for patient intersection : None
# get_intersection(lapply(ms, colnames))

# Get the intersection of the prot id
plot_venn(
    lapply(ms, function(i) i$MajorProteinIds),
    snames = paste("", seq(5))
)

# Combine batches
ms_tot <- Reduce(full_join, ms)
metadata <- get_intersection(lapply(ms, colnames))[[1]]
# Reorder the columns
ms_tot <- select(ms_tot, all_of(metadata), everything())

# Get a list of all the prot names
list_prot_names <- str_split(ms_tot$ProteinName, ";") %>%
    reformat()
list_gene_names <- str_split(ms_tot$GeneName, ";") %>%
    reformat()

# Join by samples
ms_codes_tot$sample_barcode <- str_replace(ms_codes_tot$sample_barcode, "_", "-")
# identical(colnames(ms_tot)[-seq(4)], ms_codes_tot$sample_barcode)

ms <- t(ms_tot) %>%
    t2tibble() %>%
    slice(-seq(4)) %>%
    clean_data(FALSE) %>%
    update_columns(seq(ncol(.)), as.numeric)
rownames(ms) <- ms_codes_tot$sample_barcode
colnames(ms) <- ms_tot$MajorProteinIds

ms_prot_code <- select(ms_tot, 2:4) %>%
    update_columns(3, as.factor)
rownames(ms_prot_code) <- ms_tot$MajorProteinIds

ms_sample_code <- ms_codes_tot[, -1]
rownames(ms_sample_code) <- ms_codes_tot$sample_barcode

use_data(ms, overwrite = TRUE)
use_data(ms_prot_code, overwrite = TRUE)
use_data(ms_sample_code, overwrite = TRUE)

get_correlation(ms, 0.9999)
# diagnose_outlier(ms) %>% filter(outliers_ratio > 0) %>% arrange(desc(outliers_ratio)) %>% select(-c(2, 4))
ms2 <- ms
colnames(ms2) <- seq(ncol(ms2))
# vis_miss(ms2)

qc <- rownames(ms)[str_detect(rownames(ms), "QC")]
length(qc)
```

# Transcriptomics
```{r}
rna_sample <- read_delim(file.path(path, "processed_gene_matrix.txt"), delim = " ", n_max = 1, col_names = FALSE)
rna <- read_delim(file.path(path, "processed_gene_matrix.txt"), delim = " ", skip = 1, col_names = FALSE)
rna_t <- t(rna)[-1, ] %>%
    as_tibble() %>%
    clean_data(clean_name = FALSE) %>%
    update_columns(seq(ncol(.)), as.numeric)
colnames(rna_t) <- rna %>% pull(1)
rownames(rna_t) <- rna_sample

# Number of visit A or B
l_visits <- list.map(
    c("A", "B"),
    f(i) ~ {
        detect_row(rna_t, i) %>%
            which() %>%
            slice(rna_t, .)
    }
)
sapply(l_visits, nrow) # 183  32

# Rename, reorder by samples
row_names <- list.map(l_visits, f(.) ~ {
    rownames(.) %>%
        str_remove_all("(A|B)05PB1") %>%
        as.numeric()
})
# row_names %>%
#     set_names(paste(c("1rst", "2nd"), "visit")) %>%
#     plot_venn1(n = 6, cex = 2, color = brewer.pal(9, "Paired")[7:8], vjust = 0) +
#     scale_x_continuous(expand = c(0.2, 0)) +
#     scale_y_continuous(expand = c(0.2, 0))
# 13006, 3005, 24005
data("clinic_transf")
# c(row_names, list(clinic_transf$immun_aid_identifier)) %>%
#     set_names(c(paste(c("1rst", "2nd"), "visit"), "Clinic")) %>%
#     plot_venn1(n = 6, cex = 1.5, color = c(brewer.pal(9, "Paired")[7:8], "blue"), vjust = 0) +
#     scale_x_continuous(expand = c(0.3, 0)) +
#     scale_y_continuous(expand = c(0.2, 0))
#
# ids <-  list.map(seq(3), f(i) ~ filter(clinic_transf, batch == i) %>% pull(2))
# c(row_names, ids) %>%
#     set_names(c(paste(c("1rst", "2nd"), "visit"), paste(c("1rst", "2nd", "3rd"), "batch"))) %>%
#     plot_venn1(n = 6, color = c(brewer.pal(9, "Paired")[7:8], brewer.pal(9, "Blues")[c(5, 6, 9)]), vjust = 0)
#
# c(row_names[1], ids[1]) %>%
#     set_names(c(paste(c("1rst"), "visit"), paste(c("1rst"), "batch"))) %>%
#     plot_venn1(n = 6, cex = 2, color = c(brewer.pal(9, "Paired")[7], brewer.pal(9, "Blues")[c(5)]), vjust = 0) +
#     scale_x_continuous(expand = c(0.2, 0)) + scale_y_continuous(expand = c(0.2, 0))
#
# c(row_names[1], ids) %>%
#     set_names(c(paste(c("1rst"), "visit"), paste(c("1rst", "2nd", "3rd"), "batch"))) %>%
#     plot_venn1(n = 6, cex = 1.3, color = c(brewer.pal(9, "Paired")[7], brewer.pal(9, "Blues")[c(5, 6, 9)]), vjust = 0) +     scale_x_continuous(expand = c(0.2, 0)) +
#     scale_y_continuous(expand = c(0.1, 0))

visit_a <- mutate(l_visits[["A"]], id = row_names[["A"]]) %>%
    arrange(id) %>%
    select(-c("id"))
visit_a <- sort(row_names[["A"]]) %>% set_rownames(visit_a, .)

# Rename variable
colnames(visit_a)[1] <- str_remove_all(colnames(visit_a)[1], "^X")

rna <- visit_a
use_data(rna, overwrite = TRUE)
```

# QC RNA
```{r}
# Which clinical metadata not provided
setdiff(rownames(rna), clinic_transf$immun_aid_identifier)
# "8002"  "26003"
# Which disease those only in Visit B
setdiff(row_names[[2]], row_names[[1]]) %>%
    paste0("^", ., "$", collapse = "|") %>%
    str_detect(clinic_transf$immun_aid_identifier, .) %>%
    filter(clinic_transf, .) %>%
    select(seq(3)) # %>% pull(3)
# "Adult-Onset Still’s Disease (AOSD)" "Behçet (Vasculitis)" "Inflammation of unknown origin"
clinic_proc <- clinic_transf %>%
    filter(str_detect(
        disease,
        replace_parenthesis(paste(
            c("SOJIA", "AOSD"),
            collapse = "|"
        ))
    ))
(!clinic_proc$immun_aid_identifier %in% rownames(rna)) %>%
    filter(clinic_proc, .) %>%
    select(seq(3))
clinic_intersect <- filter(clinic_proc, rownames(clinic_proc) %in% rownames(rna))
rna_intersect <- filter(rna, rownames(rna) %in% rownames(clinic_intersect))
rna_clinic_still <- list(clinic = clinic_intersect, rna = rna[[2]])
use_data(rna_clinic_still, overwrite = TRUE)
```

# Session information
```{r end, echo = FALSE}
sessionInfo()
```
