utils::globalVariables(
    c(
        ".",
        "cex",
        "cex_main",
        "cex_sub",
        "coef_corr",
        "column_code",
        "item_name",
        "missing_percent",
        "value",
        "var1",
        "var2",
        "name",
        "variable",
        "variables"
    )
)
